### ISSUE TITLE
数字字母连续串的切分粒度问题

### ISSUE THREAD

**Issue by weiweiwang** [NLPchina/ansj_seg#100]
http://t.cn/8Fq9GWz中的8Fq9GWz被切分成了8   fq   9   gwz

对比下jieba分词是把8Fq9GWz切分到一起了
http://jiebademo.ap01.aws.af.cm
http/eng :/x //x //x t/eng ./m cn/eng //x 8/m Fq9GWz/eng

目前在用ansj-seg做一些文本分类的工作，由于上面的切分导致了一些分类精度的问题，lz帮忙看看这个问题如何解决？

**Comment by QA-long** [comment]
楼主你好，我用Ansj分词 招聘信息  例如“1、熟练掌握java、J2EE系统开发，精通SSH等框架，有过接口平台设计经验者优先。”  
对于 “J2EE” “SL4J”这种 的名词 都被拆分成开了 变成了“J/EE SL/J” 有什么办法解决吗？
