### ISSUE TITLE
自定义分词器无法识别

### ISSUE THREAD

**Issue by 1144742081** [NLPchina/ansj_seg#145]
eclipse中新建java工程在使用自定义分词器的时候无法识别，请问是什么原因？

所用jar：ansj_seg-2.0.6.jar      nlp-lang-0.2.jar
工程目录src下library.properties内容：userLibrary=library/my.dic
工程目录下有library文件夹，其中有my.dic
eclipse运行打印信息：
八月 20, 2014 12:29:52 下午 org.ansj.library.UserDefineLibrary loadFile
信息: init user userLibrary ok path is : D:\Program Files\workspace\AnsjSeg\library\my.dic
八月 20, 2014 12:29:52 下午 org.ansj.library.UserDefineLibrary initAmbiguityLibrary
信息: init ambiguityLibrary ok!
八月 20, 2014 12:29:52 下午 org.ansj.library.DATDictionary loadDAT
信息: init core library ok use time :613
八月 20, 2014 12:29:52 下午 org.ansj.library.NgramLibrary <clinit>
信息: init ngram ok use time :327

**Comment by w64852908** [comment]
0.0好吧。。。我的每次都报错加载不到自定义词典，因为我是建一个txt文件然后改成dic后缀的。。。。
