### ISSUE TITLE
运行ansj_seg 报 OutOfMemory Java Heap Space 异常

### ISSUE THREAD

**Issue by theseusyang** [NLPchina/ansj_seg#163]
在 Mac OS 10.9平台下，JVM 为JDK6.0_23的环境中运行 ansj_seg1.1、1.4.1、2等版本OutOfMemory Java Heap Space 异常错误。将 JDK 升级到 JDK7后再次运行 ansj_seg 错误会消失。

**Comment by ansjsun** [comment]
如果没问题我关了。顺路说一下你的版本太低

**Comment by theseusyang** [comment]
关吧，没问题了
