### ISSUE TITLE
数字发现问题

### ISSUE THREAD

**Issue by lixiangnlp** [NLPchina/ansj_seg#164]
我发现，例如这句：计划建立一个5万公顷面积的航天站

分词结果会是“一个5万”成为一个词

另外，例如“一2月11日”，会切成“一2月 11日”

能否对阿拉伯数字识别做一个处理

**Comment by doubler** [comment]
现在看，此bug貌似还是没有修复的呢。

**Comment by ansjsun** [comment]
目前这个版本是修了的。。。计划/n,建立/v,一个/m,5万公顷/mq,面积/n,的/u,航天站/n
