### ISSUE TITLE
google语义模型用到的词与词之间的关联频率

### ISSUE THREAD

**Issue by zteny** [NLPchina/ansj_seg#169]
org.ansj.domain.BigramEntry 提及的 ”google语义模型用到的词与词之间的关联频率“ 能提供论文的名称吗？

**Comment by ansjsun** [comment]
http://baike.baidu.com/link?url=Hj4m8ol8LcIHzqD9J4M132jeCMWR1gn42_ntKaQZp17awwd3O_K-aBsrlL21QWmue7EyB--o1EB_NSChyh1oa_ 是这个
