### ISSUE TITLE
关于修改default.dic词性

### ISSUE THREAD

**Issue by yeyefengisme** [NLPchina/ansj_seg#170]
你好！在修改default.dic中词语词性后，再去获取该词词性仍然是原始词性，不能修改里面的词性吗？谢谢

**Comment by ansjsun** [comment]
List<Term> parse = ToAnalysis.parse(string) ;
FilterModifWord.modifResult(parse) ;

这样就可以了

**Comment by yeyefengisme** [comment]
非常感谢
