### ISSUE TITLE
请教，自定义词性，有一部分无法替换系统原油词性，怎么解决

### ISSUE THREAD

**Issue by yeyefengisme** [NLPchina/ansj_seg#171]
如下代码：我想修改“湖北”的词性，但分出的词还是 “增加新词例子:[湖北/ns]”,除了地名外还有这个"教授"等词，不能覆盖系统词性
UserDefineLibrary.insertWord("教授", "userDefine", 1000);
List parse = ToAnalysis.parse("清华大学教授") ;
new NatureRecognition(parse).recognition() ;
FilterModifWord.modifResult(parse);
请问有没有什么解决办法？再次打扰，谢谢！

**Comment by ansjsun** [comment]
主要是这句

```
parse=FilterModifWord.modifResult(parse);

```

package org.ansj.demo;

import java.util.List;

import org.ansj.domain.Term;
import org.ansj.library.UserDefineLibrary;
import org.ansj.recognition.NatureRecognition;
import org.ansj.splitWord.analysis.ToAnalysis;
import org.ansj.util.FilterModifWord;

public class FilterAndUpdateNatureDemo {
	public static void main(String[] args) {

		// 加入停用词
		FilterModifWord.insertStopWord("并且");
		FilterModifWord.insertStopWord("但是");

		// 加入过滤词性词性
		FilterModifWord.insertStopNatures("w","m","null") ;
		

		List<Term> parse = ToAnalysis.parse("停用词过滤了.并且修正词143922950性为用户自定义词性.但是你必须.must.设置停用词性词性词典");
		new NatureRecognition(parse).recognition();
		System.out.println(parse);
		
		UserDefineLibrary.insertWord("停用词", "userDefine", 1000);

		// 修正词性并且过滤停用
		parse = FilterModifWord.modifResult(parse);

		System.out.println(parse);

	}
}

**Comment by tuoxin126** [comment]
如果通过程序无法更改，是不是考虑将项目重新编译，下载这个项目的源码，有一个目录里面有词库文件，直接更改源。
----- 原始邮件 -----
发件人：ansj <notifications@github.com>
收件人：NLPchina/ansj_seg <ansj_seg@noreply.github.com>
主题：Re:_[ansj_seg]_请教，自定义词性，有一部分无法替换系统原油词性，怎么解决_(#171)
日期：2015年01月21日 11点18分

Closed #171.

&mdash;

**Comment by yeyefengisme** [comment]
词库在一边，直接为文件中修改的

**Comment by ansjsun** [comment]
这个问题解决了吗？？我怎么看不懂e了

**Comment by yeyefengisme** [comment]
呃呃，完了我也开始晕了，等我捋一捋

**Comment by yeyefengisme** [comment]
酱紫:版本是ansj 0.9低版本，需求是要将所有的地名如"湖北/ns"中的词性换成自定义的，问题是用类似上述方式时如果后面再要调词性的时候不使用//updateDic.put("湖北", "123");这种修改词性的语句，只用后面这个parse =FilterModifWord.modifResult(parse);还是不行，非要每次两个一起用才行，这样的话我要更改的批量词性还是要存在数据库里面.
--------------------------
想知道怎么样手动或者永久的按照我的自定义词性改了，之后就可以直接调用而不需要再调用类似updateDic.put("湖北", "123");修改词性的语句
---------------------------
不知道我描述清楚没有？

**Comment by ansjsun** [comment]
版本太老了。0.9i 不一定支持词性修正。。。还是用最新的吧

**Comment by yeyefengisme** [comment]
嗯，这几天先应付了，周末用自己的电脑在试试。
