### ISSUE TITLE
求手动方式永久覆盖系统词性

### ISSUE THREAD

**Issue by yeyefengisme** [NLPchina/ansj_seg#172]
你好，感谢你的耐心回复.，对于parse=FilterModifWord.modifResult(parse);方法可以覆盖词性，但当我再次使用的时候还需要修改词性的语句，
 想通过手动改系统词表或者自定义词表的方式，覆盖与原系统重复的词的词性后永久生效，请问有解决方法吗?
请告知方法，谢谢额

**Comment by ansjsun** [comment]
我还是建议你包装个方法每次进行处理。除非你对速度要求特别高。。建议不要修改核心词典。可能会造成不可想象的错误。包括后期无法同步升级。。如果这个需求很强烈。年后我们计划出3.x版本。你可以把这个需求实现。短期内a建议还是用arse=FilterModifWord.modifResult(parse); 一行代码而已

**Comment by yeyefengisme** [comment]
手动在核心词库里面改了。比如"教授"的一组词性为n=76手动改成n/define=76，这样会造成不可预料的后果么？

**Comment by ansjsun** [comment]
你要问我..我只能说不要修改核心词典..用户自定义词典随便修改..核心词典修改...后..1.你无法后续版本升级..2.可能在词性识别或者其他地方发生异常..既然说了不可预料.那么就是不可预料..
