### ISSUE TITLE
词性获取出userDefine是肿么回事？

### ISSUE THREAD

**Issue by yeyefengisme** [NLPchina/ansj_seg#174]
取出一个词的词性值为userDedine

**Comment by ansjsun** [comment]
是用户自定义词典的词性

**Comment by yeyefengisme** [comment]
用户词典中没有这个词啊

**Comment by yeyefengisme** [comment]
还有一些词在default.dic 中有在arrays.dic中没有，我把这个词从default中删除，但分词还能分出带词性的这个词。这是怎么回事？自动识别出来的词性吗？

**Comment by ansjsun** [comment]
我感觉你用户自定义词典加载多了.程序启动的适合看下用户自定义词典的加载路径是否是你现在用的用户自定义词典

**Comment by ansjsun** [comment]
如果词语未定义词性默认为userdefine
