### ISSUE TITLE
关于词性标注歧义的问题怎么解决？

### ISSUE THREAD

**Issue by jingzhongxu** [NLPchina/ansj_seg#175]
像阿里员工词性标注被标注为 阿里/ns，员工/n；如果我把阿里员工 阿里/ns，员工/n放到歧义字典里，比方以后遇到阿里的员工，阿里还是被标注为ns，如果在歧义字典里将阿里标注为ntc，那么像阿里地区中的阿里又被标注为ntc，像百度也有类似标注错误。像这种问题目前好像有什么好的解决方案吗？谢谢

**Comment by ansjsun** [comment]
修改default.dic词典中的词性。如果还不生效。调用词性修复让用户自定义词典优先
