### ISSUE TITLE
分词后结果不同，造成索引后，查询无结果

### ISSUE THREAD

**Issue by boyhooda** [NLPchina/ansj_seg#176]
System.out.println(IndexAnalysis.parse("创造最有利条件"));
System.out.println(IndexAnalysis.parse("最有利"));

[创造/v, 最/d, 有利/a, 条件/n]
[最/d, 有/v, 利/n]

**Comment by ansjsun** [comment]
查询的时候用toanalysis

发自我的 iPhone
