### ISSUE TITLE
关于ToAnalysis和NlpAnalysis分词的具体处理过程的疑问

### ISSUE THREAD

**Issue by NationalYu** [NLPchina/ansj_seg#177]
作者您好！
    我在具体研读和调试代码的过程中，发现了一些问题，烦您解答一下：

   1.您的主页里提到：“这是一个基于google语义模型+条件随机场模型的中文分词的java实现”，但是在具体程序里，我只发现了只有NlpAnalysis一处使用了CRF分词的地方，并且这个过程是在已经算完最优路径之后，对于一些分词错误并没有起到矫正的作用，请问CRF是只用在了这里吗？

  2.“基于google语义模型”这一块我不太明白在程序里体现的地方，是指在生成词图的过程中，通过加载bigramdict.dic里的bigram统计结果来修改词图中发射概率的权重吗？

  3.Analysis中，基本的分词模型是用什么语料来训练的，方便告诉一下吗？

                                                              谢谢您啦！

**Comment by ansjsun** [comment]
好吧我写的不科学。。回头修正一下哈
