### ISSUE TITLE
词性标注的问题

### ISSUE THREAD

**Issue by NationalYu** [NLPchina/ansj_seg#179]
对于一词多词性的情况，词性标注的情况单一，没有根据上下文来判断词性：

例如：
    发展/vn, 国有企业/nz
    我们/r, 要/v, 发展/vn, 教育/vn, 事业/n, 。/w
    发展/vn, 体育运动/n, ，/w, 增强/v, 人民/n, 体质/n, 。/w
   全标注成了 vn，我看core.dic中，是这样记录词性的：
      131757	发展	72801	21457	2	{an=0, n=3, v=1568, vn=1644}
   程序中也ToAnalysis也没有看到处理词性的过程，这是否存在问题？

**Comment by ansjsun** [comment]
看demo中的naturedemo

发自我的 iPhone

**Comment by NationalYu** [comment]
demo中附带的标注，也不会修改正确：例如：
     list = ToAnalysis.parse("我们要发展教育事业");
     System.out.println(list);
     new NatureRecognition(list).recognition(); //词性标注
      System.out.println(list);
     结果一样：
[我们/r, 要/v, 发展/vn, 教育/vn, 事业/n]
[我们/r, 要/v, 发展/vn, 教育/vn, 事业/n]

词性标注的过程我看了下，只根据词性的转移矩阵来生成最优词性?

**Comment by ansjsun** [comment]
这个可能只有这种解了..是的知识个隐马词性转移来算的

**Comment by NationalYu** [comment]
> 这个可能只有这种解了..是的知识个隐马词性转移来算的

谢谢啦，因为我水平不太高，就确认下自己理解的对不对，谢谢您啦，关了吧。
