### ISSUE TITLE
ToAnalysis分词过程中，default.dic词典的词频，在计算最优路径的时候用到了吗？

### ISSUE THREAD

**Issue by NationalYu** [NLPchina/ansj_seg#182]
您好
      如题，调试程序的时候，用户自定义词典的默认词典是default.dic
      系统自带的default.dic里的词频，在计算最优路径的时候，把这部分加到节点的频率了吗？
      如果有，麻烦您说下程序里具体地方吧？好像没找到。
                                  谢谢了。

**Comment by ansjsun** [comment]
没有用到default。dic里面的词语
