### ISSUE TITLE
建议library放到resources目录下

### ISSUE THREAD

**Issue by fifar** [NLPchina/ansj_seg#184]
工程下 library 目录存放 ambiguity.dic default.dic 两个配置文件，该目录不是 mvn/sbt 工程的标准目录，打包的时候不会打入 jar 中，执行程序的时候需要1）在特殊的目录下才能运行成功，或者 2）library.properties 中自定义字典路径改成绝对路径。1）和2）方式都有点不方便，尤其是 ansj 跑在分布式环境下，无论相对路径还是绝对路径都有点吃力。个人愚见，自定义字典存放在 resources 目录，随 class 一起打包，以 class.getResourceAsStream 方式读取，而且 ansj 里大部分字典也确实是这种方式读取的。谢谢

**Comment by ansjsun** [comment]
ambiguity.dic default.dic  是用户可编辑的。

放到jar包中无法编辑了。所以不会这么做。。


对于library.propertie加载的问题我也很头疼。

稍后我会尝试一种新的方式来寻找配置文件。也许可以解决问题。。感谢您的意见

**Comment by xiehengye** [comment]
按照您的建议把library放到resources目录下，而且打包也把library打上去了，问什么跑的时候还是自己定义的字典没有起到作用？

**Comment by fifar** [comment]
看看是否在读取的部分没处理好，class.getResourceAsStream 试试

**Comment by ansjsun** [comment]
目前应该是。先寻找项目根目录。就是启动目录。然后寻找classpath里面。。只要放到其中任何一地方逗可以
