### ISSUE TITLE
想将这个项目运行到Android项目中，该如何使用？

### ISSUE THREAD

**Issue by huprince** [NLPchina/ansj_seg#187]

**Comment by GainLee** [comment]
文档有说明吧。目前就只能通过jar包的方式，远吗好像少了个包，我试图联系作者看看

**Comment by ansjsun** [comment]
需要两个jar包 

访问 http://maven.ansj.org/org/ansj/ 最好下载最新版 ansj_seg/
如果你用的是1.x版本需要下载tree_split.jar。
如果你用的是2.x版本需要下载nlp-lang.jar


首页有说明的
