### ISSUE TITLE
如何正确编辑dic字典文件

### ISSUE THREAD

**Issue by xuetf** [NLPchina/ansj_seg#188]
我用txt或者  Ultraedit打开dic文件，然后添加了一些词，然后在测试的时候加载这个词典，但是不能识别我新添加的词。怎么弄都不行。我要怎么解决？ 还有如果我要保存新词到某个词典要怎么操作

**Comment by leiguorui** [comment]
复制一行原来的词，把复制后的修改成自己的新词（因为每行的空格不是space，而是\t）

**Comment by xuetf** [comment]
请问下有没有往词典里插入新词的方法调用？ 还是得自己用java的文件操作来插入？

**Comment by leiguorui** [comment]
我没看到可以调用的方法，应该是自己写java来操作

**Comment by xuetf** [comment]
我写了java来操作，但是原来的词条变成乱码，为什么

**Comment by lubaogui** [comment]
添加新词可以参考 https://github.com/4onni/elasticsearch-analysis-ansj 的redis发布新词, 不过也有一个问题，就是按照他的做法，无法去重，同样的词会被添加很多次，词性的扩展添加需要自己改代码。

**Comment by ansjsun** [comment]
1.@xuetf 乱码问题。可能是机器编码导致。整个项目和词典的编码都是utf-8

2.@lubaogui 不需要去重。词语加多次。内存中只会占用一个词语。。对于词语的动态添加。可以参看我的文档 http://nlpchina.github.io/ansj_seg/


3.@leiguorui 习大大万岁
