### ISSUE TITLE
为什么我不能自己添加词语到自定义词典

### ISSUE THREAD

**Issue by xuetf** [NLPchina/ansj_seg#189]
我新建了txt,然后写了条新词,格式正确，用\t隔开了，然后把编码格式改成utf-8，后缀改成dic,在main中调用的时候没有效果。 但是我要是在原来存在的dic文件末尾添加该条词语，最后执行起来的时候却有效果？为什么？ 其次，我用java的BufferedWriter写词语到已经存在的dic文件，发现原来的词语被破坏了，变成乱码。为什么？

**Comment by ansjsun** [comment]
java基础你得写\n换行吧。。具体原因很难说。。但是这么来看和分词关系不大我先关了啊
