### ISSUE TITLE
Where can I find the lastest version number  when using pom file?

### ISSUE THREAD

**Issue by cloudtrends** [NLPchina/ansj_seg#190]
I know that 1.41 is not the lastest version number , where can I find it?

 <dependency>
            <groupId>org.ansj</groupId>
            <artifactId>ansj_seg</artifactId>
            <version>1.41</version>
</dependency>

**Comment by ansjsun** [comment]
http://maven.ansj.org/org/ansj/ansj_seg/ here only have jar package
