### ISSUE TITLE
关于这个项目的发展的一些疑问

### ISSUE THREAD

**Issue by echofool** [NLPchina/ansj_seg#192]
1、作者有考虑继续维护吗？或是说还有其他人维护吗？最近好像没看见什么更新吧，不知道还有哪些坑没有修复。
2、有木有.net版本的呀。

**Comment by LittleFoolfish** [comment]
还有就是有木有图来介绍一下，我看着这个代码有点绕晕拉

**Comment by ansjsun** [comment]
1.不好意思过去的很长时间我投入到了另一个项目中，所以搁置了，现在我回来了。下一步的计划就是完善扩充这个项目，2.对于没有修复的坑，那不好说了。但是目前都已经发展到2.x版本所以理论上木有致命的bug。3. 没有.net版本。未来也不可能有。但是会提供服务的方式进行调用

**Comment by LittleFoolfish** [comment]
非常感谢解答。我想问一下 有没有图来介绍这个组件的各项之间的关系？
我打算实现.net版本的，主要是自己对这个分词的理论不是很懂，没有系统的概念。想照抄一遍，然后再理解。

**Comment by LittleFoolfish** [comment]
从今天早上起，到现在，已经将代码翻译了大部分了，但都是没有运行测试的，也没有分析各个类之间的关系，还有一部分java和.net的代码不太容易翻译的暂时没翻译出来。作者给点可以资料参考一下吗？也就是类图、你为什么这么设计等等东西拉

**Comment by ansjsun** [comment]
类图基本没有。。因为很多地方不是面向对象的方式来写的。。翻译比较有难度。。如果遇到什么问题可以加我qq详细讨论吧 。。。5144694

**Comment by echofool** [comment]
呵呵，是的，有些类的设计确实不太符合面向对象的原则，相互依赖了。翻译难度还行吧，java和c#很多互通，小部分代码可以直接拷贝都不用修改。
