### ISSUE TITLE
Template.java文件中的一点问题

### ISSUE THREAD

**Issue by lbs4570** [NLPchina/ansj_seg#201]
for (int i = 0; i < lists.size() - 1; i++) {
			temp = lists.get(i);
			String[] split = temp.split(":");

			int index = Integer.parseInt(split[0].substring(1));

			split = split[1].split(" ");
			int[] ints = new int[split.length];

			for (int j = 0; j < ints.length; j++) {
				ints[j] = Integer.parseInt(split[j].substring(split[j].indexOf("[") + 1, split[j].indexOf(",")));
			}
			t.ft[index] = ints;
		}

这段代码是不是没有处理类似于U05:%x[-1,0]/%x[1,0] 这样的情况
是不是应该添加一句split = split[0].split("/");

**Comment by ansjsun** [comment]
应该是吧。如果有报错那肯定是了。。
