### ISSUE TITLE
Maven Compile Error

### ISSUE THREAD

**Issue by qingyuanxingsi** [NLPchina/ansj_seg#202]
According to your instructions,I failed to compile the ansj_seg code and get the following error message：
<pre>
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[58,28] 找不到符号
符号： 方法 getName()
位置： 类 org.nlpcn.commons.lang.dat.Item
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[62,12] 找不到符号
符号： 方法 getStatus()
位置： 类 org.nlpcn.commons.lang.dat.Item
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[63,29] 找不到符号
符号： 方法 getName()
位置： 类 org.nlpcn.commons.lang.dat.Item
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[64,20] 找不到符号
符号： 方法 getName()
位置： 类 org.nlpcn.commons.lang.dat.Item
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[64,48] 找不到符号
符号： 方法 getName()
位置： 类 org.nlpcn.commons.lang.dat.Item
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[67,12] 找不到符号
符号： 方法 getStatus()
位置： 类 org.nlpcn.commons.lang.dat.Item
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[68,9] 找不到符号
符号： 方法 setName(<nulltype>)
位置： 类 org.nlpcn.commons.lang.dat.Item
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[106,12] 找不到符号
符号： 方法 setBase(char)
位置： 类 org.ansj.domain.AnsjItem
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[107,12] 找不到符号
符号： 方法 setCheck(int)
位置： 类 org.ansj.domain.AnsjItem
[ERROR] /home/apple/tools/open_source_tools/ansj_seg/src/main/java/org/ansj/library/DATDictionary.java:[108,12] 找不到符号
符号： 方法 setStatus(byte)
位置： 类 org.ansj.domain.AnsjItem
</pre>
Is there any solution available?Looking forward to your reply!

**Comment by ansjsun** [comment]
需要导入nlp-lang包才能编译通过。。建议skip-test

**Comment by cenwei** [comment]
请教ansjsun，我已经在pom.xml 文件导入
		<dependency>
            <groupId>org.ansj</groupId>
            <artifactId>ansj_seg</artifactId>
            
            <version>2.0.8</version>
        </dependency>
		<dependency>
			 <groupId>org.ansj</groupId>
            <artifactId>tree_split</artifactId>
			<version>1.4</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.nlpcn</groupId>
			<artifactId>nlp-lang</artifactId>
			<version>1.0</version>
			<scope>compile</scope>
		</dependency>
反编译看了一下，发现这个Item对象没有对应的方法：getName() getStatus() getIndex()  等方法。0.3版本也没有，劳请指正！谢谢。

**Comment by ansjsun** [comment]
不应该吧。你是clone的master吗？？不要clone dev分支

**Comment by cenwei** [comment]
![image](https://cloud.githubusercontent.com/assets/6905251/9188667/379aee02-4011-11e5-87cd-d1fdc2941cb1.png)
![image](https://cloud.githubusercontent.com/assets/6905251/9188673/49ca563a-4011-11e5-887b-caef96db89c4.png)
请教ansjsun 是不是因为这个原因，我在用mvn编译的时候，找不到nlp-lang1.0.2这个包，换了1.0的版本才下载成功。

**Comment by ansjsun** [comment]
你看看pom。xml中的 nlp-lang版本来确定需要哪个不好意思啊

**Comment by cenwei** [comment]
感谢@ansjsun，1.0.2的nlp-lang 已经能够获取，正常编译通过。感谢ansjsun的辛勤劳动！
