### ISSUE TITLE
半角标点符号词性为null

### ISSUE THREAD

**Issue by doubler** [NLPchina/ansj_seg#204]
使用全角没问题。句子“找到了，不好意思”分词结果为“找到[v] 了[ul]  ，[w]   不好意思[a]”
半角句子“找到了,不好意思”分词结果为“找到[v] 了[ul]  ,[null]   不好意思[a]”

其它半角标点符号，如:/,[?!~:`#-等，词性也都是null。

**Comment by ansjsun** [comment]
不好意思。之前训练文本都比较标准。。所以对于半角标点。。并无给以词性。。可能会在下一版本中修复。。暂时办法。。建议您高一个map自己来映射吧

**Comment by doubler** [comment]
好的，谢谢说明。

**Comment by ansjsun** [comment]
之后我回想办法修复这个bug 感谢你的提醒
