### ISSUE TITLE
求最新版本

### ISSUE THREAD

**Issue by waiteryee127** [NLPchina/ansj_seg#206]
你好，用目前这个版本的分词效果和http://www.nlpcn.org/demo中的分词效果差距比较大，请问一下，http://www.nlpcn.org/demo的分词用的不是这个分支的代码吗，或者哪里可以获取http://www.nlpcn.org/demo所有的分词代码。

**Comment by ansjsun** [comment]
一样的。。你需要加载用户自定义词典即可

**Comment by ansjsun** [comment]
最新版本

http://maven.nlpcn.org 自己下载吧
