### ISSUE TITLE
可以让用户自定义词库优先么

### ISSUE THREAD

**Issue by TopSpoofer** [NLPchina/ansj_seg#207]
您好，可以让用户自定义词库优先么？现在需要根据自定义的词库进行切词，都是一些电商的词。

**Comment by w64852908** [comment]
作者原话：
ansjsun commented 3 days ago
不好意思这个真的是这样的。。用户自定义词典不是最优的。。后期版本打算让用户自定义词典优先

**Comment by w64852908** [comment]
作者原话：
ansjsun commented 3 days ago
不好意思这个真的是这样的。。用户自定义词典不是最优的。。后期版本打算让用户自定义词典优先

**Comment by w64852908** [comment]
作者原话：
ansjsun commented 3 days ago
不好意思这个真的是这样的。。用户自定义词典不是最优的。。后期版本打算让用户自定义词典优先

**Comment by w64852908** [comment]
作者原话：
不好意思这个真的是这样的。。用户自定义词典不是最优的。。后期版本打算让用户自定义词典优先

**Comment by dglAndlele** [comment]
谢谢。可以让用户自己设定是不是用户字典最优，这应该是个不错的注意。

**Comment by huoxiaoduo** [comment]
您好，能设置用户字典最优挺需要的。
比如新增产品包含人名或者日期、时间等，现在还不能有效识别。

**Comment by ansjsun** [comment]
fix by #205
