### ISSUE TITLE
关于分词一个bug

### ISSUE THREAD

**Issue by pandaHP** [NLPchina/ansj_seg#209]
若在用户词典中加入“无人品” 一词，切割 “我无人品” ，结果为：
r	我	1802
b	无人	2874
v	品	8
但是分割“你无人品”，结果却为：
r	你	571
neg-common	无人品	1

就是如果是“我”字开头后面就对用户自己加的词无用了，这是为什么？

**Comment by ansjsun** [comment]
只能识别就是这样 具有随意性
