### ISSUE TITLE
关于模型方法的介绍

### ISSUE THREAD

**Issue by wly0229** [NLPchina/ansj_seg#213]
Hi,
你好，我觉得ansj_seg一直是不错的分词工具。想了解具体的方法，有没有参阅的链接或者论文。我只知道起初是根据张华平老师的分词工具写的，不清楚有什么改进。所以在此求方法介绍，以让自己更清楚的理解ansj_seg的框架和方法。

Bests,
Vincent

**Comment by ansjsun** [comment]
您好请看[wiki](https://github.com/NLPchina/ansj_seg/wiki)
