### ISSUE TITLE
userLibrary加入的词 还会在新词发现中出现

### ISSUE THREAD

**Issue by huoxiaoduo** [NLPchina/ansj_seg#217]
比如 userLibrary 已经增加了张艺谋的词
但 http://nlpchina.github.io/ansj_seg/content.html?name=%E6%96%B0%E8%AF%8D%E5%8F%91%E7%8E%B0%E5%B0%8F%E5%B7%A5%E5%85%B7
还是会出现

**Comment by ansjsun** [comment]
应该是在做识别的时候.没有考虑这个问题 ....因为 ..张艺谋可能先走的人名识别..所以导致机用户自定义词典木有先发现..这么做不算过分吧?

**Comment by shibing624** [comment]
nlpAnalysis 是人名识别优先的，之后走用户自定义词典。最新的可以用DicAnalysis处理得到你要的结果。
