### ISSUE TITLE
怎么删除默认词典

### ISSUE THREAD

**Issue by jilezhou** [NLPchina/ansj_seg#218]
本来想提“用户自定义词典如何优先”，但是发现这个问题之前有人提过了，但是貌似作者暂时木有时间提供这个功能，所以想问一下，如何删除默认词典，因为我只关心用户自定义词典的分词结果。谢谢：）

**Comment by ansjsun** [comment]
那就不要用seg 用forest 就可以额

**Comment by HavenLiu** [comment]
"那就不要用seg 用forest 就可以额"
小白，没看懂这句话，能具体点么？
