### ISSUE TITLE
自定义词识别不出来

### ISSUE THREAD

**Issue by huoxiaoduo** [NLPchina/ansj_seg#222]
比如 “接着上一张宾得Q10拍的图，上面的图片都是这个奥林巴斯XZ-1拍的”
我自定义了 宾得Q10  和 奥林巴斯XZ-1   都没生效

**Comment by ansjsun** [comment]
不好意思。这是我的一个失误。因为在正文解析前，分词器默认把正文转为小写导致，所以解决办法是

所有用户自定义词典中的词语必须小写。


比如  宾得Q10  需要改为  宾得q10

当然分词后你可以通过term.getrealname() 来获得文本中的真实词语，这样做的好处是你可以不区分大小写来拼凑词典了

**Comment by huoxiaoduo** [comment]
这个问题我自己转小写就可以了  

可以让用户自定义词库优先么？类似词性优先似的

**Comment by ansjsun** [comment]
fix it on 32 #205

**Comment by ansjsun** [comment]
没有问题我就关了啊 !
