### ISSUE TITLE
ToAnalysis.parse执行过慢

### ISSUE THREAD

**Issue by jt120** [NLPchina/ansj_seg#223]
是否是第一次执行, 会把所有词库load到内存中, 所以导致比较慢了?

maven项目, 然后引入jar包, 因为从仓库下载不下来.

dump了下线程
"main" prio=6 tid=0x000000000284f000 nid=0xdb8 runnable [0x000000000294c000]
   java.lang.Thread.State: RUNNABLE
	at java.io.WinNTFileSystem.list(Native Method)
	at java.io.File.list(File.java:1116)
	at java.io.File.listFiles(File.java:1201)
	at org.nlpcn.commons.lang.util.FileFinder.findByFile(FileFinder.java:74)
	at org.nlpcn.commons.lang.util.FileFinder.findByFile(FileFinder.java:77)
	at org.nlpcn.commons.lang.util.FileFinder.findByFile(FileFinder.java:77)
	at org.nlpcn.commons.lang.util.FileFinder.find(FileFinder.java:48)
	at org.ansj.util.MyStaticValue.<clinit>(MyStaticValue.java:77)
	at org.ansj.library.UserDefineLibrary.initUserLibrary(UserDefineLibrary.java:91)
	at org.ansj.library.UserDefineLibrary.<clinit>(UserDefineLibrary.java:37)
	at org.ansj.splitWord.Analysis.<init>(Analysis.java:44)
	at org.ansj.splitWord.analysis.ToAnalysis.<init>(ToAnalysis.java:78)

C:\tools\Java\jdk1.7.0_71\bin\java -ea -Didea.launcher.port=7541 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 13.1.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA 13.1.3\lib\idea_rt.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 13.1.3\plugins\junit\lib\junit-rt.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\charsets.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\deploy.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\javaws.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\jce.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\jfr.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\jfxrt.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\jsse.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\management-agent.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\plugin.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\resources.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\rt.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\ext\access-bridge-64.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\ext\dnsns.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\ext\jaccess.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\ext\localedata.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\ext\sunec.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\ext\sunjce_provider.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\ext\sunmscapi.jar;C:\tools\Java\jdk1.7.0_71\jre\lib\ext\zipfs.jar;D:\project\tools\book-move\target\test-classes;D:\develop\nlp\ansj_seg-3.0-all-in-one.jar;D:\develop\repo\org\apache\lucene\lucene-analyzers\3.5.0\lucene-analyzers-3.5.0.jar;D:\develop\repo\org\apache\lucene\lucene-core\3.5.0\lucene-core-3.5.0.jar;D:\develop\repo\commons-io\commons-io\2.4\commons-io-2.4.jar;D:\develop\repo\junit\junit\4.12\junit-4.12.jar;D:\develop\repo\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.jt.tools.book.BookTest,test03
一月 08, 2016 6:48:28 下午 org.ansj.util.MyStaticValue <clinit>
警告: not find library.properties in classpath use it by default !
一月 08, 2016 6:48:28 下午 org.ansj.library.UserDefineLibrary loadLibrary
警告: init userLibrary  warning :D:\project\tools\book-move\library\default.dic because : file not found or failed to read !
一月 08, 2016 6:48:28 下午 org.ansj.library.UserDefineLibrary initAmbiguityLibrary
警告: init ambiguity  warning :D:\project\tools\book-move\library\ambiguity.dic because : file not found or failed to read !
一月 08, 2016 6:48:29 下午 org.ansj.library.DATDictionary loadDAT
信息: init core library ok use time :877
[learning/en,  /nr, ros/en,  /nr, for/en,  /nr, robotics/en,  /nr, programming/en,  /nr, -,  /nr, second/en,  /nr, edition/en, ./m, pdf/en]
一月 08, 2016 6:48:30 下午 org.ansj.library.NgramLibrary <clinit>
信息: init ngram ok use time :479

**Comment by ansjsun** [comment]
1.maven 无法下载可能是需要设置
····
       
    <repositories>
        <repository>
            <id>mvn-repo</id>
            <url>http://maven.nlpcn.org/</url>
        </repository>
    </repositories>
····


2.第一次运行慢是需要加载词典之后就快了

**Comment by jt120** [comment]
把项目clone到本地install了下解决了, 可以装个插件, 那样源码也会一起发布, 挺方便的
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <attach>true</attach>
                    </configuration>
            </plugin>

**Comment by ansjsun** [comment]
感谢你的意见..就这么干...
