### ISSUE TITLE
找不到 ambiguity.dic 产生警告

### ISSUE THREAD

**Issue by TopSpoofer** [NLPchina/ansj_seg#225]
init ambiguity  warning :/home/lele/mycode/scalacode/dcp_2.0/library/ambiguity.dic because : file not found or failed to read

[error] 一月 12, 2016 3:22:44 下午 org.ansj.library.UserDefineLibrary loadFile
[error] 信息: init user userLibrary ok path is : /home/lele/mycode/scalacode/dcp_2.0/DynConfig/user_dictionary.dic
[error] 一月 12, 2016 3:22:44 下午 org.ansj.library.UserDefineLibrary initAmbiguityLibrary
[error] 警告: init ambiguity  warning :/home/lele/mycode/scalacode/dcp_2.0/library/ambiguity.dic because : file not found or failed to read !
[error] 一月 12, 2016 3:22:44 下午 org.ansj.library.UserDefineLibrary loadFile
[error] 信息: init user userLibrary ok path is : /home/lele/mycode/scalacode/dcp_2.0/DynConfig/user_dictionary.dic
[error] 一月 12, 2016 3:22:45 下午 org.ansj.library.DATDictionary loadDAT
[error] 信息: init core library ok use time :642
[error] 一月 12, 2016 3:22:45 下午 org.ansj.library.NgramLibrary <clinit>
[error] 信息: init ngram ok use time :352

可以分词，但为何出现error的信息？

**Comment by ansjsun** [comment]
应该是waring 没关系的..我用的jdk自带的log导致的吧 ...放心用吧

**Comment by dglAndlele** [comment]
thk

**Comment by dglAndlele** [comment]
thk
