### ISSUE TITLE
Git中的AutoCRLF与SafeCRLF换行符问题

### ISSUE THREAD

**Issue by jimichan** [NLPchina/ansj_seg#227]
ansj：
我发现项目代码中由于开发环境不一样，导致crlf问题。
mac中换行符是\n ，window下 是 \r\n    所以导致了多人开发环境下代码即使修改了一行都不能自动git合并。
所以大家同一在git中进行配置，同一使用\n换行符，可以避免大量冲突。
建议在git中使用：

#提交时转换为LF，检出时不转换
git config --global core.autocrlf input 

在README文档中需要进行说明。

参考 http://www.cnblogs.com/flying_bat/archive/2013/09/16/3324769.html

**Comment by ansjsun** [comment]
@jimichan  感谢你的提示已经添加.
