### ISSUE TITLE
ansi_seg如何实现地名识别

### ISSUE THREAD

**Issue by harryyu1018** [NLPchina/ansj_seg#230]
您好~ 我准备基于ansj_seg开发一个可以识别地名所属地理类别的功能（比如: 省，市，区县，道路，等等）~ 所以我想请问一下ansj_seg是如何识别地名的，请问具体学习的方法，资料还有代码有哪些？谢谢

我刚开始使用ansj_seg所以还不是很熟悉其内部结构~

**Comment by ansjsun** [comment]
就是CRF
