### ISSUE TITLE
crf模型下载下来怎么用？

### ISSUE THREAD

**Issue by jerry-sjtu** [NLPchina/ansj_seg#232]
crf模型和代码是分开的，下载后怎么使用？能给个代码说明么？

**Comment by ansjsun** [comment]
不知道你通过什么方式下载的...建议你使用

DownLibrary.main(null)

下载..下载完毕后

调用 NlpAnalysis 

启动会提示你加载crfmodel  同时会打印模型路径.检查下路径是否正确就可以了
