### ISSUE TITLE
加载用户词典慢的问题

### ISSUE THREAD

**Issue by chaos-dd** [NLPchina/ansj_seg#233]
现在加载用户词典是通过在当前目录循环查找文件，如果当前目录文件多的话会非常慢！这个能不能修改一下。改成允许用户配置路径和在classpath下寻找岂不是更好吗

**Comment by ansjsun** [comment]
你好这个问题在我映像里面是#e19be358d57a8e0d8975b86fbf3e76b60c1f72ec 修复过..

**Comment by chaos-dd** [comment]
额 这个patch貌似没包含在3.1的tag里

**Comment by ansjsun** [comment]
你下载3.5试试..之前有个版本的确有这个问题.尤其在windows下..

**Comment by ansjsun** [comment]
历史终将不了了之
