### ISSUE TITLE
java.lang.StackOverflowError 是为什么

### ISSUE THREAD

**Issue by skycathy1314** [NLPchina/ansj_seg#234]
下载了ansj_seg-3.5-all-in-one.jar
只是跑了最基本的测试代码
 List<Term> parse1 = BaseAnalysis.parse("让战士们过一个欢乐祥和的新春佳节。");
System.out.println(parse1);
就老师报错说stack溢出，是为什么

**Comment by ansjsun** [comment]
不应该呀..你机器的内存是多少?

**Comment by skycathy1314** [comment]
机器吗，4G

**Comment by ansjsun** [comment]
我刚试了的确没有问题..你是否下载了词典和你的jar包以及完整代码粘贴上来吧

**Comment by skycathy1314** [comment]
我就添加了ansj_seg-3.5-all-in-one.jar 这个包，然后只是准备跑示例代码看一眼而已。。。没下词典，也没干什么别的

package com.company;
import org.ansj.domain.Term;
import org.ansj.splitWord.analysis.BaseAnalysis;
import org.ansj.splitWord.analysis.ToAnalysis;


import java.util.List;

public class Main {

    public static void main(String[] args) {

        List<Term> parse1 = BaseAnalysis.parse("让战士们过一个欢乐祥和的新春佳节。");
        System.out.println(parse1);
    }
}

**Comment by ansjsun** [comment]
我和你一样我就不报错...

你试试 

vm arguments:
 -XX:MaxDirectMemorySize=128m

**Comment by ansjsun** [comment]
不行的话加我q

**Comment by skycathy1314** [comment]
![image](https://cloud.githubusercontent.com/assets/10240715/12808497/3efece76-cb52-11e5-9689-23ec6429001b.png)
然后依然不行

**Comment by ansjsun** [comment]
你这个是eclipse的配置吧???不是运行的java环境的配置

**Comment by skycathy1314** [comment]
哎？改的不是这个嘛？

**Comment by ansjsun** [comment]
一般我不会报这个错的..我感觉是你环境的问题..你直接跑helloword不报错吗?

**Comment by skycathy1314** [comment]
不哎，我试过直接println，是可以的…

**Comment by ansjsun** [comment]
换个电脑试试吧 :( 没办法了..我这里真的无法发生

**Comment by skycathy1314** [comment]
对，我打算换电脑试试

**Comment by yuanjianfaith** [comment]
我这里也出现这个问题，8G内存机器。

**Comment by ansjsun** [comment]
@yuanjianfaith 调整内存大小...8g应该不可能溢出的...我服了

**Comment by yuanjianfaith** [comment]
我已经放弃了，直接下来源码来做试验了，ok没问题。

**Comment by chihchiehshao** [comment]
參考這篇試試 是否-Xss問題

http://stackoverflow.com/questions/14763079/what-are-the-xms-and-xmx-parameters-when-starting-jvms

**Comment by ansjsun** [comment]
历史终将不了了之
