### ISSUE TITLE
3.5+版本为什么发现不了新词

### ISSUE THREAD

**Issue by zhangmianhongni** [NLPchina/ansj_seg#235]
`valInfo="洁面仪配合洁面深层清洁毛孔 清洁鼻孔面膜碎觉使劲挤才能出一点点皱纹 脸颊毛孔修复的看不见啦 草莓鼻历史遗留问题没辙 脸和脖子差不多颜色的皮肤才是健康的 长期使用安全健康的比同龄人显小五到十岁 28岁的妹子看看你们的鱼尾纹";
LearnTool learnTool = new LearnTool();
List<Term> list = NlpAnalysis.parse(valInfo, learnTool);
WordSegmentResult wsr = new WordSegmentResult();
wsr.setTermList(list);
wsr.setNewWords(learnTool.getTopTree(0));`
为什么我使用3.5+的版本，learnTool里面发现不了新词，count一直为0，但是以前2.08的就版本能发现几个新词。

**Comment by ansjsun** [comment]
因为没有加载模型.3.x版本之后模型不随jar包下载了

DownLibrary.main(null)

下载..下载完毕后

调用 NlpAnalysis

启动会提示你加载crfmodel 同时会打印模型路径.检查下路径是否正确就可以了

**Comment by ansjsun** [comment]
历史终将不了了之
