### ISSUE TITLE
版本更新后，分词有点小问题

### ISSUE THREAD

**Issue by rtghbnm** [NLPchina/ansj_seg#236]
兖州煤业(01171)被控违约诉讼获胜诉 这个句子
我加了纠正词典ambiguity.dic   “兖州煤业    兖州煤业    nu” 
 调用这个方法 NlpAnalysis.parse("兖州煤业(01171)被控违约诉讼获胜诉") 
分出来 “兖州煤业(” 为nw 新词 
正常是分出来 兖州煤业 nu 这种形式
有些加了用户词典的词后面跟（）的 通过NlpAnalysis都会分词词（ 为nw
是不是crf。model训练模型不充分的原因呢
帮忙看看谢谢~

**Comment by ansjsun** [comment]
你说对了是crf训练时候语聊不干净造成的问题.应该在不久的将来重新训练一个模型来解决这种问题

**Comment by hirocc** [comment]
可以利用自己的语料库来定制训练这个模型吗？

**Comment by ansjsun** [comment]
不就得将来....可以..

**Comment by ansjsun** [comment]
历史终将不了了之
