### ISSUE TITLE
UserDefineAnalysisTest 自订词优先最简单的 test case 都跑不过

### ISSUE THREAD

**Issue by HerbJiang** [NLPchina/ansj_seg#237]
这个版本直接跑 UserDefinedAnalysisTest 会发现第一个 Assert 就失败了
看 List<Term> parse = UserDefineAnalysis.parse(str) 结果没有“爸爸去哪儿”
没人遇到这个问题吗？

**Comment by ansjsun** [comment]
sorry 这的确是我的一个错误.严重的错误.

修改了nlp-lang 包中的一个东西导致的

已经修复 在 96778e9  .未来发布jar包会在3.8中看到

**Comment by HerbJiang** [comment]
可否再问一个问题，目前提供自定义的 nature 不会优先呈现，例如下列代码

		Forest myForest = new Forest();
		Library.insertWord(myForest, new Value("如下", "#MyNature", "1000"));
		System.out.println(UserDefineAnalysis.parse("上海电力2012年财务报表如下怎爸爸去哪儿么办", myForest));

结果“如下”这个词的 nature 仍然是 vi

**Comment by HerbJiang** [comment]
找到原因
UserDefineAnalysis line 77
FilterModifWord.modifResult(result); 
改成
FilterModifWord.modifResult(result, forests);

**Comment by ansjsun** [comment]
ok in jar 3.7.1 thanks @HerbJiang

**Comment by HerbJiang** [comment]
再回报一个状况

		Library.insertWord(UserDefineLibrary.FOREST, new Value("北京卡", "#UserDefined", "1000"));
		System.out.println(UserDefineAnalysis.parse("北京卡机场服务"));

结果无法提供"北京卡"

**Comment by ansjsun** [comment]
hi @HerbJiang  感谢你提交的bug

路径如下.
````
北	0.0 ,北京/ns	0.0 ,北京卡/UserDefined	0.0 ,
京	0.0 ,
卡	0.0 ,卡机/nz	0.0 ,
机	0.0 ,机场/nis	0.0 ,
场	0.0 ,
服	0.0 ,服务/vn	0.0 ,
````

你看到了因为  北京卡 ..卡机 机场 出现了冲突.所以程序寻找最优路径.因为寻找最优路径 所以

 北京+卡+机场>北京卡+机场

这个策略的的确是有问题.我会仔细考虑

目前在程序中通过二次用户自定义词表扫描应该可以不完美解决

**Comment by ansjsun** [comment]
历史终将不了了之
