### ISSUE TITLE
3.6版本使用自定义词库优先分词，出现了奇怪的现象。

### ISSUE THREAD

**Issue by zhangmianhongni** [NLPchina/ansj_seg#238]
3.6版本使用自定义词库优先分词，出现了奇怪的现象。
首先我增加了一个自定义词条，写了一个调用 用户词库优先分词 的方法
现象如下：
情况1：然后放到spricg MVC的controller里面调用，启动tomcat，页面上面去点击调用这个controller的方法。
情况2：直接在eclipse里面右键一个测试文件，Run。

2个情况调用的方法完全一样，直接copy，但是得到的分词结果却不一样，情况1的分词结果是正常的，但是情况2的分词结果却没有按照我定义的那个词条分词，我的自定义词条并没有出现在分词结果。

**Comment by ansjsun** [comment]
1.下载最新的3.7.1版本
2.注意两次启动.读取的词典路径是否有区别.会有log显示的

**Comment by zhangmianhongni** [comment]
从3.6版本更新到3.7.1版本后 出现了FilterStopWord.updateDic can not be null , you must use set FilterStopWord.setUpdateDic(map) or use method set map 错误，但是程序能正常运行，什么回事

**Comment by ansjsun** [comment]
把你的代码粘贴上来吧..这个问题在我这里无法重现.可能性比较多...

**Comment by ansjsun** [comment]
历史终将不了了之
