### ISSUE TITLE
可否根据词性和字对词自定义？

### ISSUE THREAD

**Issue by kylinzlkz** [NLPchina/ansj_seg#239]
如“2015年6月3日，在上海”在NlpAnalysis里分词结果会是
[2015年/nw, 6月/nw, 3日/nw ...]
我想在userDefine.dic中自定义：
/m年 /year
/m月 /month
这样可以么？？

**Comment by ansjsun** [comment]
用户自定义吃点不支持类似这正则的方式.建议后期对分词结果进行二次判断.

还有标注为nw可能是我的分词bug.额.一定是bug我会尽快修改

**Comment by logozy** [comment]
我在测试NLPAnalysis的时候 也有很多的nw情况（包括默认词典里存在的词）。不知道怎么解决？？这个是词性标注的bug吗？

**Comment by ansjsun** [comment]
的确是一个bug因为在数字识别 之前nlp识别出来了数字.导致.无法合并..后期打算制作一个分类工具来对词语的词性进行分类

**Comment by logozy** [comment]
你是指，在词性标注结果之后的分类处理吗？  学习代码中，没有看明白人名识别这块是怎么做的？ 有没有相关资料呢？  万分感谢  (* ￣3)(ε￣ *)

**Comment by kylinzlkz** [comment]
那写下新的问题吧~~ 就是在userDefine.dic中我加了些自定义的词.. 如：bilibili  1000  wangzhan，我定义了很多个，用Library.makeForest载入后分析总会报错。 但如果我把我自己定义的这些词复制到default.dic中，且不载入userDefine.dic时就不会报错。
报错的点是：Graph.java 中Merge方法中if (terms[to] != null) ，此处terms[to]会超出terms的上限，取不到会报java.lang.ArrayIndexOutOfBoundsException: 297
请问是我自定义的词语有问题还是什么原因呢？？（不好意思有点长... 怕说不清...）

**Comment by ansjsun** [comment]
1.自定义词典这个问题一般都是编码问题..   任何时候.不要用windows记事本编辑词典..切记

bilibili 1000 wangzhan  中间的分割符是tab 就是\t 千万不要用空格.


 至于后一个问题.可能是因为第一个问题引起的把...你试试

**Comment by kylinzlkz** [comment]
我用的nodepad++ ，编码用的UTF-8这样~~ 
还会出现 userDefine.dic里面定义：报警人  1000   shouhaizhe，然后分词的结果却会多带一个字，如：报警人报/shouhaizhe

**Comment by lixinliang373** [comment]
我发现词性这个版本的词性标注问题较大，对于上面说的时间词会识别成nw，还有一些机构名也会识别成nw，不知道在目前的这个版本下这种情况下应该如何解决才好？

**Comment by ansjsun** [comment]
@kylinzlkz  中间的分隔符是tab吗?

**Comment by ansjsun** [comment]
@lixinliang373  的确是有这个问题..

的确是一个bug因为在数字识别 之前nlp识别出来了数字.导致.无法合并..后期打算制作一个分类工具来对词语的词性进行分类


会在未来的版本中修复..具体是否下一个版本不好说额我争取哈

**Comment by kylinzlkz** [comment]
对的~ 是tab  由于不知道该怎么解决... 于是我把他们都复制到了default.dic中... 就解决了.. _(:з」∠)_

**Comment by ansjsun** [comment]
历史终将不了了之
