### ISSUE TITLE
不知是不是bug, 但如何获取的词性?

### ISSUE THREAD

**Issue by zoln** [NLPchina/ansj_seg#241]
`UserDefineLibrary.insertWord("大豆", "userDefine", 1000);
        UserDefineLibrary.insertWord("豆油", "userDefine", 1000);
        List<Term> parse = ToAnalysis.parse("金龙鱼大豆油");
        System.out.println(parse);`
给出结果 [金龙/nz, 鱼/n, 大豆油/nmc]

这个大豆油的词性对吗? 我期望的结果是分出大豆,豆油

**Comment by ansjsun** [comment]
我觉得你应该用 IndexAnalysis.parse("金龙鱼大豆油"))

**Comment by ansjsun** [comment]
历史终将不了了之
