### ISSUE TITLE
打包war文件  分词出问题

### ISSUE THREAD

**Issue by wangBIT** [NLPchina/ansj_seg#242]
您好，程序本地跑得好好的，上传服务器打包成war包，然后在分词那就卡主了，好像没有运行出结果来，具体也不知道啥问题。能帮忙看下吗？

parse = UserDefineAnalysis.parse(s); 
//接下来的都无法运行了 
System.out.println("分词结果： "+parse);

**Comment by ansjsun** [comment]
应该是内存给的不够 

发自我的 iPhone

**Comment by wangBIT** [comment]
额好像是因为加载用户自定义词典时候路径的问题。。。  另外问一下，需要多大内存额？

**Comment by wangBIT** [comment]
额好像是因为加载用户自定义词典时候路径的问题。。。 另外问一下，需要多大内存额？ @ansjsun

**Comment by ansjsun** [comment]
路径不对..会在打印路径的时候出现..理论上不会卡主吧..内存起码给1g吧...如果是tomcat 默认128m肯定是不够的

**Comment by wangBIT** [comment]
额 路径啥的解决了，对比发现加载的词典也正确，确实分词的时候没能通。 用的linux服务器是：
             total       used       free     shared    buffers     cached
Mem:        501780     475504      26276        348       172

512M的，不够用啊。。

**Comment by ansjsun** [comment]
应该是够的。。不过看你用户自定义词典大小吧。。大点保险么

**Comment by wangBIT** [comment]
原先在本地的eclipse下可以正常运行的。换了个8G的内存，结果tomcat还是报错了，在Windows服务器下报错如下：
java.lang.ArrayStoreException: org.nlpcn.commons.lang.tire.domain.Forest
        at org.ansj.recognition.UserDefineRecognition.<init>(UserDefineRecogniti
on.java:21)
        at org.ansj.splitWord.analysis.ToAnalysis$1.userDefineRecognition(ToAnal
ysis.java:58)
        at org.ansj.splitWord.analysis.ToAnalysis$1.merger(ToAnalysis.java:52)
        at org.ansj.splitWord.analysis.ToAnalysis.getResult(ToAnalysis.java:76)
        at org.ansj.splitWord.Analysis.analysisStr(Analysis.java:127)
        at org.ansj.splitWord.Analysis.parseStr(Analysis.java:219)
        at org.ansj.splitWord.analysis.ToAnalysis.parse(ToAnalysis.java:100)

**Comment by ansjsun** [comment]
试试ToAnalysis

发自我的 iPhone

**Comment by wangBIT** [comment]
ToAnalysis和UserDefineAnalysis  两个都出同样的问题~ @ansjsun

**Comment by ansjsun** [comment]
是3.7.1的jar包吗？


发自我的 iPhone

**Comment by wangBIT** [comment]
用3.7.1的jar包试过，也用当时2.0版本的也试过。都出了问题 @ansjsun

**Comment by ansjsun** [comment]
看错误是你往用户自定义词典中加入错误的类型 是否程序添加词到词典中了？如果有先去掉 试试

发自我的 iPhone

**Comment by wangBIT** [comment]
晚上又试了一下，把之前的工程删除，重新新建了一个，手动粘贴之前的代码，再从github上重新下载了2.0版本的ansj，再次上传到服务器，终于成功了。。。。

暂时还没有尝试用3.7.1的jar进行尝试，不确定是不是新版本的问题。而且还有一个问题是，在之前的项目中，即使是删除了3.7.1的jar，改用2.0的版本，也还是不行的，难道是有什么缓存或者记忆问题吗？总之就是换了新工程，新导入新的2.0jar包，就正常了、。。  感谢 @ansjsun 的解答~

**Comment by ansjsun** [comment]
一般这种灵异现象都和人品有关 不知道jdk 反正我没记额

发自我的 iPhone

**Comment by wangBIT** [comment]
哈哈~  

等有时间我再试试单独用3.7.1jar行不行、、、、

我也下了个github的客户端，还挺方便

**Comment by ansjsun** [comment]
历史终将不了了之
