### ISSUE TITLE
人工标注的语料库的相关问题

### ISSUE THREAD

**Issue by kylinzlkz** [NLPchina/ansj_seg#243]
我看到有文章介绍说你用10年的人民日报的资料训练语料库什么的，我想问一下详细的过程是什么？？结果是形成一个和人民日报内容相符的语料库？？那应该怎么使用？ 是用LearnToolDemo么？？这个一直不太明白这个算法里面reload训练结果是什么？？可以解释一下么？？麻烦了...

**Comment by ansjsun** [comment]
无法形成 。。

**Comment by zpzkit** [comment]
差不多的问题，我想自己拿语料来训练模型得到可以利用的分词工具，你的工具怎么来训练？谢谢

**Comment by ansjsun** [comment]
历史终将不了了之
