### ISSUE TITLE
Term中score和selfscore是什么？怎么计算出来的？

### ISSUE THREAD

**Issue by kylinzlkz** [NLPchina/ansj_seg#244]
现在着重在看NLP这部分，可是里面很多地方没有注释，来咨询一下：
1）walkPath()中的relationMap是什么？？我Debug一直是null，好像没什么用的样子
2）Term结构体中有一个score和selfscore是什么？感觉和最后统计出的newword的freq有关？？那我是否可以自己给这个score赋值？？

**Comment by ansjsun** [comment]
ngram 中庸的。。。selfscore是本身分数。。score是vterbi 中记录路径的分数。

最好不要修改分数。。。newword  freq好像是依赖这个我也给忘记了

**Comment by ansjsun** [comment]
历史终将不了了之
