### ISSUE TITLE
3.7.1版本使用UserDefineAnalysis分词报出警告

### ISSUE THREAD

**Issue by woloqun** [NLPchina/ansj_seg#245]
error：FilterStopWord.updateDic can not be null , you must use set FilterStopWord.setUpdateDic(map) or use method set map

使用ToAnalysis，则没有这个问题

**Comment by ansjsun** [comment]
感谢你的bug反馈。是有问题。会在下一个release版本中修复

**Comment by aashenge** [comment]
这个问题我也发现了，后来看代码已经改过了，但是没有release

**Comment by ansjsun** [comment]
历史终将不了了之
