### ISSUE TITLE
歧异词典跟用户自订词典的冲突

### ISSUE THREAD

**Issue by HerbJiang** [NLPchina/ansj_seg#246]
简单来说，原歧异词典已经包含 “李民工作    李民  nr  工作  vn”
因此“李民工作了一天”结果是 “李民 / 工作 / 了 / 一天”

当加入
Library.insertWord(UserDefineLibrary.FOREST, new Value("李民工", "#UserDefined", "1000"));
的分词结果仍是 “李民 / 工作 / 了 / 一天” 

但若是
Library.insertWord(UserDefineLibrary.FOREST, new Value("李民工作了", "#UserDefined", "1000"));
的分词结果却是 “李民工作了 / 一天” 
歧异词典没发挥作用

**Comment by ansjsun** [comment]
分词过程是 

歧义词典 -》 核心词典 -》用户自定义词典

词典之间如果不存在交叉冲突。。

则最大匹配， 

你的例子不算冲突

李民 + 工作 +了 = 李民工作了

所以说。。这个结果是符合预期的

**Comment by HerbJiang** [comment]
原來，我把歧異詞典的作用當作「絕對」分詞。
這樣我理解你的邏輯了。這樣沒有方式強制系統作特定的分詞？

**Comment by ansjsun** [comment]
的确和之前的预期有出入我考虑一下..看有什么好的办法保持原貌

**Comment by HerbJiang** [comment]
貌似可以在歧异词典断词时把 TermNatures.id 设为歧异专用的（例如 -3）
后面 UserDefineRecognition 就可以根据这个来避免合并词
