### ISSUE TITLE
新词发现有问题

### ISSUE THREAD

**Issue by fahgrjgdjfle** [NLPchina/ansj_seg#247]
我用了NlpAnalysis的洁面仪的例子，但是分出的是这样的。
[洁/ag, 面/n, 仪/k, 配合/v, 洁/ag, 面/n, 深层/b, 清洁/a, 毛孔/n,  , 清洁/a, 鼻孔/n, 面/n, 膜/n, 碎/a, 觉/v, 使劲/v, 挤/v, 才/d, 能/v, 出/v, 一点点/m, 皱纹/n,  , 脸颊/n, 毛孔/n, 修复/v, 的/uj, 看/v, 不/d, 见/v, 啦/y,  , 草莓/n, 鼻/ng, 历史/n, 遗留/vn, 问题/n, 没辙/v,  , 脸/n, 和/c, 脖子/n, 差不多/l, 颜色/n, 的/uj, 皮肤/n, 才/d, 是/v, 健康/a, 的/uj,  , 长期/d, 使用/v, 安全/an, 健康/a, 的/uj, 比/p, 同龄人/n, 显/v, 小/a, 五/m, 到/v, 十岁/m,  , 28岁/m, 的/uj, 妹子/n, 看看/v, 你们/r, 的/uj, 鱼尾纹/n]

**Comment by ansjsun** [comment]
3.5+版本为什么发现不了新词 #235

参看这个..或者观察日志..会有提示

**Comment by fahgrjgdjfle** [comment]
我用的是3.7.1-all-one版本

**Comment by ansjsun** [comment]
因为没有加载模型.3.x版本之后模型不随jar包下载了

DownLibrary.main(null)

下载..下载完毕后

调用 NlpAnalysis

启动会提示你加载crfmodel 同时会打印模型路径.检查下路径是否正确就可以了

你也可以参看日志。。会有提示的

**Comment by ansjsun** [comment]
历史终将不了了之
