### ISSUE TITLE
下载的编译出来的jar有点小问题

### ISSUE THREAD

**Issue by aashenge** [NLPchina/ansj_seg#255]
3.7 出现了如果UserDefineAnalyses 没有附带forest那么可能停词那出现null错误（代码看过了，改的，但是编译版不行）
3.5 出现了繁简转换失效，userLibrary=library/default（default是文件夹）下面增加字典无法自动读取（除default.dic之外的均读取失败，只能增加在default.dic里）

**Comment by ansjsun** [comment]
试试最新的版本..应该已解决

**Comment by aashenge** [comment]
现在其实还有点小问题，就是当CRF去做新词发现，会把中文和标点放到一起，应该是crf模型的问题吧
另外空格可能被识别为nr，这个如果出现在（nr nr）之间还是有道理的，但是分词之后就很奇怪了

**Comment by ansjsun** [comment]
历史终将不了了之
