### ISSUE TITLE
词性标注 "的" uj 

### ISSUE THREAD

**Issue by chihchiehshao** [NLPchina/ansj_seg#257]
高/a, 准确率/n, 的/uj, 完美/a, 结合/v,

http://nlpchina.github.io/ansj_seg/
词性说明
汉语文本词性标注标记集

没 uj  

新版本问题??

**Comment by chihchiehshao** [comment]
nature.map中包含使用的词性 但与网站上的列表不一致

**Comment by ansjsun** [comment]
是的你可以参考

http://blog.csdn.net/truong/article/details/18847549

文档中的可能不完全

**Comment by chihchiehshao** [comment]
谢谢你的补充 没问题了
