### ISSUE TITLE
分词不准确

### ISSUE THREAD

**Issue by zxl333** [NLPchina/ansj_seg#259]
我使用的是3.7.2版本，用的同样的ansj在线帮助的语句，但是分词结果却大相径庭，分词不准确
List<Term> parse = NlpAnalysis.parse("洁面仪配合洁面深层清洁毛孔 清洁鼻孔面膜碎觉使劲挤才能出一点点皱纹 脸颊毛孔修复的看不见啦 草莓鼻历史遗留问题没辙 脸和脖子差不多颜色的皮肤才是健康的 长期使用安全健康的比同龄人显小五到十岁 28岁的妹子看看你们的鱼尾纹");
    System.out.println(parse);
在线帮助分词结果：
    result:[洁面仪/nw, 配合/v, 洁面/nw, 深层/b, 清洁/a, 毛孔/n, , 清洁/a, 鼻孔/n, 面膜/n, 碎觉/nw, 使劲/v, 挤/v, 才/d, 能/v, 出/v, 一点点/m, 皱纹/n, , 脸颊/n, 毛孔/n, 修复/v, 的/uj, 看不见/v, 啦/y, , 草莓/n, 鼻/ng, 历史/n, 遗留问题/nz, 没辙/v, , 脸/n, 和/c, 脖子/n, 差不多/l, 颜色/n, 的/uj, 皮肤/n, 才/d, 是/v, 健康/a, 的/uj, , 长期/d, 使用/v, 安全/an, 健康/a, 的/uj, 比/p, 同龄人/n, 显/v, 小/a, 五/m, 到/v, 十岁/m, , 28岁/m, 的/uj, 妹子/n, 看看/v, 你们/r, 的/uj, 鱼尾纹/n]

我的分词结果：
       [洁/ag, 面/n, 仪/k, 配合/v, 洁/ag, 面/n, 深层/b, 清洁/a, 毛孔/n,  , 清洁/a, 鼻孔/n, 面/n, 膜/n, 碎/a, 觉/v, 使劲/v, 挤/v, 才/d, 能/v, 出/v, 一点点/m, 皱纹/n,  , 脸颊/n, 毛孔/n, 修复/v, 的/uj, 看/v, 不/d, 见/v, 啦/y,  , 草莓/n, 鼻/ng, 历史/n, 遗留/vn, 问题/n, 没辙/v,  , 脸/n, 和/c, 脖子/n, 差不多/l, 颜色/n, 的/uj, 皮肤/n, 才/d, 是/v, 健康/a, 的/uj,  , 长期/d, 使用/v, 安全/an, 健康/a, 的/uj, 比/p, 同龄人/n, 显/v, 小/a, 五/m, 到/v, 十岁/m,  , 28岁/m, 的/uj, 妹子/n, 看看/v, 你们/r, 的/uj, 鱼尾纹/n]

这是什么原因导致呢？算法改变了，还是在线帮助的经过训然后出来的结果

**Comment by ansjsun** [comment]
没加载辞典和模型 有提示的 看log

发自我的 iPhone

**Comment by ansjsun** [comment]
历史终将不了了之
