### ISSUE TITLE
分配权重分数公式不懂，望解答

### ISSUE THREAD

**Issue by fahgrjgdjfle** [NLPchina/ansj_seg#260]
看粗分词是，看到MathUtil.java中的compuScore函数，里面有个公式，是怎么得来的，
`double value = -Math.log(dSmoothingPara * frequency / (MAX_FREQUENCE + 80000) + (1 - dSmoothingPara) * ((1 - dTemp) * nTwoWordsFreq / frequency + dTemp));`
MAX_FREQUENCE 为什么是常量2079997？为什么加80000？

**Comment by ansjsun** [comment]
ictclas 源码中抄来的..应该是经验公式+ bayes吧..

**Comment by ansjsun** [comment]
历史终将不了了之
