### ISSUE TITLE
分词出来的结构没有去掉标点符号，空格之类的。

### ISSUE THREAD

**Issue by yuanjianfaith** [NLPchina/ansj_seg#261]

**Comment by Lunaticus7** [comment]
参照文档中【停用词】相关内容

**Comment by ansjsun** [comment]
已经修改了在3.7.3中 可以试试

**Comment by hirocc** [comment]
3.7.3发现用NLP分词会出现标点符号，空格等有时会和前面的字“组合” 被识别为新词。。
比如： 前,/3.994875345588278/nw, 称,/3.663641962662617/nw,  店)/1.6059800384274483/nw 等等

**Comment by ansjsun** [comment]
@hirocc 可能这个问题依旧存在.在下一个大版本中会彻底修复这个问题.提供用户自定义训练模型.

**Comment by ansjsun** [comment]
历史终将不了了之
