### ISSUE TITLE
小问题，请孙健大大关注

### ISSUE THREAD

**Issue by aashenge** [NLPchina/ansj_seg#262]
现在其实还有点小问题，就是当CRF去做新词发现，会把中文和标点放到一起，应该是crf模型的问题吧
另外空格可能被识别为nr，这个如果出现在（nr nr）之间还是有道理的，但是分词之后就很奇怪了

另外请关注下 繁简转换字典表，这两个怎么都不是繁简互转的内容吧

叛 判
判 叛

**Comment by ansjsun** [comment]
感谢提供..分词发现标点问题..已经得到改善...在新的版本中..未来会在新的版本中彻底修复这个bug

简繁体...不好说.....感觉问题不是很大 ...再看看哈哈

**Comment by ansjsun** [comment]
历史终将不了了之
