### ISSUE TITLE
能否讲解一下系统架构和涉及到的知识和资料

### ISSUE THREAD

**Issue by aprophet** [NLPchina/ansj_seg#263]

**Comment by hirocc** [comment]
是的，对ansj大神的作品非常感兴趣，无奈很多细节和背景知识不熟悉， 希望能够有一些资料指点，我们可以自学的哈哈

**Comment by ansjsun** [comment]
数据结构上面是 TrieTree
机器学习上面 是hmm+crf+ngram

就这几个就可以了...

**Comment by intohole** [comment]
crf 是什么算法解码的？能问下吗？ 一般训练crf的步骤是什么？ java使用模型 ， 怎么样个思路和算法 ， 能介绍下吗？

2016-04-26 23:30 GMT+08:00 ansj <notifications@github.com>:

**Comment by hirocc** [comment]
感谢指点！

**Comment by ansjsun** [comment]
@intohole 解码是自己写的..只有一种算法vterbi吧...

训练现在的版本是 crf++,或者wapiti 训练. 下一个大版本会推出自己的crf训练..可以等待...

**Comment by intohole** [comment]
就是想问下 维特比算法 ， 一共需要几个矩阵 ， 怎么从crf模型得到啊

**Comment by ansjsun** [comment]
@intohole  在训练的时候需要 差不多需要 n * k*k 大小的矩阵..
n是文本长度.. k是tag个数


在解码的时候..之需要 n*k大小的矩阵就可以..这个你得看 crf的论文..比我只言片语的要详细和争取

**Comment by intohole** [comment]
谢谢，我回去看下crf那篇论文 ；

**Comment by ansjsun** [comment]
历史终将不了了之
