### ISSUE TITLE
孙健大大，无法访问maven.ansj.org呀

### ISSUE THREAD

**Issue by RandomNye** [NLPchina/ansj_seg#264]
访问http://maven.ansj.org/时显示无法找到 maven.ansj.org 的服务器 DNS address，请问是出问题了么？

**Comment by ansjsun** [comment]
maven.nlpcn.org

发自我的 iPhone

**Comment by RandomNye** [comment]
谢谢大大

**Comment by ansjsun** [comment]
@RandomNye 不客气我关了哈
