### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by qinb** [NLPchina/ansj_seg#266]
@ansjsun  你好，我下了你最近一次提交的代码，在调用crf模型的时候报错内存溢出的错误.
  我按照网上的方法进行了调整内存大小，可还是没有用。
   因为对这个原理以及代码不太熟悉，想请问：这个该怎么处理，非常感谢！

**Comment by ansjsun** [comment]
一般是你调整内存的方式不对..

如果是java 命令行调用则 -Xms1024m -Xmx1024m

如果是eclipse 

在代码上右键，依次点击“Run As ”-> “Run Configurations ”，在Arguments 参数中的“VM arguments: ”中填入如下值即可。

-Xms1024m -Xmx1024m
