### ISSUE TITLE
求助求助..诡异的问题..!词性标注结果是乱的

### ISSUE THREAD

**Issue by sinb** [NLPchina/ansj_seg#267]
我在本地写好了服务，用到了词性标注ToAnalysis.parse，测试一切正常.
但是部署到服务器上，得到的词性标注结果居然乱掉了。

比如：输入是： “美国站国际道义制高点”
我直接把List<Terms> terms打印出来，在本地的正确结果是：
[美国/ns, 站/v, 国际/n, 道义/n, 制高点/n]
但是在服务器上的结果却是：
 [nsf/36089, n/24601, 际/ng, n/230, 义/ng, n/100, 高点/n]

单词和词性的位置乱掉了！有人遇到这种情况吗，求指教。

**Comment by ansjsun** [comment]
这个事情应该可以确定不是程序的问题。。。。你最好可以把日志下载回本地打开看看。。。看上去也不是乱码。。或者把结果写入到文件。。下载回来看看。。

**Comment by sinb** [comment]
嗯啊，找到问题了,如果在服务器上我不加载default.dic,结果就是对的，加上之后分词就错了，看来是词典文件乱了。这个default.dic是我从windows里拖过去的，我去瞅瞅是不是换行符问题。。
另外在此对ansj_seg项目表示跪地感谢！

**Comment by sinb** [comment]
解决了。。程序木有任何问题，我自己词典格式乱掉了。。
再次感谢ansj_seg项目！
