### ISSUE TITLE
can not run lucence5 plugin

### ISSUE THREAD

**Issue by syzxlyx** [NLPchina/ansj_seg#268]
In lucence5-plugin ,when i compile and run indexertest,I found AnsjAnalyzer have not type.When getTokenizer ,it throw exception.So test is failed.
How to solve the problem?

**Comment by ansjsun** [comment]
i am sorry! it is my miss take!

``Analyzer ca = new AnsjAnalyzer(TYPE.dic);``

now it fixed!

**Comment by ansjsun** [comment]
历史终将不了了之
