### ISSUE TITLE
怎么样定义自己的词库

### ISSUE THREAD

**Issue by 644020240** [NLPchina/ansj_seg#269]
你好，有个问题请教下，我有些地址类的数据大概10万条左右，比如江苏省南京市鼓楼区中山北路93号，我在分词的时候当记录中包含这个地址的时候能不能不让它切词，并且给它一个词性。请问这个可以定义自己的地址词库吗？

**Comment by ansjsun** [comment]
当然可以。。自定义词库的使用的详细方式。参看首页的文档。。

**Comment by 644020240** [comment]
首页文档？请问有链接吗？里面有详细的介绍方法吗？
麻烦了，由于是刚刚接触ansj，有许多不懂的地方，之前一直是用ictclas，

**Comment by ansjsun** [comment]
http://nlpchina.github.io/ansj_seg/

**Comment by GongLe** [comment]
字典格式看不懂，请问有文档介绍吗？

**Comment by ansjsun** [comment]
三列用tab隔开..词 词性 词频

**Comment by GongLe** [comment]
博主回复真及时，要支付宝转了点代码钱，哈哈。
我拉了源代码，最近在看一些用到的算法，之前没弄过自然语言分词。

**Comment by ansjsun** [comment]
@GongLe 已收到巨款

**Comment by ansjsun** [comment]
历史终将不了了之
