### ISSUE TITLE
why ansj_lucene5_plugin has not PorterStemmer

### ISSUE THREAD

**Issue by syzxlyx** [NLPchina/ansj_seg#270]
I can find PorterStemmer class in ansj_lucene4_plugin,but do not find it in ansj_lucene5_plugin.Is the class replaced by other class or not needed in ansj_lucene5_plugin?

**Comment by ansjsun** [comment]
We think this is useless! so remove it!

**Comment by ansjsun** [comment]
历史终将不了了之
