### ISSUE TITLE
lucene5.5 新的API新建field没有被索引

### ISSUE THREAD

**Issue by coder-huang** [NLPchina/ansj_seg#272]
我用的是官网的indexTest的demo,但在新建索引的时候，使用新的API创建field不能生效
   Document doc = new Document();
// Field field = new StringField("text", text, Store.YES);
// doc.add(field);
   doc.add(new Field("text", text, Field.Store.YES, Field.Index.ANALYZED));
   iwriter.addDocument(doc);

只能使用废弃的API吗？

**Comment by ansjsun** [comment]
1.StringField是不分词的field.
2.可以用这个Field field = new TextField("text", text,Store.YES) ;

**Comment by coder-huang** [comment]
经测试可以，O(∩_∩)O谢谢

**Comment by ansjsun** [comment]
历史终将不了了之
