### ISSUE TITLE
关于日期等时间词的分词和识别

### ISSUE THREAD

**Issue by hirocc** [NLPchina/ansj_seg#273]
请问各位大神，是否有方法能够对“ 5月16日”这样的日期格式整体实现整体分词，并打上/t 的标签呢？
3.7.3版本中不论是DicAnalysis还是NlpAnalysis都会拆开并识别为数词或新词。

**Comment by ansjsun** [comment]
抱歉..目前不能做..这中颗粒度级别..未来可能通过类似于插件的方式来实现

**Comment by ansjsun** [comment]
历史终将不了了之
