### ISSUE TITLE
NlpAnalysis的一个分词bug，但是我不知怎么修复

### ISSUE THREAD

**Issue by jimichan** [NLPchina/ansj_seg#274]
对文本 『2015年无锡市突发环境事件』 进行分词。
结果是  

无锡市
突发
无锡市
突发
环境
事件

错误在于词的重复，还有2015年这个nw的丢失

代码第111行左右
//						if (isRuleWord(word)) { // 如果word不对那么不要了
//							temp = null;
//							continue;
//						}
在这个里面有任意的continue执行，都会导致错乱
记得在以前的版本中没有这个问题，那时候我会加一个判断nw的长度的代码，大概就是
if(word.lenth()>6){
continue;
}
这个的代码现在也不能正确执行了，就是continue逻辑导致的

**Comment by ansjsun** [comment]
我在我本地版本测试是没有这个问题的.你用的版本是?最近打算发布一个大版本..正好修复下

**Comment by ansjsun** [comment]
尝试做一个大的重构发现工作量蛮大的哎

**Comment by jimichan** [comment]
好吧，是我错了
我读取词是用的 term.getName() ，其实应该用term.getRealName()才会正确,
用getName就会得到那个错误的结果

那么
term.toString(){
if ("null".equals(nature.natureStr)) {
			return name;
		}
		return this.getRealName() + "/" + nature.natureStr;
}
}
就需要改成

if ("null".equals(nature.natureStr)) {
			return getRealName();
		}
		return this.getRealName() + "/" + nature.natureStr;
}

**Comment by jimichan** [comment]
我刚提交了一下，原来是
if (isRuleWord(word)) { // 如果word不对那么不要了
							temp = null;
							tempOff += word.length();//这里offset原来没有设置导致后面的错位了
							continue;
						}
原来tempOff没有正确偏移又导致了一些错位的问题
