### ISSUE TITLE
自定义分词搜索问题

### ISSUE THREAD

**Issue by odao** [NLPchina/ansj_seg#275]
作者您好，我在default.dic里直接增加了自定义词，但是搜索结果总是匹配不到完整的自定义词。如，我加了一个`3-4(小班) userDefine 1000`，但是直接搜索`3-4(小班)`找不到结果，但确实是有完全匹配的记录。请问这种情况问题出在哪里？

**Comment by ansjsun** [comment]
1 词典路径错误没有加载成功
2 增加词语格式不对 比如\t 写成空格
3 词典编码或用win记事本增加了不可见字符在记事本中

发自我的 iPhone

**Comment by odao** [comment]
谢谢您的回复。确实如此。
