### ISSUE TITLE
如何设置分词的优先级，比如“男单鞋”

### ISSUE THREAD

**Issue by javahaohao** [NLPchina/ansj_seg#276]
“男单鞋”，分词器默认词典文件给我分成了“男单/j, 鞋/n”，我在扩展词典文件里面配置了“单鞋”也没有起作用？如何解？请指点一二（还有个疑问词典文件中的词频作用于那？）
ToAnalysis分词器

**Comment by ansjsun** [comment]
试试dicanalysis

发自我的 iPhone
