### ISSUE TITLE
请问如何调高自定义词库的优先级？

### ISSUE THREAD

**Issue by MaskRaylosT** [NLPchina/ansj_seg#278]
我在scala程序开发中需要分词，使用3.7.5版本
UserDefineLibrary.insertWord("顺丰", "ud", 3200)
    val content = "顺丰收货真是太给力了"
    val terms = ToAnalysis.parse(content)
println(terms.toArray.mkString(","))
顺/a,丰收/v,货/n,
而我想要的是
顺丰/ud,收/v,货/n
请问我应该如何配置才能优先用自定义词库呢？

**Comment by ansjsun** [comment]
使用DicAnalysis

**Comment by MaskRaylosT** [comment]
ok，成功了，多谢！
