### ISSUE TITLE
请教下如何将自己新增的歧义纠正条目保存到歧义纠正辞典中

### ISSUE THREAD

**Issue by bobcy2015** [NLPchina/ansj_seg#279]
目前手头有数万篇文本用ansj进行了分词处理，要从中找出地名，人名等特定词性的词语，我用推荐的精准分词-ToAnalysis对这数万篇文本 进行分词并按照词性提取出地名，人名等特定词性的单词，做了一个统计列表，发现其中有差不多10%左右的词性是明显错误的，尤其是人名的统计词列表。然后我手动用作者提供的方式动态添加了上百条歧义纠正条目来修正分词，重跑后效果有所改善，我添加条例的代码类似这样：
        value = new Value("西康","西康","ns");
        Library.insertWord(UserDefineLibrary.ambiguityForest, value);
        value = new Value("金华","金华","ns");
        Library.insertWord(UserDefineLibrary.ambiguityForest, value);
        value = new Value("中华人民共和国","中华人民共和国","nt");
        Library.insertWord(UserDefineLibrary.ambiguityForest, value);
        value = new Value("铁建十六局","铁建十六局","nt");
        Library.insertWord(UserDefineLibrary.ambiguityForest, value);
        value = new Value("荆楚网","荆楚网","nw");
        Library.insertWord(UserDefineLibrary.ambiguityForest, value);
        value = new Value("豆丁网","豆丁网","nw");
        Library.insertWord(UserDefineLibrary.ambiguityForest, value);
        value = new Value("李","李","nr1");
        Library.insertWord(UserDefineLibrary.ambiguityForest, value);
        value = new Value("郑","郑","nr1");
        Library.insertWord(UserDefineLibrary.ambiguityForest, value);

目前手动添加了上百个这样的歧义纠正条目，发现还有上千个类似的单词需要纠正词性，我不想在程序每次运行时都这样先用代码动态添加上千个歧义纠正条目，想写个程序先把其保存到歧义纠正辞典中，或者写入到自定义词典中，但是我在自定义词典的demo代码中没看到如何设置词性的例子，请问该如何做，谢谢。

**Comment by ansjsun** [comment]
这种情况你试试DicAnalysis 应该效果会好 你的业务是词典优先 如果没有这个类 你下载最新的jar包

发自我的 iPhone

**Comment by bobcy2015** [comment]
我用的的是3.7.3 all in one，才发现更新到了3.7.5，不过DicAnalysis 还没有文档吧，不清楚怎么用，我还是想尽量用比较熟悉的3.7.3来开发。

还有个问题想麻烦下作者大大，我开发环境是eclipse+maven插件，使用maven来创建的项目，POM里面搜索ansj，目前都只能找到0.9版的jar包。我用本地添加jar包的方式来把下载的ansj jar包导入到项目中，这样用mvn clean  install的方式生成的jar包里面，不包括ansj的jar包，因为最终程序还要用exe4j生成exe放到另外一台没安装开发环境的机器上跑，目前在找方法看怎么把外部导入的jar包捆绑打包到maven生成的单个jar包中，如果大大能把3.7.3 all in one发布到maven上就好了，多谢。

**Comment by ansjsun** [comment]
3.7.5 版本挺好用的..建议升级使用DicAnalysis ..这个是用户自定义词典优先的策略..

关于maven

你需要做如下配置


````
    <!-- 增加新的maven源,这个是必须的 -->   
    <repositories>
        <repository>
            <id>mvn-repo</id>
            <url>http://maven.nlpcn.org/</url>
        </repository>
    </repositories>


    <dependencies>
        ....

        <dependency>
            <groupId>org.ansj</groupId>
            <artifactId>ansj_seg</artifactId>
            <version>3.7.5</version>
        </dependency>
        ....
    </dependencies>
````

**Comment by bobcy2015** [comment]
谢谢大大的指点，现在可以把ansj打包到maven创建的jar包里面了。我换成了3.7.5的DicAnalysis跑了下，把我之前添加的上百个的歧义纠正条目都注释了，跑完发现还是得添加那些歧义纠正条目，不然这类词的词性明显还是分类错误。我从我自己生成的统计摘要文档中抽一部分给大大看看：
地名里面的错误：
东至/ns:4320:
北至/ns:3006:
南站/ns:1796:
西至/ns:1460:
土岭/ns:773:
客运专线/nz:586:
确保安全/ns:581:

人名里面的错误：
成渝/nr:3218:
焦柳/nr:1630:
武广/nr:864:
石亭江/nr:818:
张滩至/nr:485:
兰新线/nr:391:
荆楚网/nr:212:
后面的数字是这些词在我的2万多个测试文档中出现的总次数统计。

我之前的做法是每跑一次从统计中找出这些明显不对的词，用代码动态添加到歧义纠正辞典中，想问下如果换成DicAnalysis的话，是不是还是这样处理，还是说我可以自定义一个词典，把我发现的这些词保存到自定义词典中，然后加载自定义词典。如果可以的话，请问大致代码该如何写，最关键的是我想知道怎么给自定义添加的词设置词性，还有如何加载自定义词典，谢谢大大。

**Comment by ansjsun** [comment]
额你需要把之前的词条加入到用户 自定义词典中.然后用..dicanalysis 试试..

1.自定义词典加载...
你现在没有挂载自定义词典吗???

最简单的办法.系统启动的时候有个日志..warning ..说自定义词典在某个路径下不存在

````
file in path 词典路径 can not to read!");
````

如果加载成功显示

````
"init user userLibrary ok path is : 词典路径
````

你在词典中添加修改词语即可.

词典格式参考..

http://maven.nlpcn.org/down/library/default.dic

**Comment by bobcy2015** [comment]
我的日志是：
2016-05-26 12:34:01 007 [ main:5403 ] [ DICLOG:(88) ] - [ WARN ] not find library.properties in classpath use it by default !
2016-05-26 12:34:01 915 [ main:6311 ] [ DICLOG:(139) ] - [ INFO ] init user userLibrary ok path is : D:\projects\search\analyzer\library\default.dic
2016-05-26 12:34:01 915 [ main:6311 ] [ DICLOG:(84) ] - [ INFO ] init ambiguityLibrary ok!
2016-05-26 12:34:03 304 [ main:7700 ] [ DICLOG:(75) ] - [ INFO ] init core library ok use time :1374
2016-05-26 12:34:03 790 [ main:8186 ] [ DICLOG:(17) ] - [ INFO ] init ngram ok use time :453
谢谢大大的指点，目前我就是用的Library目录下的默认字典default.dic，大小5.63 MB (5,908,047 字节)来进行分词，该目录下还有ambiguity.dic和crf.model两个文件，我是不是用一个类似UE这样的文本编辑器打开dic文件，然后按照格式每行添加一个词目就行了？如果是这样的话，我可以把我需要纠正的词目写入到ambiguity.dic里面吗？因为default.dic里面每个单词的后面还有频率这个数字，我不清楚我添加的词目的频率数字是多少

**Comment by ansjsun** [comment]
1.是的你得用户自定义词典就是 D:\projects\search\analyzer\library\default.dic

2.是的用ue打开直接修改.比如你说词性错误.在里面找到那个词语改对词性就可以.

3.词频数默认写个1000就可以.

ps:  单个词语消歧,不建议用ambiguity.dic  速度慢你可以把词语假如到default.dic中,然后用DicAnalysis来分词看看效果,应该会好很多

如果你有能力整理自己的词典完全替代default.dic也是不错的选择.

**Comment by bobcy2015** [comment]
谢谢，知道了，每个词目之间的空格是tab吧？

**Comment by ansjsun** [comment]
是的 一定是tab

发自我的 iPhone

**Comment by ansjsun** [comment]
历史终将不了了之
