### ISSUE TITLE
面向索引分词是不是粒度太细了？

### ISSUE THREAD

**Issue by sinb** [NLPchina/ansj_seg#281]
String s = "安徽合肥";
List<Term> parsedTermList = IndexAnalysis.parse(s);
System.out.println(parsedTermList);

结果是：
[安徽/ns, 合肥/ns, 安/ag, 徽/ng, 合/v, 肥/n]

没有必要这么细吧？这样建索引对准确率影响会很大，请问有没有办法控制这个粒度？谢谢！

**Comment by ansjsun** [comment]
如果觉得太细.可以考虑 dicanalysis 或者toanalysis

**Comment by ansjsun** [comment]
历史终将不了了之

**Comment by anoteboy** [comment]
我想问下 这个具体是哪个版本 我现在的需求就是需要这样的粒度分词，望告知

**Comment by ansjsun** [comment]
所有版本都可以。需要你挂载用户自定义词典。词典中有单字都给识别出来了@anteboy
