### ISSUE TITLE
还是繁简转换的问题，部分简繁转换的很奇怪

### ISSUE THREAD

**Issue by aashenge** [NLPchina/ansj_seg#282]
哪 那
哪 娜
妠 钠
艿 奶
悩 脑
哞 牟
沬 抹
沬 末
佲 铭
洺 名
嫚 曼
嫚 慢
嬤 吗
囉 锣

记录下来的不太多 感觉很多转换问题相当大  我只是抽取了100条，手工标注了下。。。

**Comment by aashenge** [comment]
要不要开放个子版本，让大家一起来整理？

**Comment by ansjsun** [comment]
感谢你的意见..github就是最好的开放..but没有人来修改.简繁体是个若需求...

**Comment by ansjsun** [comment]
历史终将不了了之
