### ISSUE TITLE
自定义词典的调用

### ISSUE THREAD

**Issue by wanghaisheng** [NLPchina/ansj_seg#283]
如果是在library.properties中如下配置
```
dic_[unit]=unit.dic
```
        Forest forest = MyStaticValue.getDicForest("unit");
        UserDefineLibrary.FOREST = forest;
        System.out.println(DicAnalysis.parse(str,forest));
这样子调用为何不会使用自定义词典

**Comment by wanghaisheng** [comment]
```
    private static void loadFormFile(String dic_path) {
        // TODO Auto-generated method stub
        // make new forest
        Forest forest = new Forest();

        UserDefineLibrary.loadLibrary(forest, dic_path);

        // 将新构建的辞典树替换掉舊的。
        UserDefineLibrary.FOREST = forest;
    }
    public static void main(String args []){
        //通过配置文件library.properties来添加自定义字典


        // 从文件中reload
        loadFormFile("unit.dic");
｝
```

**Comment by ansjsun** [comment]
第一个问题..

dic_unit=/path/unit.dic

 Forest forest = MyStaticValue.getDicForest("dic_unit"); //获取这本词典就是你配置文件的key

System.out.println(DicAnalysis.parse(str,forest, UserDefineLibrary.FOREST, unit)); //词典可以放多个.有先后顺序

**Comment by ansjsun** [comment]
第二个问题
unit.dic 格式好像有问题
90后[制表符]userDefine[制表符]2000

制表符就是\t ,没有中括号,词典要求utf-8格式.不要用win记事本来编辑词典

**Comment by wanghaisheng** [comment]
thx
