### ISSUE TITLE
人名识别可能关掉吗？

### ISSUE THREAD

**Issue by jiaruita** [NLPchina/ansj_seg#284]
“戴防蓝光眼镜”，
被分成了：“戴防蓝 光 眼镜”。
用的ToAnalysis，添加了自定义词库，但是词库里没有“戴防蓝”这个词。
这里“戴防蓝”是不是当成一个人名了？这样的话，这个功能可能被关掉吗？
谢谢。

**Comment by ansjsun** [comment]
用DicAnalysis试试

发自我的 iPhone

**Comment by oczjack** [comment]
是不是用的逆向分词算法啊？



365570664@qq.com
 
发件人： Ru
发送时间： 2016-06-14 17:34
收件人： NLPchina/ansj_seg
主题： [NLPchina/ansj_seg] 人名识别可能关掉吗？ (#284)
“戴防蓝光眼镜”，
被分成了：“戴防蓝 光 眼镜”。
用的ToAnalysis，添加了自定义词库，但是词库里没有“戴防蓝”这个词。
这里“戴防蓝”是不是当成一个人名了？这样的话，这个功能可能被关掉吗？
谢谢。

**Comment by ansjsun** [comment]
不是的...是自定义词典优先的策略你可以看这里https://github.com/NLPchina/ansj_seg/wiki/%E5%88%86%E8%AF%8D%E6%96%B9%E5%BC%8F这是他们的区别

**Comment by jiaruita** [comment]
用DicAnalysis不会有这种问题，但是通过比较diff感觉整体效果不如ToAnalysis，可能是我的词库不够好。
所以还是用了ToAnalysis。
我试了在配置文件里加上isNameRecognition=false，但是结果还是一样的，这项配置对ToAnalysis有效果吗？

**Comment by ansjsun** [comment]
有可能你的配置文件没有加载.

注意看下日志是否找到了library..


你可以用硬编码的方式..


在程序里面调用

MyStaticValue. isNameRecognition = false ;

这么设置一次就可以了

**Comment by ansjsun** [comment]
历史终将不了了之
