### ISSUE TITLE
default词典的词性一点点小问题

### ISSUE THREAD

**Issue by aashenge** [NLPchina/ansj_seg#285]
上上大吉    ns  3
上不去   t   3
3.x版本里是
上上大吉    l   3
上不去   v   3

新版本的词性仿佛错了

**Comment by ansjsun** [comment]
应该是对的...

这里是词性说明

**Comment by aashenge** [comment]
t是时间词啊。。。上不去 怎么也不会是时间词
ns是地名啊。。。上上大吉应该也是l 习用语

**Comment by ansjsun** [comment]
历史终将不了了之
