### ISSUE TITLE
关于5.0的自定义词典一个怪异的bug

### ISSUE THREAD

**Issue by vpccw152c** [NLPchina/ansj_seg#286]
在使用5.0的自定义词典功能时，自定义的词典中第一个词无法被识别，从第二个开始才会被识别，如果第一行留白，就可以正常工作。
例如，自定义词典内容如下：
售后      userDefine   1000
否其      userDefine   1000
其中“否其”是故意写的一个很怪异的自定义词，这时分词结果为
售/v
后/f
否其/userDefine
也就是说售后没有被识别，否其被识别了。如果将两者顺序对调，变为
否其       userDefine    1000
售后       userDefine    1000
分词结果为：
售后/userDefine
否/vg
其/r
也就是说否其被忽略了。如果将第一行留白，变为

否其       userDefine    1000
售后       userDefine    1000
分词结果为：
售后/userDefine
否其/userDefine
请问这个可能是什么原因？是我有什么地方使用错误了吗？

**Comment by windyjune** [comment]
这应该是编辑器的原因，有些编辑器如记事本，会在开始的位置增加一个字符

**Comment by vpccw152c** [comment]
已经解决了，用notepad++打开，转码为"UTF-8 无BOM格式编码"就行了，谢谢楼上的提醒

**Comment by ansjsun** [comment]
历史终将不了了之
