### ISSUE TITLE
能不能提供一个crf.model.text的文件？

### ISSUE THREAD

**Issue by waiteryee127** [NLPchina/ansj_seg#287]
能不能提供一个crf.model.text的文件？我想试验一下load crf.model.text的功能，谢谢

**Comment by ansjsun** [comment]
这种文件都很大。。。且和load普通模型区别一样。。后台根据文件头判断的。。所以基本上看不出区别。你可以通过我wiki来自己训练一个。那个wiki写的挺详细的

**Comment by ansjsun** [comment]
历史终将不了了之
