### ISSUE TITLE
可以用来实现敏感词过滤么？

### ISSUE THREAD

**Issue by xiuhuwang** [NLPchina/ansj_seg#289]
我想通过自定义个敏感词词库，然后根据分词的结果，对敏感词进行替换或者删除操作。这种方式是否可行呢？

**Comment by ansjsun** [comment]
这个不用分词..直接用replace 或者用 nlp-lang 里面的Forest就可以实现

**Comment by xiuhuwang** [comment]
直接replace的话效率慢，而且有些情况不好处理。目前我采用了nlp-lang中的Forest，敏感词当作词典。但发现这样一个问题，比如：我是一个处女座的处*。加入处*是敏感词，处女座不是，这时候处理的结果是处女座中的处*也给处理掉了，但是使用分词却不会出现这个问题。你有什么建议？
谢谢你~

**Comment by xiuhuwang** [comment]
谢谢你的建议。
今天发现这样一个问题，如果不分词的话，我根据敏感词词典提取出敏感词后，做替换的时候，会误伤。比如处女座不是敏感词，处女是敏感词的话，处女座就会被处理成了**座。你有好的建议么，谢谢了。

**Comment by ansjsun** [comment]
把处女座加入词表

发自我的 iPhone

**Comment by xiuhuwang** [comment]
我试了这种方式，然后通过SmartGetWord提取关键词，均能提取出来这两个词，但是对语句replace的时候，就会替换掉了。分词的话，处女座是一个单词，所以不会误伤。是我使用的方式不对么？

**Comment by ansjsun** [comment]
用 getFrontWords 不要用 getAllWords

**Comment by JasonHuangHe** [comment]
@xiuhuwang hi，代码能分享下么？

**Comment by ansjsun** [comment]
历史终将不了了之
