### ISSUE TITLE
请问，怎样才能加入你们呢？

### ISSUE THREAD

**Issue by flystarhe** [NLPchina/ansj_seg#292]
看到你在 readme 中的文字“4.提供更加优化的CRF模型。替换ansj的默认模型。”，我想试试，请问可以吗？我工作会用 NLP 技术，不过重心不在这，有一定可能会半途而废（比如工作变得繁重起来的时候）

**Comment by ansjsun** [comment]
当然可以。 。我觉得还是先尝试吧。。用crf++或者wapiti训练一个好的crf模型。。

我们对crf模型 主要侧重于。  未登录词识别 和 模型体积的找一个最优的性价比

**Comment by flystarhe** [comment]
好的，我先跑通一个。

**Comment by flystarhe** [comment]
hi，我用CRF++跑了一个分词模型，不过是用python玩的。请问你方便分享一份java使用训练好model的参考资料吗？

**Comment by ansjsun** [comment]
@flystarhe  https://github.com/NLPchina/ansj_seg/wiki/%E5%AE%9A%E5%88%B6%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84CRF%E6%A8%A1%E5%9E%8B  这里有

**Comment by flystarhe** [comment]
@ansjsun thx，用CRF++训练基本是按套路来，高质量的语料太少了，北京大学的那个分词和词性标注语料感觉有不少错误和冲突

**Comment by flystarhe** [comment]
@ansjsun 请教一个问题，资料里是训练的2列的模型，比如ner训练时加了词性的，至少也是3列，这样训练的模型用你的方式加载，执行的结果还可靠不？

**Comment by ansjsun** [comment]
我那个就不支持三列。。只支持两列

**Comment by flystarhe** [comment]
@ansjsun 你好，我在看你crfmodel的源码，希望能在基础上修改一个能读ner训练模型的，先假设两列吧，不过是6tag的。但是看不懂，能分享一些资料吗？

**Comment by ansjsun** [comment]
历史终将不了了之
