### ISSUE TITLE
WIKI 错误：用户自定义词典

### ISSUE THREAD

**Issue by delei** [NLPchina/ansj_seg#295]
1. 在wiki的[用户自定义词典]中，有一段：[点这里](https://github.com/NLPchina/ansj_seg/wiki/用户自定义词典)
`注意5.0.x以后的版本应按如下操作`
下面是空白的

2. 后续是否特别新增5.0.x的有关实例说明？比如说，parse后返回的为Result对象。这种变化还是比较大的。

**Comment by delei** [comment]
5.0.x的用户子典按照wiki说明导入了自定义字典。但是不太会写dic文件，我模范code 中src/library/中的dic写了下，感觉我可能还没有明白这个文件的写法，但是用Java代码的写法
`UserDefineLibrary.insertWord("xxx", "xxx", 100);`
是可以使用的。

如果我们自定义字典，dic文件应该如何来定义呢，看src/library/里面的很简单的。但是模仿写好像有问题

注：已经通过library.properties中定义好了，启动时log也未报file not found的错误。
我的dic文件内容:
```
上海电力 datadriver 100
上海电 datadriver 101
````

Java:
```
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.ansj.domain.Result;
import org.ansj.splitWord.analysis.DicAnalysis;

public class ansjTest {

	public static void main(String[] args) {
		List<String> strList = new ArrayList<>();
		HashMap<String, String> keyMap = new HashMap<>();
		strList.add("上海电力独立董事就公司聘");
		Result analysisList = null;
		for (String temp : strList) {
			// UserDefineLibrary.insertWord("上海电力", "datadriver", 100);
			analysisList = DicAnalysis.parse(temp);
			System.err.println(analysisList);
		}

	}

}

```
result：
```
上海/ns,电力/n,独立/a,董事/nnt,就/d,公司/nis,聘/v
```

**Comment by ansjsun** [comment]
UserDefineLibrary.insertWord("xxx", "xxx", 100); 第一个参数是词语..第二个参数是词性.第三个参数是权重.一般用词频.如果不知道就写2000

关于文件dic的分割符是用的\t 就是tab 就是制表符 .

**Comment by ansjsun** [comment]
这几天在搞另一个项目..这个文档先暂时告以段落..等忙回来..来做啊

**Comment by delei** [comment]
嗯。是tab的问题，我在eclipse中是用4个空格代替tab的，所以没法用

@ansjsun  另外，我今天在wiki中改了你的“错别字”。

－－－－－－－多问一下－－－－－－－－－
为何要使用tab呢？支持用空格吗？

> 哈哈，我去研究下source code，看能不能修改修改支持用空格呀。哈哈

**Comment by delei** [comment]
哈哈。找到了，在这里
org.nlpcn.commons.lang.tire.library第85行insertWord
```
String[] param = temp.split("\t");
```

**Comment by ansjsun** [comment]
在自然语言里面空格是字符...词语里面极可能有空格....比如英文短语全称等.所以你懂得...文档实在没时间补...你要是有兴趣可以帮我写点...

**Comment by delei** [comment]
是这样呀！OK，学习了！
对于这个我也算是初次具体接触，但会去稍微研究下源码！我是怕误导其他人，可能，某天我就在WIKI里面加些实例什么的！😁
