### ISSUE TITLE
核心词库更新?

### ISSUE THREAD

**Issue by ziq211** [NLPchina/ansj_seg#296]
请问一下, ansj的核心词库(一元词频, 二元词频)是和NLPIR-ICTCLAS保持同步更新的吗? 有没有什么工具能把ICTCLAS的核心词库转换成ansj的格式?
另外, 假如我有一份某个领域的熟语料, ansj有没有工具来根据这个语料重新生成新的核心词库?
谢谢

**Comment by ansjsun** [comment]
没有现成的工具需要自己整理

**Comment by ziq211** [comment]
谢谢, 明白了. 另外现在ansj的核心词库是自己做的吗, 生成词库的语料是来自哪里呢?

**Comment by ansjsun** [comment]
大多来自于ictclas 的核心词典..自己整理了少部分

**Comment by ziq211** [comment]
谢谢, 挺好奇ansj自己整理的少部分词是怎么和ictclas的词库集成起来的?
按我的理解, 在HMM模型里核心词库的词频是选取N-最短路径的关键. 在不知道ictclas核心词库的语料来源时, ansj如何处理自己的词频从而和ictclas的词频相匹配? 比如说这个问题, 因为ictclas的语料库规模更大, 导致在词库里来自ictclas的词相应的词频更高.
或者说, 我们没用用词频的绝对值, 而是用概率=词频/语料中词的总数. 这样的话就需要保证ansj词库的语料在词的分布上要和ictclas的基本一致.

**Comment by ansjsun** [comment]
后加的数字完全是蒙的

**Comment by ansjsun** [comment]
历史终将不了了之
