### ISSUE TITLE
检索分词的问题

### ISSUE THREAD

**Issue by ZhouJiaLinmumu** [NLPchina/ansj_seg#299]
您wiki中提到的"旅游和服务"这个case，分出来的结果仍是：旅游/vn,旅/vg,游/v,和服/n,和/c,服务/vn,服/v,务/vg。请问怎样才能像你wiki中说的，解决这种跨term的问题，使其部分分出“和服”这样的词来？

**Comment by ansjsun** [comment]
不要用索引分词。。用toanalysis，或者dicanalysis试试吧 。。。
