### ISSUE TITLE
请教关于根据词性设置停用词

### ISSUE THREAD

**Issue by xiabiyu** [NLPchina/ansj_seg#300]
您好。我想请教下ansj里面使用词性来设置停用词filter，是否有词性对照表可以进行参考？没有搜索到可用的。

**Comment by ansjsun** [comment]
如果是5.0版本

https://github.com/NLPchina/ansj_seg/wiki/%E5%81%9C%E7%94%A8%E8%AF%8D%E8%BF%87%E6%BB%A4

**Comment by xiabiyu** [comment]
多谢，请问是否有fitler.insertStopNatures("uj"); 关于这个uj、ul分别对应什么的对应表？

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/wiki/%E8%AF%8D%E6%80%A7%E6%A0%87%E6%B3%A8%E8%A7%84%E8%8C%83


词性看这里...

但是..可能不完全匹配... 你注意开头的u 就可以 ..

**Comment by xiabiyu** [comment]
非常感谢！
