### ISSUE TITLE
英文分词大小写问题。

### ISSUE THREAD

**Issue by YaoKaixuan** [NLPchina/ansj_seg#303]
1、用户自定义词典里面维护的英文，只能分词出小写英文；
  2、句子中大写的英文，分词后也变成了小写；
请问，上面这两个问题怎么解决？

**Comment by ansjsun** [comment]
通过 term.getRealName() 来获取原文中的词语。。 前提是你打开 MyStaticValue.isRealName=true 。好像默认是开着的

**Comment by YaoKaixuan** [comment]
您好，用户自定义词典里面我维护了“FOREST daxie 1000”，也维护了“forest xiaoxie 1000”，分词语句中包含“FOREST和forest”，分词结果FOREST的词性是xiaoxie，forest的词性也是xiaoxie。
    当我只删除词典里面“forest xiaoxie 1000”这个词，保留“FOREST daxie 1000”这个词，重新分词后，FOREST和forest的词性都变成en，这表示不能识别大写，对吗。

**Comment by ansjsun** [comment]
用户自定义dic必须小写..

关于词性
你需要调用一次词性修正,以用户自定义词典优先...


如果你用的5.0的版本可以参看

关于5.0中FilterModifWord方法的问题 #290

**Comment by ansjsun** [comment]
历史终将不了了之
