### ISSUE TITLE
关于NlpAnalysis分词有个问题请教下

### ISSUE THREAD

**Issue by xiabiyu** [NLPchina/ansj_seg#304]
您好，我在分词中使用动态添加自定义词，使用NlpAnalysis.parse时候不管我把添加进去的词词频设置如何都始终会把词标注为新词。
UserDefineLibrary.insertWord("暖", "userDefine", 1000000000);
Result res = NlpAnalysis.parse("太暖啦！");
结果为：
例子:太暖/nw,啦/y,！/w
这个是否可以让新词发现的优先级并不这么高？

**Comment by ansjsun** [comment]
目前还不能。如果你自定义词典优先级高。。可以选择DicAnalysis的方式
