### ISSUE TITLE
ansj_seg分词所参考的paper是什么？

### ISSUE THREAD

**Issue by robotdj** [NLPchina/ansj_seg#305]
这个分词工具很赞，我是nlp新手，想结合ansj_seg学习分词，希望能有ansj_seg所参考的paper信息～

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/wiki 这个写了用到的技术。。参考资料重点看ictclas

**Comment by ansjsun** [comment]
历史终将不了了之
