### ISSUE TITLE
Ansj有没有对txt文件分词的方法？

### ISSUE THREAD

**Issue by YaoKaixuan** [NLPchina/ansj_seg#306]
您好，想问一下有没有对txt文件进行分词的方法。

**Comment by ansjsun** [comment]
..... ..一点程序都不写的分词吗?

**Comment by YaoKaixuan** [comment]
因为之前用word分词器的时候，有一个分词函数是直接输入要分词的txt文件路径，和分词后结果保存的txt文件路径即可，挺方便的。现在改用Ansj了，如果没有的话，我自己写一个好了。

**Comment by ansjsun** [comment]
没有 但是你可以这么写

IOUtil.Writer("result.txt", "utf-8", IOUtil.getContent("需要分词的文本.txt", "utf-8"));

**Comment by ansjsun** [comment]
历史终将不了了之
