### ISSUE TITLE
关于标点符号的问题

### ISSUE THREAD

**Issue by xiabiyu** [NLPchina/ansj_seg#307]
孙健大大您好，又来打扰，在分词中对于标点符号的解析遇到了个问题，希望您能解答下。
在分词一份文本时发现，如果文本中是中文标点符号，分词器可以准确地将标点分出。但是如果分词的文本中存在英文的标点符号，就无法识别出标点符号，输出为/null词性，'.'英文的句号在默认词典中解析为/m量词。是否是Ansj不支持对于英文标点符号的识别？
后尝试动态的加入对英文标点符号的识别UserDefineLibrary.insertWord(",", "w", 1000);，但是在实际测试时候依然识别不出标点符号，请问是否有什么方法可以在分词中增加对于英文标点符号的识别？

**Comment by ansjsun** [comment]
这个算是我词典中的一个错误。在核心词典中就错了。。后期用户词典可以做覆盖。不过需要。。多一些操作。。关于5.0中FilterModifWord方法的问题 #290

**Comment by xiabiyu** [comment]
谢谢。解决了 :-D
