### ISSUE TITLE
怎么去掉分词结果后的标识

### ISSUE THREAD

**Issue by willduan** [NLPchina/ansj_seg#308]
例如分词之后结果为：
欢迎/v,使用/v,ansj/en,_,seg/en,,,(,ansj/en,中文/nz,分词/n,),在/p,这里/r,如果/c,你/r,遇到/v,什么/r,问题/n

后面有很多的 /v /en啊等等，我项目里面不需要这些，最后的结果只想要实现如下：
欢迎  使用  ansj  seg  (ansj  中文  分词  )  在   这里 如果   你   遇到   什么   问题
结果如上，
1 .  最后只想要分词结果，分词直接用空格分开，不需要后面的标识，想请教一下应该如何实现，我找了一圈没有详细的使用文档，最后倒是输出到文件问答里面您给解答了
2.  还有就是文档或者用户手册目前好像还没有，想请问一下如何加入编写手册的团队，有没有qq群之类的

谢谢您百忙之中给予解答(^-^)

**Comment by ansjsun** [comment]
如果你用的5.0的分词可以通过

````
ToAnalysis.parse("分词结果！").toStringWithOutNature()
````

**Comment by ansjsun** [comment]
历史终将不了了之
