### ISSUE TITLE
数字字母连续串的切分粒度问题

### ISSUE THREAD

**Issue by QA-long** [NLPchina/ansj_seg#309]
楼主你好，我用Ansj分词 例如“1、熟练掌握java、J2EE系统开发，精通SSH等框架，有过接口平台设计经验者优先。”

对于 “J2EE” “SL4J”这种由字母数字组合的名词都被拆分成开了 变成了“J/EE SL/J” 有什么办法解决吗？

同 已关闭的问题：https://github.com/NLPchina/ansj_seg/issues/100

**Comment by ansjsun** [comment]
在用户自定义词典中增加j2ee(必须小写)就可以了.

**Comment by ansjsun** [comment]
历史终将不了了之
