### ISSUE TITLE
发现全文分词和分段落分词差异较大

### ISSUE THREAD

**Issue by edhn3000** [NLPchina/ansj_seg#310]
试了一下nlp分词对于人名的识别，分词处理对传入文本用了3种方式：全文分词、分段落（按回车分段）分词、分句子（按句号或回车）分词效果都不太一样
有时全文分词不如分段落分词对人名提的准，也有时反过来， 后两种方式虽有差异但不大；
比如全文分词“出生于鹿寨县”，分成“出生/v,于鹿寨/nr,县/n”，分段处理就可以正确“出生/v,于/p,鹿寨县/nw”；全文分词“李四的女儿张三因其父xx”，分成“张三因/nr”（多因），分段处理可以正确；
另外，分段分词的一个错误“理由同郑旭”，分成“同郑旭/nr”（多原）全文分词可以正确
想请教一下，做人名识别时怎么用比较好？比如应该传入多长的文本，是全文还是分段落、还是其他方式，还是其他原因影响的？

**Comment by ansjsun** [comment]
试试nlpanalysis 或者dicanalysis吧。。toanalysis的人名识别。。有问题。。正在谋划重做

**Comment by edhn3000** [comment]
用的是nlpanalysis不是toanalysis，至于dicanalysis是字典优先吧，没有自定义词词典时是不是没啥特殊？

**Comment by ansjsun** [comment]
你的分词版本是？我在5.0貌似比较正常

**Comment by edhn3000** [comment]
是5.0，发现粒度控制在以句子为单位，分词效果比整个段落、或直接传入全篇文档效果要好些，往往分词较准。
