### ISSUE TITLE
关于自定义词典优先级问题

### ISSUE THREAD

**Issue by wei-yao** [NLPchina/ansj_seg#316]
5.0_使用 DicAnalysis , 用户自定义的词典优先级一定最高吗?
之前使用3.7 ToAnalysis 并不一定按照用户自定义词典中的条目来分，就使用了ambiguity作词典

现在想用DicAnalysis, 不知道还有没有以前的问题

**Comment by ansjsun** [comment]
应该么有你可以试试..

**Comment by wei-yao** [comment]
非常感谢,昨天试了一下,可以
