### ISSUE TITLE
NlpAnalysis分词，可以关掉新词发现功能吗？

### ISSUE THREAD

**Issue by flystarhe** [NLPchina/ansj_seg#317]
NlpAnalysis分词会合并出类似“四川省成都市青羊区江汉路/nw”的新词，应用中希望能得到其中地名的识别，如“四川省 成都市 青羊区 江汉路”。请问有办法阻止这种合并吗？
这种合并会导致后续学习的特征增加太多。

**Comment by ansjsun** [comment]
那就用dicanalysis 或者 toanalysis来做..

**Comment by flystarhe** [comment]
thx，现在用Dic来做的，不过遗憾的是Nlp对于“xx路”这种未登录词切分更准一些
