### ISSUE TITLE
多台服务器词典如何同步

### ISSUE THREAD

**Issue by JasonHuangHe** [NLPchina/ansj_seg#319]
我有多个服务器，每个服务器的tomcat启动的时候，加载用户自定义词典，通过页面新增用户词典后，其他服务器的词典如何同步呢？只能使用中间件之类的技术通知吗？

**Comment by ansjsun** [comment]
除非你把分词做成服务的形式.缺点是这样速度会有损失..

**Comment by ansjsun** [comment]
历史终将不了了之
