### ISSUE TITLE
更新一下maven中央库里面的版本嘛

### ISSUE THREAD

**Issue by wendal** [NLPchina/ansj_seg#320]
至今还是0.9啊

**Comment by ansjsun** [comment]
maven 库的用户名密码忘记了..找回邮件总发送不到....还有我的jar包貌似超过maven库单个文件大小的限制了...于是乎.....自己搞了....哎....放一个 response 头也不是那么麻烦的事情是吧 ....

**Comment by dblinkin** [comment]
@ansjsun 同求maven中央库更新， 是否可以将代码打jar包， 字典库使用的时候由使用者重新下载

**Comment by ansjsun** [comment]
中央仓库我回头想想办法..
分词的jar包可以从这里下载http://maven.nlpcn.org/org/ansj/ansj_seg/

**Comment by wendal** [comment]
要不放在 jcenter
https://bintray.com/

http://maven.nlpcn.org 这个地址, travis-ci构建的时候几乎每次都timeout

**Comment by ansjsun** [comment]
用这个吧  http://maven.ansj.org/   我发的此时还不行.还在同步中全同步完估计得1个小时后

jcenter我回头学习下.....

话说nutz搞一个中国的maven库吧...群里都900人了.一人10块钱就够一年了...

**Comment by ansjsun** [comment]
历史终将不了了之

**Comment by wendal** [comment]
@ansjsun 已经有了 https://jfrog.nutz.cn/artifactory/webapp/#/home
