### ISSUE TITLE
希望CRF模型的加载和标注能做成通用的

### ISSUE THREAD

**Issue by liulhdarks** [NLPchina/ansj_seg#321]
希望CRF模型的加载和标注能做成通用的，现在是为分词写死的，如果能通用化，就可以灵活的用到其他地方了。

**Comment by ansjsun** [comment]
很好的建议,为了保证调用速度.和简单保证训练和调用方式一致.做的选择..后期也许会想办法支持任意模型...

**Comment by ansjsun** [comment]
历史终将不了了之
