### ISSUE TITLE
ambiguity.dic没有作用？？？

### ISSUE THREAD

**Issue by bks-git** [NLPchina/ansj_seg#322]
我使用的是ansj_seg-3.7.5-all-in-one.jar的DicAnalysis分词

待分词的串：”我对这个头衔并不满意。“   vs  “我对这个头衔并不满意”

两句话只差一个句号，但是分词结果相差很大

[我/rr, 对/p, 这个/rz, 头衔/n, 并不/d, 满意/vn, 。/w]   vs   [我/rr, 对/p, 这个/rz, 头衔/n, 并/cc, 不满/an, 意/ng]

然后我在ambiguity.dic中添加了如下条目：
不满意   不 d   满意  vn

但是分词结果依然如上。有请大神分析：

1.为什么差一个句号，分词结果哈别这么大？
2.为什么ambiguity.dic没有发挥作用？

非常感谢！

**Comment by ansjsun** [comment]
ambiguity的格式发生改变。不需要写前面了
直接写
````
不 d 满意 vn
````

都是tab隔开。。具体看
https://github.com/NLPchina/ansj_seg/blob/master/library/ambiguity.dic

**Comment by bks-git** [comment]
首先真诚感谢解答！

1.更改ambiguity.dic的格式之后依然存在上面描述的问题（使用ansj_seg-5.0.1-all-in-one.jar的DicAnalysis分词）
2.为什么相差一个句号，分词的结果差别这么大？

谢谢，祝好！

**Comment by ansjsun** [comment]
历史终将不了了之
