### ISSUE TITLE
我是小白，请问下NER的例子在哪？

### ISSUE THREAD

**Issue by guotong1988** [NLPchina/ansj_seg#326]
多谢！！
是不是还要用 斯坦福CoreNLP 一起来做？

**Comment by ansjsun** [comment]
这 个 https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/demo/NlpDemo.java

里面都是demo...

**Comment by ansjsun** [comment]
历史终将不了了之
