### ISSUE TITLE
ansj分词不稳定的问题

### ISSUE THREAD

**Issue by libenyang** [NLPchina/ansj_seg#328]
使用ansj发现一个问题，当一句话，上下文多个空格，或者其他的无关字符，分词的变化很大，index，和query都是如此，可能会在搜索中带来召回的问题，3.x的版本我测是5%左右的比例，还不小，希望能修复:)

**Comment by ansjsun** [comment]
你好可以提供一些badcase吗我好有针对性修复

发自我的 iPhone

**Comment by libenyang** [comment]
吴 进 
  吴进   
index_size:3diffnum:1
陈 欣慰 
  陈欣慰   欣慰 
index_size:4diffnum:1
赵树 达 
  赵树达   
index_size:3diffnum:1
彭 建国 
  彭建国   建国 
index_size:4diffnum:1
贺静 中 
  贺静中   
index_size:3diffnum:1
易 中华 
  易中华   中华 
index_size:4diffnum:1
王东 建 东建 
  王东建   王东 东建 
index_size:5diffnum:1
张广 财 
  张广财   张广 
index_size:4diffnum:1
类 延 民 
  类 延民   
index_size:4diffnum:1
冶 富 荣 
  冶 富荣   
index_size:4diffnum:1
张 金 合 
  张金合   
index_size:3diffnum:1
孙 雪 
  孙雪   
index_size:3diffnum:1
王海燕 王海 海燕 
  王 海燕   王海 
index_size:5diffnum:1
楚 新 
  楚新   
index_size:3diffnum:1
姚满 中 
  姚满中   
index_size:3diffnum:1
温 成本 
  温成本   成本 
index_size:4diffnum:1
马 进 
  马进

**Comment by zhiyousanqian** [comment]
我这边有个例子  对"孟可胡歌"和"孟可 胡歌"进行切分一下试试。前面的会切成“孟可胡 歌”

**Comment by ansjsun** [comment]
用dicanalysis 效果可能会好一些

**Comment by zhiyousanqian** [comment]
dicanalysis是新版本加上的吗。我再3.x版本里面发现了UserDefineAnalysis 这个。感谢大神的回复。我是ansj的忠实用户

**Comment by ansjsun** [comment]
@zhiyousanqian  是的加了有一段时间了..dicanalysis是词典优先的策略....你估计用的版本够旧的... UserDefineAnalysis 更名为DicAnalysis了...之前名称太长了..你可以下载3.7.5的最后一个版本.或者用5.x

http://maven.nlpcn.org/org/ansj/ansj_seg/

**Comment by zhiyousanqian** [comment]
多谢了，有问题我再反馈。

**Comment by libenyang** [comment]
@ansjsun 例子发了哈，这只是一部分例子，不知道5.0.1稳定性是否好一些，

**Comment by ansjsun** [comment]
目前5.0.1估计还是有这些问题..但是dicanalysis稳定性很强..下一步打算重构人名识别和核心词典稳定性应该会好很多

**Comment by ansjsun** [comment]
历史终将不了了之
