### ISSUE TITLE
分词index分词，es使用phrase问题

### ISSUE THREAD

**Issue by libenyang** [NLPchina/ansj_seg#329]
index分词尽量将多个粒度都分出来，增大召回，但是有一个问题，es是按pos来判断phrase的，所以在某些情况下ansj词，临近的词没有放在临近的位置上。可能会判断失误。对于这种重叠的分词，似乎没办法100%解决这个问题。
测试
pos: 0 start: 0 end: 2
上网人
pos: 1 start: 2 end: 5
上网
pos: 2 start: 2 end: 4
网人
pos: 3 start: 3 end: 5
人员
pos: 4 start: 4 end: 6
零零
pos: 5 start: 6 end: 8

**Comment by ansjsun** [comment]
用 indexanalysis 来做phrase ..可以做到全匹配查询

**Comment by libenyang** [comment]
这也可能做不到，比如这个例子，query如果是"上网人员"，使用index分词将被分成，如下的词
4
|上网|pos:0|start:0|end:2
|人员|pos:1|start:2|end:4
|上网人|pos:2|start:0|end:3
|网人|pos:3|start:1|end:3
会发现，和索引句子的顺序相差甚远，是无法用phrase匹配到的

**Comment by ansjsun** [comment]
你可以试试...一定要用index方式做query事可以的...应为顺序不变.搜索结果也是完全匹配的

**Comment by chenjinyuan87** [comment]
按他的例子，例如原文是
上网人员测试
则分词结果是：
上网 人 上网 网人 人员? 测试 //这里会出来人员?5.0的index改进了么。。我一直用的自己重写的index
这时候phrase查询 上网人员测试 就会出错了
人员和测试隔了两个词
lucene有posincremental=0的做法
我目前还没测试如果这么干会发生什么？

**Comment by ansjsun** [comment]
应该是可以了..3.x的最后几个版本..已经把顺序调整了

**Comment by ansjsun** [comment]
现在改成这样了
````
上网人 上网 上 网人 网 人员 人 员 测试 测 试
````

**Comment by chenjinyuan87** [comment]
不行吧？假设查询时，分词是上网 人员 测试
那么上网的pos是2
人员的pos是5
测试的pos是8
一般即使放宽条件，slop也就是1啊，这都到3了
事实上我一直觉得这根本就不是分词器能解决的问题。。

**Comment by chenjinyuan87** [comment]
如果非要解决，那应该是采用各种不同的策略把全文存N遍。
例如这里，要存成
上网人/员/测试
上网人/员/测/试
上网/人员/测试
上 网人 员 测试
...
排列组合下来还有无数种分法

**Comment by ansjsun** [comment]
你试试就知道了 实践出真知 不过会有这种情况 旅游和服务。你搜索和服是没有结果的 具体原因 你猜

发自我的 iPhone

**Comment by chenjinyuan87** [comment]
那我就给你实践吧：
以下是代码：
        UserDefineLibrary.insertWord("上网人");
        UserDefineLibrary.insertWord("网人");
        AnsjAnalyzer ansjAnalyzer = new AnsjAnalyzer(AnsjAnalyzer.TYPE.index);
        TokenStream tokenStream = ansjAnalyzer.tokenStream("上网人员测试", "test");
        while (tokenStream.incrementToken()) {
            System.out.println(tokenStream.getAttribute(CharTermAttribute.class));
        }
        IndexWriterConfig config = new IndexWriterConfig(ansjAnalyzer);
        IndexWriter writer = new IndexWriter(new RAMDirectory(), config);
        Document doc = new Document();
        doc.add(new TextField("test", "上网人员测试", Field.Store.YES));
        writer.addDocument(doc);
        writer.commit();
        IndexSearcher searcher = new IndexSearcher(DirectoryReader.open(writer));
        System.out.println(searcher.count(new TermQuery(new Term("test", "网人"))));
        Query q = new QueryParser("test", new AnsjAnalyzer(AnsjAnalyzer.TYPE.query)).parse("\"上网人员测试\"");
        System.out.println(q);
        System.out.println(searcher.count(q));

以下是输出：
上网人
上网
网人
人员
测试
1
test:"上网 人员 测试"
0

**Comment by ansjsun** [comment]
@chenjinyuan87 
````
UserDefineLibrary.insertWord("上网人");
		UserDefineLibrary.insertWord("网人");
		AnsjAnalyzer ansjAnalyzer = new AnsjAnalyzer(AnsjAnalyzer.TYPE.index);
		TokenStream tokenStream = ansjAnalyzer.tokenStream("上网人员测试", "test");
		while (tokenStream.incrementToken()) {
			System.out.println(tokenStream.getAttribute(CharTermAttribute.class));
		}
		IndexWriterConfig config = new IndexWriterConfig(ansjAnalyzer);
		IndexWriter writer = new IndexWriter(new RAMDirectory(), config);
		Document doc = new Document();
		doc.add(new TextField("test", "上网人员测试", Field.Store.YES));
		writer.addDocument(doc);
		writer.commit();
		IndexSearcher searcher = new IndexSearcher(DirectoryReader.open(writer));
		System.out.println(searcher.count(new TermQuery(new Term("test", "网人"))));
		Query q = new QueryParser("test", new AnsjAnalyzer(AnsjAnalyzer.TYPE.index)).parse("\"上网人员测试\"");
		System.out.println(q);
		System.out.println(searcher.count(q));
````

`Query q = new QueryParser("test", new AnsjAnalyzer(AnsjAnalyzer.TYPE.query)).parse("\"上网人员测试\"");`
这句也得用index方式分词哦.改成

`Query q = new QueryParser("test", new AnsjAnalyzer(AnsjAnalyzer.TYPE.index)).parse("\"上网人员测试\"");`

我这里的结果是

````
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
上网人
上网
网人
人员
测试
1
test:"上网人 上网 网人 人员 测试"
1

````

不过这种方式的确有时候无法找回比如

比如如果只搜索.`上网人 `是无法找回的..应为`人`和`人员`是两回事...这个地方无法解决..但是你搜索`上网人员` 是可以召回的

**Comment by chenjinyuan87** [comment]
用index分词时，搜索的phrase事实上不是真实意图，虽然结果是正确的，但并不可取。

因为这样做只适合phrase，如果是普通的搜索，用index分词进行搜索就会返回一堆无关的结果。而且在es里面基本上都指定搜索时的分词器是query了。

**Comment by ansjsun** [comment]
的确是index方式失去了消歧的功能...

我现在的做法是  两个分词器配合  临近用index + query term的方式来搜索...虽然可能有错误召回..但是都放的很后了...

当然看业需求..只用query做索引和搜索也是可以的...但是用户自定义词典的要求很高...把合成词都去掉

**Comment by chenjinyuan87** [comment]
是啊，总之是不完美的解决办法。。

**Comment by libenyang** [comment]
看完了几位的留言，我也是抛出这一个问题，未想到完美的解决方案，本质上讲是重叠分词导致的，想召回全部的可能结果，使用phrase是不可能的，如果能保证query粒度都是近邻在一起，能解决绝大多数问题，

**Comment by ansjsun** [comment]
@libenyang index在query分词的后面又增加的其他粒度分词,是最早的一个方案...

也是可行的...那样用query就可以做phrase查询了..缺点是高亮无法工作了..所以改成目前的方式..

**Comment by libenyang** [comment]
@ansjsun 哦原来如此，高亮的工作原理不是很了解，能否简单跟我说一下无效的原因

**Comment by ansjsun** [comment]
高亮无效..可能是在读取文本的时候我丢了\r 这类字符...后面重写bufferedreader现在貌似好一些额...

**Comment by libenyang** [comment]
@ansjsun 我找到了高亮有问题的原因，这篇文章说的比较详细http://blog.csdn.net/xiao_jun_0820/article/details/50515350
还是觉得应该保证：
index和query都使用query粒度分词，没有重叠；index细粒度分词在query分词的后面又增加的其他粒度分词
这样能最大限度的使用phrase

针对高亮问题只需对细粒度的分词，的start end的位置做一些改动，这样虽不符合实际，但在搜索中也没有其他的使用场景了

**Comment by ansjsun** [comment]
这个已经解决了把

**Comment by libenyang** [comment]
@ansjsun 恩，目前是不会出错，"上网人 上网 网人 人员 测试"，结果是这样，但是phrase基本也没法用了，除非全匹配，不然"上网人员"就搜不到结果了，所以我觉得原来的方式更好，只是修改重叠部分分词的start位置。
ps:我测的是5.0.0版本

**Comment by ansjsun** [comment]
用最新的版本试试...应该已经修复了这个bug
