### ISSUE TITLE
crf关键词提取功能

### ISSUE THREAD

**Issue by jie147** [NLPchina/ansj_seg#335]
ansj中有crf关键词提取功能吗？

**Comment by ansjsun** [comment]
关键词提取不是用的crf算法..

**Comment by jie147** [comment]
恩，我看你的源码是用tf-idf算法，ansj中crf只是用在了分词对吧，我的老师非常确定的说ansj中有crf关键词提取功能，我都无语了。。。

**Comment by ansjsun** [comment]
@jie147 我觉得你们老师说的没错..是我错了...

关键词权重用的tf-idf, 但是在关键词抽取上..和初始分值上..是用了crf来计算分数的.

关键词提取.很重要的一步就是..未登录词语的识别.

**Comment by jie147** [comment]
恩，我明白你的意思了。

**Comment by ansjsun** [comment]
历史终将不了了之
