### ISSUE TITLE
无法按词典进行英文分词

### ISSUE THREAD

**Issue by gaohuitang** [NLPchina/ansj_seg#336]
您好，孙大哥，请问在分词时，无法按照自定词典对英文文本进行正确分词，情况如下
例如：
  自定义词库：sqlserver
  分词文本：mssqlserver
 调用DicAnalysis.parse( ) ，
 分词结果mssqlserver。而不是sqlserver？
  请问该如何解决？谢谢！

**Comment by ansjsun** [comment]
你好英文单词是一个个体，所以不会被拆开 你得 ms sqlserver 才有可能

**Comment by gaohuitang** [comment]
哦哦，原来是这样，多谢！

**Comment by gaohuitang** [comment]
孙大哥，请问在提取关键词时，同时过滤掉停用词该如何操作？

**Comment by ansjsun** [comment]
多提几个自己过滤吧

发自我的 iPhone

**Comment by ansjsun** [comment]
历史终将不了了之
