### ISSUE TITLE
crf训练的语料是针对版本的问题

### ISSUE THREAD

**Issue by moshangshaoguang** [NLPchina/ansj_seg#337]
训练出的语料是针对5.0.1版本的的还是通用的

**Comment by moshangshaoguang** [comment]
本人是小白，求指点一下，怎么训练出自己想要的语料 例如：上海味丹企业有限公司   经过语料训练成
上海味丹企业有限公司/nt  去调用 NlpAnalysis.parse("上海味丹企业有限公司"),最后显示的结果为上海味丹企业有限公司/nt

**Comment by ansjsun** [comment]
5.x之后是通用的

merge to #342
