### ISSUE TITLE
mavan中央库的ansj_lucene4_plug不可用

### ISSUE THREAD

**Issue by wendal** [NLPchina/ansj_seg#341]
原因是ansj_lucene4_plug的pom.xml引用了ansj_plugin, 然后ansj_plugin又没有上传到中央库, 依赖链就这样挂了

**Comment by ansjsun** [comment]
昏..怪我没试..

现在发布了个

https://oss.sonatype.org/content/groups/public/org/ansj/ansj_plugin/


你看看这样是否可以了..刚发布..我这里测试还是有错..可能没同步呢吧...

**Comment by ansjsun** [comment]
我试了下.需要删掉.本地以加载的错误.然后重新update maven 就可以了我关了 啊....
