### ISSUE TITLE
“上海虹桥机场”用IndexAnalysis分词没分出来“虹桥机场”

### ISSUE THREAD

**Issue by konghuarukhr** [NLPchina/ansj_seg#343]
ansj版本5.0.1

用的wiki里面的示例程序，和wiki里面提到的“上海虹桥机场”这个词，分词结果：
BaseAnalysis：上海/ns,虹桥/ns,机场/n
ToAnalysis：上海/ns,虹桥/ns,机场/n
DicAnalysis：上海/ns,虹桥/ns,机场/n
IndexAnalysis：上海/ns,虹桥/ns,机场/n

IndexAnalysis模式下，不是应该分出来“虹桥机场”的吗？

我尝试了许多文本，感觉IndexAnalysis模式和BaseAnalysis的分词结果基本一致，和ToAnalysis几乎完全一致。

分“洁面仪配合洁面深层清洁毛孔 清洁鼻孔面膜碎觉使劲挤才能出一点点皱纹 脸颊毛孔修复的看不见啦 草莓鼻历史遗留问题没辙 脸和脖子差不多颜色的皮肤才是健康的 长期使用安全健康的比同龄人显小五到十岁 28岁的妹子看看你们的鱼尾纹”这个wiki里面的句子，我的测试结果和wiki里面说的，出入也很大。

**Comment by ansjsun** [comment]
没有加载用户自定义词典导致..看日志有提示..在某个路径找不到用户自定义词典.

**Comment by konghuarukhr** [comment]
@ansjsun 谢谢你。
我还是不太理解。ansj不是自带了词典吗？一定需要添加用户自定义词典，才能实现IndexAnalysis的效果？

**Comment by konghuarukhr** [comment]
ansj自带的词典是library/default.dic还是src/main/resources/core.dic啊？我从maven下载下来的jar包里面貌似没找到项目里面的library/default.dic这个文件，莫非我想用这个词典的话，需要我手动指定么？

**Comment by ansjsun** [comment]
简单来说。。

来这里 下载 

https://github.com/NLPchina/ansj_seg/tree/master/library


或者来这里

http://maven.nlpcn.org/down/library/default.dic

放到你项目根目录 library/default.dic 然后就可以了

**Comment by konghuarukhr** [comment]
谢谢。
加上default.dic之后，没问题了。

也就是说，要正确使用ansj的IndexAnalysis分词模式，不仅仅要在项目里面添加maven依赖，还需要添加一个额外下载的词典。ansj的jar包里，实际上带有一个叫core.dic的词典，并且该词典含有“杀人不眨眼”，“杀人”，“眨眼”这三个词，如果不添加额外的词典，IndexAnalysis对“杀人不眨眼”分词也分不出来“杀人”和“眨眼”。

这个行为和别的分词器好像很不一样，如果wiki里面说明一下这点就好了。

**Comment by JerryChin** [comment]
遇到一模一样的问题，花了10个小时终于根据上面的讨论解决了。
