### ISSUE TITLE
自定义词库好像不生效

### ISSUE THREAD

**Issue by LPQingFeiDeYi** [NLPchina/ansj_seg#344]
UserDefineLibrary.loadLibrary(new Forest(), "library/myDic.dic"); //新都化工
System.out.println(UserDefineLibrary.contains("新都化工"));  //false

请问我这这种定义方式有问题么？

**Comment by ansjsun** [comment]
#338  看这个

**Comment by ansjsun** [comment]
额。。你这个问题 。。我需要看看你myDIc.dic的词典格式 。。

词语[TAB]词性[TAB]词频

utf-8的文本。。去掉bom头。不能用win记事本编辑切记

**Comment by LPQingFeiDeYi** [comment]
谢谢，new Forest() 改为 UserDefineLibrary.FOREST可以了
