### ISSUE TITLE
“旅游和服务”在IndexAnalysis模式下分出来“和服”

### ISSUE THREAD

**Issue by konghuarukhr** [NLPchina/ansj_seg#345]
wiki里面解释IndexAnalysis面向索引分词时这么说：

> 比如我们常见的歧义句“旅游和服务”->对于一般保证召回 。大家会给出的结果是“旅游 和服 服务” 对于       ansj不存在跨term的分词。意思就是。召回的词只是针对精准分词之后的结果的一个细分。

我项目里面加载了default.dic。
IndexAnalysis模式切分“旅游和服务”的时候，结果是“旅游/vn,旅/vg,游/v,和服/n,和/c,服务/vn,服/v,务/vg”。

怎么“和服”也出来了？而且每个单字也切出来了。我哪里用的不对吗？

**Comment by ansjsun** [comment]
wiki旧了 现在策略改了


发自我的 iPhone

**Comment by konghuarukhr** [comment]
@ansjsun 
请问一下，最后一个支持那个特性的版本是哪个？
我做索引时希望用那种方式分词。。谢谢。

**Comment by ansjsun** [comment]
还是用index方式吧召回重要一些
