### ISSUE TITLE
ansj_seg 在自定义hive函数中不能正常使用

### ISSUE THREAD

**Issue by madong-fun** [NLPchina/ansj_seg#347]
今天在hive自定义函数在中调用了分词，不知道为什么不能正常使用自定义分词，本地测试方法是正常的。

`    /**
     \* 根据给定地址，分词，返回自定义分词
     \* @param word
     \* @return
     */
    public  List<String> analysis(String word){

```
    Result result = DicAnalysis.parse(word);
    List<Term> termList =result.getTerms();
    System.out.println(result);
    logger.info("analysis result is {}.",result);
    Term term;
    List<String> list = new ArrayList<String>();
    for (int i = 0; i <termList.size(); i++) {
        term = termList.get(i);
        if (term.getNatureStr().equalsIgnoreCase("userDefine")){
            list.add(term.getRealName());
        }
    }

    return list;

}`
```

**Comment by ansjsun** [comment]
抱歉我没在hadoop环境用过这个.但是我想用这个需要把相关jar.扔到hadoop环境才可以把...不知道报什么err

**Comment by madong-fun** [comment]
不知道为什么，就是读取不到 自定义词典！没有什么错误！

**Comment by madong-fun** [comment]
`2016-09-10T14:15:37,357 WARN  [main]: DICLOG (:()) - file in path /usr/local/hive/file:/data/workspace-java/flow.data.analysis/target/flow-analysis-jar-with-dependencies.jar!/library/default.dic can not to read!
2016-09-10T14:15:37,357 WARN  [main]: DICLOG (:()) - file in path /usr/local/hive/file:/data/workspace-java/flow.data.analysis/target/flow-analysis-jar-with-dependencies.jar!/library/default.dic can not to read!
2016-09-10T14:15:37,358 WARN  [main]: DICLOG (:()) - file in path /usr/local/hive/file:/data/workspace-java/flow.data.analysis/target/flow-analysis-jar-with-dependencies.jar!/library/default.dic can not to read!
`

周末终于有闲暇去捣鼓这个问题，在自己的测试机发现了原因，如上日志。我要运行的jar没有放在hive的安装目录下，根据UserDefineLibrary.loadLibrary()中的源码看，UserDefineLibrary.class.getClassLoader().getResource(path)获取file路径，却不知为何定位到hive的安装目录，这个或许是hive的运行机制导致的。以前也运行过类似的例子，不过当时为了方便都放到了hive目录下，这次因为在公司预发环境，所以没有这做，才出现了这个问题！幸好，找到原因了！

**Comment by ansjsun** [comment]
历史终将不了了之
