### ISSUE TITLE
关于语料训练的问题

### ISSUE THREAD

**Issue by moshangshaoguang** [NLPchina/ansj_seg#351]
在你写得为wiki里只是介绍怎么去训练语料，使用训练的语料后对结果看不出有什么区别，能不能麻烦把这方面的有关介绍一下呢。

**Comment by ansjsun** [comment]
最近实在太忙..如果我闲下来整理下.不知道为嘛..现在那个case我也过不去了....汗颜啊

**Comment by gaohuitang** [comment]
我也有同样的困惑，加载自己的训练模型分词与不加载有什么区别呢？

**Comment by moshangshaoguang** [comment]
请问一下现在问题解决了吗
