### ISSUE TITLE
5.0.2版分词粒度太粗

### ISSUE THREAD

**Issue by lijiajia** [NLPchina/ansj_seg#352]
最新5.0.2版本分词粒度太粗了，比如我分“关台灯”和“关床头灯”，希望结果是“关/台灯”和“关/床头灯”，实际分出来的结果是“关台灯”和“关床头灯”，请问有什么解决办法吗

**Comment by ansjsun** [comment]
不要用 nlpanalysis

**Comment by lijiajia** [comment]
已经解决了，用ToAnalysis可以
