### ISSUE TITLE
同义词分词

### ISSUE THREAD

**Issue by madong-fun** [NLPchina/ansj_seg#354]
我认为同义词分词的结果应该是这样的：

`String content = "北京大兴亦庄经济开发区南海家园二里";`
北京/ns,大兴/ns,亦/d,庄/ag,经济/n,开发区/n,南海家园/userDefine[南海家园,南海家园一里,南海家园二里]

貌似最近合并到主线的同义词分词并不能提供这样的效果

**Comment by ansjsun** [comment]
are you sure?我是按照你的提交合并的呀

**Comment by ansjsun** [comment]
历史终将不了了之
