### ISSUE TITLE
是否可以先设置停用词和用户词库

### ISSUE THREAD

**Issue by Blusea** [NLPchina/ansj_seg#356]
`def initFilter={
    val filter = new FilterRecognition
    filter.insertStopNatures("w","null","ns","r","u","e") // 加入停用词性
    val stopwords = List("的","了","地","哈","啊")   // 加入停用词
    filter.insertStopWords(stopwords)
    // 用户字典加载
    UserDefineLibrary.loadFile(UserDefineLibrary.FOREST,new File("library/UserDefineLibrary.txt"))
    //TODO
    filter
  }` 
`def SegAndDeletUntoken(line:String)={
    ToAnalysis.parse(line).recognition(initFilter).getTerms().map(_.toString)
  }`
每次执行SegAndDeletUntoken都需要加载一次用户字典，能不能生成分词器实例只加载一次？

**Comment by ansjsun** [comment]
这个就是加载一次多次使用啊 是不是你调用的方式有问题

发自我的 iPhone
