### ISSUE TITLE
新的词性列表以及...文档未更新问题

### ISSUE THREAD

**Issue by x11819130** [NLPchina/ansj_seg#357]
WIKI最后有个词性标注规范,但那个应该是以前的了,不知道新的词性标注规范哪里可以看到,新的词性应该是49个是吗?
还有...WIKI应该没有更新了,像<新词发现小工具>那章
NlpAnalysis.parse("张艺谋的卡宴，马明哲的戏",learnTool) ;
5.02里这个方法改掉了是吗?
其实最想问的是自定义词库,自定义词库是怎么生成的?自定义词库的词性必须是那49个吗?还有core.dic里每一列代表什么?
新人新上路,求带.

**Comment by ansjsun** [comment]
新的调用方式在这里 
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/demo/NlpDemo.java


词性是比较随便的内置的是文档..然后用户可以自己拓展..


core.dic里面是DAT格式.具体百度双数组tire数

**Comment by 9vivian88** [comment]
词性列表有么？RW.RWPersonSingle是什么意思。有越细粒度的列表越好。
