### ISSUE TITLE
crf模型训练语料有何作用？

### ISSUE THREAD

**Issue by gaohuitang** [NLPchina/ansj_seg#359]
孙大哥好，关于CRF训练模型，我想请教两个问题。
      1、使用crf训练自己的语料，再加载训练好的模型（model.txt）分词，分词结果与不加载模型（model.txt）有什么区别呢？
      2、加入我训练的预料库中多次出现“呼叫中心”一词，后期加载该训练模型分词，会不会把“呼叫中心”作为一个词？不再将其分成“呼叫” 和 “中心”两个词了。

**Comment by ansjsun** [comment]
1.crf能提高未登录词的找回。但是稳定性稍差。
2除非配置歧义词典否则无法再分开了。
