### ISSUE TITLE
为什么自定义词典和DAT要分开分词？

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#361]
我发现自定义词典是在graph里进行分词的，这时候已经根据DAT分过一遍了。为什么不把两个词典合并到一起分词呢？我觉得这样做应该更合理一些

发现这个问题主要是因为有些英文人名被标记成en了，而我的自定义词典里面有这个人。
例如：
自定义词典里面：
angelababy  nr
最后分词结果是： 
angelababy en

代码就这样：
        UserDefineLibrary.insertWord("angelababy", "nr", 1000);
        System.out.println(ToAnalysis.parse("angelababy"));

**Comment by ansjsun** [comment]
NlpAnalysis.parse("结婚的和尚未结婚的孙建是一个好人").recognition(new NatureRecognition())

参见

https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/recognition/impl/NatureRecognitionTest.java


以用户自定义词典优先

**Comment by chenjinyuan87** [comment]
实际上我就没有用过naturerecognition啊。。。。因为我发现用了词性还是不怎么对，干脆就直接用所有词性了

**Comment by syncml** [comment]
我也遇到过这个问题

**Comment by ansjsun** [comment]
历史终将不了了之
