### ISSUE TITLE
ansj5.0 用户自定义词典 如何配置

### ISSUE THREAD

**Issue by bsb5142332** [NLPchina/ansj_seg#365]
求教ansj5.0之后如何配置用户自定义词典，只能通过手动load吗？
1、文档中没有交代。“注意5.0.x以后的版本应按如下操作”下面为空白
2、MyStaticValue也没有userLibrary，如何实现反射赋值？

**Comment by shi-yuan** [comment]
···java
MyStaticValue.DIC.put(MyStaticValue.DIC_DEFAULT, userLibraryPath);
···
