### ISSUE TITLE
两次分词结果不一样？

### ISSUE THREAD

**Issue by sandyfog** [NLPchina/ansj_seg#366]
使用ToAnalysis分别用“三星”和“三星电子”进行分词的时候，得到下面结果：
三/m,星/n
三星/nz,电子/n
为什么单独分词三星被拆分了，而三星电子没有拆分？

**Comment by ansjsun** [comment]
你三星没放到自定义词典中。。。。

拆不拆是依据上下文决定的

**Comment by ansjsun** [comment]
历史终将不了了之
