### ISSUE TITLE
1234567在词典里面的词性居然是nb！

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#367]
att
这是为什么？
46	.	65536	-1	5	{nb=1}
48	0	65536	-1	5	{nb=1}
49	1	65536	-1	5	{nb=1}
50	2	65536	-1	5	{nb=1}
51	3	65536	-1	5	{nb=1}
52	4	65536	-1	5	{nb=1}
53	5	65536	-1	5	{nb=1}
54	6	65536	-1	5	{nb=1}
55	7	65536	-1	5	{nb=1}
56	8	65536	-1	5	{nb=1}
57	9	65536	-1	5	{nb=1}

**Comment by ansjsun** [comment]
牛逼么

**Comment by ansjsun** [comment]
历史终将不了了之
