### ISSUE TITLE
自定义字典不生效

### ISSUE THREAD

**Issue by taoyufan** [NLPchina/ansj_seg#369]
代码如下：
UserDefineLibrary.insertWord("拱墅区", "userDefine", 1000);
String text = "杭州市拱墅区嘉绿景苑东园3单元";
Result terms = ToAnalysis.parse(text);
System.out.println(terms);
//结果： 杭州市/ns,拱/v,墅/x,区嘉绿/nr,景苑东/nr,园/ng,3/m,单元/n
自定义的字典没有生效，请教我该如何做？

**Comment by taoyufan** [comment]
使用DicAnalysis是可以的

**Comment by ansjsun** [comment]
用Dicanalysis.parser

发自我的 iPhone
