### ISSUE TITLE
lucene插件和同义词

### ISSUE THREAD

**Issue by yeyuelong** [NLPchina/ansj_seg#370]
请问lucene插件会添加同义词支持麽？

**Comment by ansjsun** [comment]
会的。。但是神么时候不敢说了。。

**Comment by summer7611** [comment]
我看lucene6 plugin已经update到5.0.4了，是不是就可以用同义词了？如果是lucene5的话，是不是对应的几个地方改一下就好？

**Comment by shi-yuan** [comment]
目前还用不了，需要改动的地方，一个是位置增量，一个是类型

**Comment by ansjsun** [comment]
历史终将不了了之
