### ISSUE TITLE
加载词典default.dic分词错误

### ISSUE THREAD

**Issue by oldjiong** [NLPchina/ansj_seg#371]
北京大学 =》 北京大学
浙江大学 =》 浙大 + 大学
不加载词典分词准确

**Comment by ansjsun** [comment]
UserDefineLibrary.insertWord("北京大学", "userDefine", 1000)  这么试试

**Comment by oldjiong** [comment]
MyStaticValue.DIC.put(MyStaticValue.DIC_DEFAULT, "../../library/default.dic");
Analyzer ca = new AnsjAnalyzer(AnsjAnalyzer.TYPE.dic);
str = "浙江大学";
我试这么试的，想试试自定义词典
然后： 浙江大学 =》 浙大 + 大学

**Comment by ansjsun** [comment]
历史终将不了了之
