### ISSUE TITLE
ansj打包过程中，使用无法使用default.dic等三个dic文件

### ISSUE THREAD

**Issue by sunyonggang** [NLPchina/ansj_seg#373]
windows平台，开发工具IDEA，语言scala，使用的是ansj v5.0.3，将ansj_library.properties放到resource root下面去，可以识别出library的路径，直接执行可以分词成功，但使用maven打包后，发现使用无法加载default.dic，ambiguity.dic, synonyms.dic等三个文件，导致后面的jar包始终无法正常运行，是我放的路径的问题？🖐🏻

有一种方式，就是我将打成的jar包的同级目录放上library目录，那么在运行jar包的时候，是可以去读同级目录的 `library/*.dic` 的，但我的程序是一个分布式的，不可能这样玩，赐教..

**Comment by ansjsun** [comment]
把辞典放到hdfs或其它地方自己用程序加载吧

发自我的 iPhone

**Comment by sunyonggang** [comment]
我将ansj_library.properties中的配置指向hdfs路径，或者是MyStaticValue.DIC.put(MyStaticValue.DIC_DEFAULT, "hdfs://****")的两种方式，还是报之前一样的错误:
```
Init user library error  :hdfs://***  not find that file
```
👀

**Comment by sunyonggang** [comment]
我想通过将library目录放到resource目录下，打包的时候可以发现jar包中存在 `library/*`，但是jar包根据 `ansj_library.properties`找不到jar包里面的library目录，只能找到jar包同级的library，这是我的配置有问题？还是个bug？

**Comment by sunyonggang** [comment]
后面我修改了路径，在通过`spark-submit`提交的时候，将dic文件以`files`的参数加在后面就可以了。
但这个只能说算是`spark-submit`提供的files参数有用。
代码层面上讲，ansj目前只能读取本地文件系统的dic文件
```
UserDefineLibrary.java

BufferedReader e = IOUtil.getReader(new FileInputStream(file), "UTF-8");
```
读取hdfs上面的可能需要自己写代码实现。

**Comment by madong-fun** [comment]
你可以用 spark自带的 textFile读取hdfs上的词典，然后调用  UserDefineLibrary.insertWord(word); 插入到词典中去！

**Comment by ansjsun** [comment]
楼上正解。。。。UserDefineLibrary.insertWord("ansj中文分词", "userDefine", 1000) ；这么动态的自己插入把。。。程序没有直接读hdfs功能

**Comment by madong-fun** [comment]
不知道，先用textFile加载，然后cache，可不可以直接读取，没有试过！不过我再hive中，是用add file /path/file.dic ，然后自定义函数中直接调用就可以 func("",file.dic)，UDF函数中UserDefineLibrary.loadFile(file.dic) 就可以，你可以测试下spark可不可以

**Comment by sunyonggang** [comment]
行的，我可以测试下，先读成rdd，然后insertWord()。
不过，这个样子写程序，感觉**不优雅**

**Comment by ansjsun** [comment]
历史终将不了了之
