### ISSUE TITLE
2.0.8以后的索引分词不起作

### ISSUE THREAD

**Issue by eagleHan** [NLPchina/ansj_seg#377]
2.0.8以后的版本中IndexAnalysis对“中央政府”只能切出“中央政府”，不能切出“中央“和”政府“
”主副食品“也一样

**Comment by eagleHan** [comment]
面向索引分词：故名思议就是适合在lucene等文本检索中用到的分词。
用户自定义词典√ 数字识别√
人名识别√  机构名识别Χ  新词发现Χ
var parse =  IndexAnalysis.parse("主副食品")
result：[主副食品/n]
在该版本中分词效果貌似有点问题，切换成3.7.6的结果也跟上方一样，不过看资料说是能有result:[主副食品/n, 主副食, 副食, 副食品, 食品]这种效果

请问索引分词有需要特别设置的地方吗？

**Comment by ansjsun** [comment]
用索引分词需要挂用户自定义词典


发自我的 iPhone

**Comment by ansjsun** [comment]
历史终将不了了之
