### ISSUE TITLE
Solr中文本带\n\r\t字符，会造成高亮偏移

### ISSUE THREAD

**Issue by summer7611** [NLPchina/ansj_seg#378]
最近将Solr的分词改为Ansj分词，分词很好用，但是有时会遇到些问题。我用的ansj_seg-5.0.2和ansj_lucene5_plug。 

我在org.ansj.ansj_lucene5_plug.HeightLightTest.java中也做了高亮测试。在content的最前面加入“\n\t\r"，再运行程序，发现高亮发生了偏移。 是不是在计算字符位置的时候忽略了特殊字符？
测试内容代码如下：
```
		String content = "\n\t\r不强行上下车，做到先下后上，候车要排队，按秩序上车；下车后要等车辆开走后再行走，如要穿越马路，一定要确保安全的情况下穿行；交通信号灯的正确使用，什么事交通安全出行交通信号灯的正确使用，什么事交通安全出行";
		String query = "\"交通安全出行\"";
```

测试结果如下：

```
,	,
,不/d,强行/d,上/f,下车/v,，/w,做到/v,先/d,下/f,后/f,上/f,，/w,候车/v,要/v,排队/v,，/w,按/p,秩序/n,上车/v,；/w,下车/v,后/f,要/v,等/u,车辆/n,开走/v,后/f,再/d,行走/v,，/w,如/v,要/v,穿越/v,马路/n,，/w,一定/d,要/v,确保/v,安全/nr,的/uj,情况/n,下/f,穿行/v,；/w,交通/n,信号灯/n,的/uj,正确/a,使用/v,，/w,什么/r,事/n,交通安全/n,交通/n,安全/n,出行/v,交通/n,信号灯/n,的/uj,正确/a,使用/v,，/w,什么/r,事/n,交通安全/n,交通/n,安全/n,出行/v
text:"交通安全 交通 安全 出行"

	
不强行上下车，做到先下后上，候车要排队，按秩序上车；下车后要等车辆开走后再行走，如要穿越马路，一定要确保安全的情况下穿行；交通信号灯的正确使用，什<font color="red">么事交通</font><font color="red">安全</font>出行交通信号灯的正确使用，什
```

**Comment by ansjsun** [comment]
主要是因为\r ….这个问题之前发现过..解决了中间的\r没考虑第一行\r

**Comment by summer7611** [comment]
可以告诉我要改哪部分代码吗？我自己先去改一下。

**Comment by ansjsun** [comment]
挺复杂的有个ansjreader

发自我的 iPhone

**Comment by summer7611** [comment]
我又做了几个测试，发现单独的\r或者只是\n\r都不会引起高亮偏移。文本开头只有\t\r这样的组合会引起高亮偏移，文本中间只有\n\t\r这样的组合会引起高亮偏移。 我在ansjreader中readString()的两个提到\n和\r的if中，加入了\t的对应条件，解决了高亮偏移的问题。 但是我不知道这样改会不会引起其他问题。其中，第二个if不改动好像也没有问题。

```
if (c != '\r' && c != '\n' && c!='\t') {
				break;
}
```
```
			if (c == '\n' || c == '\r' || c == '\t') {
				isRead = false;
				break;
			}
```

**Comment by summer7611** [comment]
我之前这样改还是会有问题。在文中如果出现"\n\r    \n\r    \n\r    "这种中间带空格的\n\r，还是会造成后面的高亮偏移。如果在上述if条件中加入` c!=' '` 可以解决这种情况。但是忽略空格会不会造成其他问题？

**Comment by summer7611** [comment]
这几天用改过的代码跑，发现在文本中间出现"\n   \r"这种\n空格\r的组合，也会引起高亮偏移。所在ansjreader的readString()对应的if条件中加入了两个空格条件，分别为半角空格和全角空格。

```
if (c != '\r' && c != '\n' && c!='\t' && c != ' ' && c != '　') {
                break;
}
```


           ```
 if (c == '\n' || c == '\r' || c == '\t' && c == ' ' || c == '　') {
                isRead = false;
                break;
            }
```

**Comment by lwjydhcg** [comment]
@summer7611    请问你最后一次改动后，高亮正常了么  我最近也在被这个问题困扰

**Comment by summer7611** [comment]
@lwjydhcg 啊，之前看到邮件忘记回，到今天才又看到。。。 我改完后至今高亮都正常，希望你也解决了问题

**Comment by ansjsun** [comment]
既然正常了。。我就关了哇
