### ISSUE TITLE
DicAnalysis 部分词（苹果、咖啡等）的自定义标签问题

### ISSUE THREAD

**Issue by paperluo** [NLPchina/ansj_seg#380]
Forest dict1 = new Forest();
Library.insertWord(dict1, new Value("苹果", "userDefine", "1000"));
Library.insertWord(dict1, new Value("咖啡", "userDefine", "1000"));
System.out.println(DicAnalysis.parse("吃苹果喝咖啡", dict1));

吃/v,苹果/n,喝/vg,咖啡/n

**Comment by ansjsun** [comment]
不太确定你的版本,在5.1.0 中我测试结果如下

吃/v,苹果/userDefine,喝/vg,咖啡/userDefine

所以下载最新版本吧..

你可以试试

Forest dict1 = new Forest();
Library.insertWord(dict1, new Value("苹果", "userDefine", "1000"));
Library.insertWord(dict1, new Value("咖啡", "userDefine", "1000"));
		
System.out.println(DicAnalysis.parse("吃苹果喝咖啡", dict1).recognition(new UserDicNatureRecognition(dict1) ));
