### ISSUE TITLE
万圣节被识别为nr

### ISSUE THREAD

**Issue by JoeZhouWenxuan** [NLPchina/ansj_seg#382]
万圣节被识别为人名nr

**Comment by ansjsun** [comment]
应该是被人名识别最先发现.后续则不会用词典替代..建议用 姓名词性再修复下

**Comment by ansjsun** [comment]
UserDicNatureRecognition userDicNatureRecognition = new UserDicNatureRecognition() ;
		
		System.out.println(ToAnalysis.parse("万圣节").recognition(userDicNatureRecognition));

**Comment by JoeZhouWenxuan** [comment]
谢谢你的回复！

发件人: ansj
收件人: NLPchina/ansj_seg
抄送人: 周文瑄、Author
2016-12-10 23:12
主 题: Re: [NLPchina/ansj_seg] 万圣节被识别为nr (#382)
UserDicNatureRecognition userDicNatureRecognition = new UserDicNatureRecognition() ; System.out.println(ToAnalysis.parse("万圣节").recognition(userDicNatureRecognition));
