### ISSUE TITLE
加载默认词表后，Dic分词报java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ameyais** [NLPchina/ansj_seg#385]
ansj_seg5.0.3版本，加载了默认的default.dic后，句子中带“哎咿呀”的，分词时会报错java.lang.ArrayIndexOutOfBoundsException

**Comment by ansjsun** [comment]
恭喜你发现了本年度最佳bug...

这个是在dicanalysis中,当时没考虑周全导致的

此bug会在5.1.0中修复.
