### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project ansj_seg: Compilation failure: Compilation failure: [ERROR] 

### ISSUE THREAD

**Issue by kylinhao** [NLPchina/ansj_seg#387]
`[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:55 min
[INFO] Finished at: 2016-12-08T10:24:30+08:00
[INFO] Final Memory: 25M/1109M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project ansj_seg: Compilation failure: Compilation failure:
[ERROR] /home/kylinhao/ansj_seg/src/main/java/org/ansj/library/FilterLibrary.java:[52,23] 错误: 找不到符号
[ERROR] 类 FilterLibrary
[ERROR] /home/kylinhao/ansj_seg/src/main/java/org/ansj/library/FilterLibrary.java:[52,39] 错误: 找不到符号
[ERROR] 类 FilterLibrary
[ERROR] /home/kylinhao/ansj_seg/src/main/java/org/ansj/library/FilterLibrary.java:[83,26] 错误: 找不到符号
[ERROR] 类 FilterLibrary
[ERROR] /home/kylinhao/ansj_seg/src/main/java/org/ansj/library/FilterLibrary.java:[128,34] 错误: 找不到符号
`

这是什么原因

**Comment by ansjsun** [comment]
之前...提交上来一半的工作,可能导致编译无法通过.pul下再试试
