### ISSUE TITLE
字典读取有问题

### ISSUE THREAD

**Issue by shanshouchen** [NLPchina/ansj_seg#388]
当资源文件在工作目录下时，字典读取没有问题，但当资源文件(字典)打包成jar的时候，通过ClassName.class.getClassLoader().getResource()是读不到文件的

**Comment by ansjsun** [comment]
在未来的版本中.打算做通过..其他方式加载远程词典...请关注..ansj_seg 5.1.0 版本...后续我会把jar发布出来并且,文档补全...
