### ISSUE TITLE
为什么字典文件和字典配置不支持从jar中读取

### ISSUE THREAD

**Issue by shanshouchen** [NLPchina/ansj_seg#389]
library/*
ansj_library.properties
library.properties

有时候想把字典配置和自定文件打包为jar，目前ansj不支持自动从jar包中读取(除了系统自带的字典)

**Comment by ansjsun** [comment]
是不支持的..后期会加入新的读取方式..在5.0.1 的版本中,回头我写一个教程来说明. 这个issues先保留
