### ISSUE TITLE
用户自定义词典

### ISSUE THREAD

**Issue by kylinhao** [NLPchina/ansj_seg#390]
![image](https://cloud.githubusercontent.com/assets/5234656/21041941/3b0a6c92-be29-11e6-8941-f7dc7cde0648.png)
5.0.x以后的版本应按如下操作
然后就是空白了，空白是什么，在properties使用userLibrary已经不支持了

**Comment by ansjsun** [comment]
好了加上了 


userLibrary 改名为dic 完整的配置文件如下

````
#path of userLibrary this is default library
dic=library/default.dic

#path of crfModel
#crf_dic1=library/crf.model

#redress dic file path
ambiguityLibrary=library/ambiguity.dic
synonymsLibrary=library/synonyms.dic

#set real name
isRealName=true

#isNameRecognition default true
isNameRecognition=true

#isNumRecognition default true
isNumRecognition=true

#digital quantifier merge default true
isQuantifierRecognition=true

````

**Comment by Klauszhao** [comment]
为什么我的还是没有用？我按照这样的配置，并自己定义了“淘宝”这样的用户词典，分词时还是会将淘宝分成两个词，
相关配置如下：
#path of userLibrary this is default library
dic=library/default.dic

#redress dic file path
ambiguityLibrary=library/ambiguity.dic

#set real name
isRealName=true

#isNameRecognition default true
isNameRecognition=true

#isNumRecognition default true
isNumRecognition=true

#digital quantifier merge default true
isQuantifierRecognition=true

运行出来的输出内容是：
十二月 15, 2016 3:46:34 下午 DICLOG info
INFO: init user userLibrary ok path is : G:\workspace\ANSJ_Test\library\default.dic
十二月 15, 2016 3:46:34 下午 DICLOG info
INFO: init ambiguityLibrary ok!
十二月 15, 2016 3:46:35 下午 DICLOG info
INFO: init core library ok use time :749
十二月 15, 2016 3:46:35 下午 DICLOG info
INFO: init ngram ok use time :526
每天/r,淘/v,宝/n,，/w,花钱/v,没/d,烦恼/an,，/w,试试/v,这个/r,分词/n,器/k,的/uj,五个/m,分词/n,方法/n,。/w

望解答

**Comment by ansjsun** [comment]
这个应该是词典没加载成功。词典必须utf-8格式。。分隔符是\t  tab 不是空格
