### ISSUE TITLE
四种分词策略的原理

### ISSUE THREAD

**Issue by kylinhao** [NLPchina/ansj_seg#392]
**IndexAnalysis**
**DicAnalysis 用户自定义词典优先策略的分词**
**NlpAnalysis** 
**IndexAnalysis**
https://github.com/NLPchina/ansj_seg/wiki/%E5%88%86%E8%AF%8D%E6%96%B9%E5%BC%8F

这几种分词方式，实现的原理都是什么？能详细说下吗？上面的链接没有详细解释，能解释下吗

**Comment by ansjsun** [comment]
文档说的很清楚了..更详细的就是代码了
