### ISSUE TITLE
关于分词后的处理

### ISSUE THREAD

**Issue by aoleiming** [NLPchina/ansj_seg#396]
您好，

我是初学者。。。
有个问题请教一下。

我看了很多的分词工具，您的工具速度很快也很好用。
不过我的疑问是，分词之后我应该如何使用呢？
网上很多资料说，分词后作为CNN等技术的input，不是很详细。

比如我想实现个问答系统，那我对用户提出的问题分词之后，去跟预先定义好的问题-答案进行匹配，找到最相似的返回吗？
那么如何匹配呢。。。

谢谢。。。

**Comment by ansjsun** [comment]
参见搜索引擎吧....
