### ISSUE TITLE
CRF++训练少量数据可以训练，用大规模语料的时候程序reading data时报错

### ISSUE THREAD

**Issue by Mrfogg** [NLPchina/ansj_seg#397]

**Comment by ansjsun** [comment]
crf模型解析.可能出现了一些问题...目前没有太多精力 ..去修复这个...是出现在模型读取的时候..模型结果和我的预期设置不一致造成...

**Comment by sunjiadong** [comment]
我的训练语料也就300多兆，也是报错，训练不了，请问题主解决问题了吗？

**Comment by Smaillife** [comment]
我个人也比较注重dic的训练，希望早日解决这个问题

**Comment by seven-clear** [comment]
原因是32位的问题，64位的就可以了
