### ISSUE TITLE
dic分词诡异的bug，自定义词不起作用，非常诡异！

### ISSUE THREAD

**Issue by ameyais** [NLPchina/ansj_seg#398]
default.dic就是那个默认的词表
UserDefineLibrary.loadLibrary(UserDefineLibrary.FOREST,"E:\\tool\\default.dic")
UserDefineLibrary.insertWord("英雄联盟")
DicAnalysis.parse("英雄联盟")
这样子分出来的结果是  英雄/nz_联盟/nis
insert的词没有起作用

但是如果不加载那个默认的default.dic，而是直接insert，就可以分出 英雄联盟/userDefine

**Comment by ameyais** [comment]
找到了更加根本的原因
保持isRealName=false
UserDefineLibrary.insertWord("英雄联盟")
UserDefineLibrary.insertWord("英联")
DicAnalysis.parse("英雄联盟")
分出来的结果是 英联 联盟，因为在分此前，”英雄联盟”被转成了”英联联盟”，从而识别不到英雄联盟这个词了，求问这种自动转换可以关掉么？（为何要设置这种转换啊。。。。）

**Comment by ansjsun** [comment]
你好我在我最新的版本中并没有出现这个问题

//dic分词诡异的bug，自定义词不起作用，非常诡异！ #398
		MyStaticValue.isRealName = true ;
		DicLibrary.insert(DicLibrary.DEFAULT,"英雄联盟") ;
		DicLibrary.insert(DicLibrary.DEFAULT,"英联") ;
		System.out.println(DicAnalysis.parse("英雄联盟"));
		
英雄联盟/userDefine


您的版本是? 可能这个bug已经被修复请等待5.1.0版本的分词

**Comment by ameyais** [comment]
我是5.0.3版本，跪求新版本的发布~

**Comment by ansjsun** [comment]
@ameyais  

https://oss.sonatype.org/content/repositories/releases/org/nlpcn/nlp-lang/1.7.2/

https://oss.sonatype.org/content/repositories/releases/org/ansj/ansj_seg/5.1.0/

可以了试试..好使不...

**Comment by ameyais** [comment]
好使了！大赞~~~
