### ISSUE TITLE
org.ansj.domain.Result 无法转换成List<Term>

### ISSUE THREAD

**Issue by diaosuyidsy** [NLPchina/ansj_seg#399]
`List<Term> terms = ToAnalysis.parse("我觉得Ansj中文分词是一个不错的系统!我是王婆!");`

这句话就会报错说Result无法转换成List<Term>。我是下载的5.0.4的jar

**Comment by shi-yuan** [comment]
```java
Result result = ToAnalysis.parse("我觉得Ansj中文分词是一个不错的系统!我是王婆!");
List<Term> terms = result.get();
```

**Comment by appleyuchi** [comment]
Error:(34, 17) java: 找不到符号
  符号:   类 Result
  位置: 类 DataPreProcess
