### ISSUE TITLE
ansj面向索引的分词  没有效果 使用的是最新的ansj_seg 5.1.0

### ISSUE THREAD

**Issue by zhangxianweihebei** [NLPchina/ansj_seg#401]
public static void main(String[] args) {
		 String str = "上海虹桥机场南路" ;
		 Result result = IndexAnalysis.parse(str);
		 List<Term> terms = result.getTerms();
		 System.out.println(terms);
	}

结果 
[上海/ns, 虹桥/ns, 机场/n, 南/f, 路/n]

**Comment by ansjsun** [comment]
没有挂载用户自定义词典吧

发自我的 iPhone

**Comment by zhangxianweihebei** [comment]
是没有挂载用户自定义词典       你的意思是  自定义 上海，虹桥，机场  等词后  才会有 召回率？

**Comment by ansjsun** [comment]
索引分词的原理是.在核心词典分词之后.利用用户自定义词典的分词结果.做二次发现.如若你没有挂载.用户自定义词典.索引分词便不会生效.
