### ISSUE TITLE
ansj  中英文 混合词 检索不到

### ISSUE THREAD

**Issue by zhangxianweihebei** [NLPchina/ansj_seg#402]
使用自定义用户词典

一个lucene （词）

这是一个lucene 检索工具  （内容）

检索  一个lucene   结果是空

**Comment by ansjsun** [comment]
分词版本？ 不应该呀 你看看这句话的分词结果

发自我的 iPhone

**Comment by zhangxianweihebei** [comment]
版本是最新的               就是当用户自定义词典  （词）是个中英组合时   检索不到

**Comment by zhangxianweihebei** [comment]
我进一步测试了一下  

ansj中sas我觉得Ansj中文分词是一个不错的系统!我是王婆!  （内容）
analyzer= new AnsjAnalyzer(TYPE.user);
UserDefineLibrary.insertWord("Ansj中", "userDefine", 1000);  （词典）

《结果》
name:<font color='red'>ansj</font><font color='red'>中</font>
sas我觉得<font color='red'>Ansj</font>中文分词是一个不错的系统!我是王婆! 



结论  如果中文本身是一个词  他是一个词  如上 中文，分词
用户自定义 Ansj中  词
没有按照用户意愿去区分，而是优先  自己组合   自己组合不到了  在使用 用户词典

**Comment by ansjsun** [comment]
1.用DicAnalysis 的方式进行分词.... TYPE.dic 这个来搜索
2. 增加词语的时候..UserDefineLibrary.insertWord("Ansj中".**toLowcase()**, "userDefine", 1000); 词语必须小写

**Comment by zhangxianweihebei** [comment]
lucene 使用DicAnalysis 是不是的自己实现啊

**Comment by zhangxianweihebei** [comment]
![image](https://cloud.githubusercontent.com/assets/15844529/21540231/d746b362-cde8-11e6-87f4-b77071ab65e8.png)
TYPE.dic 和user 结果是

**Comment by zhangxianweihebei** [comment]
添加索引
![image](https://cloud.githubusercontent.com/assets/15844529/21602881/a41b7b78-d1d3-11e6-937d-102e32a726e9.png)
查询索引
![image](https://cloud.githubusercontent.com/assets/15844529/21602882/abf7630c-d1d3-11e6-98a1-a9f3311e695c.png)

结果页
![image](https://cloud.githubusercontent.com/assets/15844529/21602864/5a5efb72-d1d3-11e6-83e8-b2488f11b3a9.png)


没有强制 使用用户自定义分词

**Comment by ansjsun** [comment]
如果用dic的方式是用户自定义词语优先的
