### ISSUE TITLE
最新版本 动态添加用户字典 方法没了？

### ISSUE THREAD

**Issue by zhangxianweihebei** [NLPchina/ansj_seg#404]
UserDefineLibrary.insertWord("ansj中文分词", "userDefine", 1000);
 最新版本 找不到这个方法了

**Comment by zhangxianweihebei** [comment]
5.1.0 没了   5.0.4   还有

**Comment by kingsdu** [comment]
是啊，大神，怎么没了呢？
那怎么动态添加歧义词呢？
而且我在歧义词典里面添加也没效果呢？

**Comment by zhangxianweihebei** [comment]
降低版本呗

**Comment by shi-yuan** [comment]
使用  Library.insertWord

**Comment by ansjsun** [comment]
不好意思,5.1.0版本之后重构了.词典设置..一直很忙所以没有完善文档..可以通过

//多种加载途径
https://github.com/NLPchina/ansj_seg/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E

//多种词典类型
https://github.com/NLPchina/ansj_seg/wiki/%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%85%B8

//用户自定义词典的一个例子
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/library/DicLibraryTest.java
