### ISSUE TITLE
File2Stream类里面的multiple方法貌似有点小问题

### ISSUE THREAD

**Issue by lukachun** [NLPchina/ansj_seg#406]
在File2Stream类的multiple方法里面：
private InputStream multiple(String path) throws FileNotFoundException {
        File[] libs = new File[0];
        File file = new File(path);
        if(file.exists() && file.canRead()) {
            if(file.isFile()) {
                libs = new File[]{file};
            } else if(file.isDirectory()) {
                **File[] vector = file.listFiles(new FilenameFilter() {
                    public boolean accept(File dir, String name) {
                        return dir.canRead() && !dir.isHidden() && !dir.isDirectory();
                    }
                });**
                if(vector != null && vector.length > 0) {
                    libs = vector;
                }
            }
        }
    ....
  }

加粗的地方是不是修改成这样会好点：
    **File[] vector = file.listFiles(new FileFilter() {
           public boolean accept(File file) {
                        return file.canRead() && !file.isHidden() && !file.isDirectory();
           }
      });**

**Comment by ansjsun** [comment]
就是filefilter 和filenamefilter的区别吧

发自我的 iPhone

**Comment by lukachun** [comment]
是的，在这个地方用FilenameFilter应该是不起作用的，在FilenameFilter的accept方法里面dir参数指的是目录，所以 !dir.isDirectory() 一直就是false

**Comment by ansjsun** [comment]
的确有问题.感谢..
