### ISSUE TITLE
自定义词是数字或者英文将无效？

### ISSUE THREAD

**Issue by LPQingFeiDeYi** [NLPchina/ansj_seg#407]
我想定义一些数字作为自定义词，比如股票代码：000035， 和英文简写：SXSM。 但是发现无法自定义，000035不按我自定义的词性stock，是m。英文简写也这样。请问如何解决这个问题。谢谢！

**Comment by ansjsun** [comment]
英文词典中的词语必须小写..

你需要通过一次词性修复来让用户自定义词典优先

System.out.println(NlpAnalysis.parse("结婚的和尚未结婚的孙建是一个好人").recognition(new NatureRecognition()));


如果使用的不是默认词典需要 在new NatureRecognition(词典名称)

**Comment by LPQingFeiDeYi** [comment]
@ansjsun 
我现在用的是5.0.2的版本，按照你的方方法是不行的。
5.0.2可以用这样 UserDefineLibrary.loadLibrary(UserDefineLibrary.FOREST, "library/userDefine"); 加载用户定义词典（加载整个文件夹）
刚看了5.11.0，没看懂如果加载用户自定义词典。求指点

**Comment by ansjsun** [comment]
try it
````
Result terms = ToAnalysis.parse("Ansj中文分词是一个真正的ict的实现.并且加入了自己的一些数据结构和算法的分词.实现了高效率和高准确率的完美结合!");
		terms.recognition(new NatureRecognition()) ; //词性标注
		System.out.println(terms);
````
