### ISSUE TITLE
5.1.0版本dic分词加入的词无效

### ISSUE THREAD

**Issue by ameyais** [NLPchina/ansj_seg#409]
DicLibrary.insert(DicLibrary.DEFAULT, "琅琊榜","user",1000)
println(DicAnalysis.parse("琅琊榜"))

输出结果是
琅,琊/g,榜/n

麻烦大神看一下吧，用的是最新版5.1.0

**Comment by xia5271** [comment]
我也遇到这个问题了，还以为是我打开的方式不对那...

**Comment by xia5271** [comment]
玫红色  也是这种问题，使用NlpAnalysis就没事

`DicLibrary.insert(DicLibrary.DEFAULT, "玫红色");
        System.out.println(DicAnalysis.parse("玫红色"));
        System.out.println(NlpAnalysis.parse("玫红色"));`
