### ISSUE TITLE
在Spark上分词时自定义词库失效

### ISSUE THREAD

**Issue by YCG09** [NLPchina/ansj_seg#410]
我在Spark上调用ansj进行文本分词，分别尝试了词库文件导入和textFile读hdfs的方式，UserDefineLibrary.contains("xxx")也都能返回true，Idea里和以local方式在Spark集群中提交任务都没有问题

然而一旦以standalone或yarn模式提交任务就出现自定义词表部分失效的问题，不能完全分词正确，并且每次运行返回的分词结果均存在差异，无论采用client还是cluster方式，尝试了各种方法都无法解决，我使用的是ansj5.0.4和Spark1.6.2，另外也试过ansj5.1.0，问题依旧存在，莫非和Spark有关系？

被这个问题困扰了很久，期待大家的帮助，谢谢！

**Comment by ansjsun** [comment]
你是用的配置文件是 library.properties 还是ansj_library.propertis ?如果是 library.properties 改成后者.

可以尝试 LibraryDic.insert("任意一个词语") 然后分词看看这个词语是否能分出

**Comment by ameyais** [comment]
应该是由于你加载词典这个操作只在driver上执行了，所以local可以分出，但是其他的executor有的并没有加载词典。

为了保证每个executor的词典都加载了，我的方法是可以把加载词典的forest的广播出去
val dic1 = Library.makeForest(dict_list)
val brDict = sc.broadcast(dic1)

在分词的时候，使用DicAnalysis.parse(line, brDict.value)

**Comment by YCG09** [comment]
@ameyais 非常感谢，广播后问题解决了！

另外我还想问下在使用FilterRecognition动态加载停用词进行停用词过滤时也存在不能完全过滤的问题，该如何解决呢？

**Comment by ameyais** [comment]
相同的道理，把加载停用词的过滤器广播

**Comment by YCG09** [comment]
@ameyais 是我糊涂了，谢谢！

**Comment by andyxzq** [comment]
@ameyais ，请问你说的dict_list是什么？

**Comment by YCG09** [comment]
@andyxzq 你可以参考这个，https://github.com/YCG09/xgbspark-text-classification
