### ISSUE TITLE
请问一下，5.1.0版本加载自己的CRF模型是怎么做的？之前的MyStaticValue.CRF.put()方法没有了

### ISSUE THREAD

**Issue by sunjiadong** [NLPchina/ansj_seg#411]

**Comment by ansjsun** [comment]
用CRFLibrary这个类的静态方法

发自我的 iPhone

**Comment by sunjiadong** [comment]
@ansjsun  嗯，我用了类里面的put，模型是crf++训练的，txt格式，加载的时候报了not in gzip format的错误，麻烦问下 crf模型的格式有什么要求吗？

**Comment by JaneVinWin** [comment]
@ansjsun 请问这个问题可以给个调用的例子吗

**Comment by ansjsun** [comment]
CrfLibrary.put("name1","crf文件路径")

new NlpAnalysis().setCrfModel(CrfLibrary.get("name1")).parse(.....)

**Comment by JaneVinWin** [comment]
@ansjsun  按上面的方法，得到error
![image](https://cloud.githubusercontent.com/assets/11938475/23706135/f0c48d60-0447-11e7-8293-3a12c352ea1e.png)

**Comment by ansjsun** [comment]
可能是训练的crf模型不对...具体我也不太有把握..模型那块有bug除了我成功了..好多人都失败了

**Comment by tianshuaifei** [comment]
@ansjsun 你好，我自己训练的crfmodel,使用下边的方法能够正常运行：
CRFppTxtModel crfppTxtModel=new CRFppTxtModel();
String path = "D:/Java/workspace/bwNLP/library/model/modex.txt";
CRFppTxtModel model = crfppTxtModel.loadModel(path);
System.out.println(new SplitWord(model).cut("结婚的和尚未结婚的"));

当我调用：
CrfLibrary.put("name1",path);
CrfLibrary.get("name1");
的时候报了以下错误：

六月 07, 2017 6:04:17 下午 org.ansj.library.CrfLibrary error
严重: org.ansj.domain.KV@283bbb6 load err Not in GZIP format

然后我用
		CRFppTxtModel model = crfppTxtModel.loadModel(path);
		model.writeModel("D:/Java/workspace/bwNLP/library/model/crf.model");
将crf++-0.58的model压缩保存，重新调用：
CrfLibrary.put("name1","D:/Java/workspace/bwNLP/library/model/crf.model");
CrfLibrary.get("name1");
又报了如下错误：

月 07, 2017 6:11:07 下午 org.ansj.library.CrfLibrary error
严重: org.ansj.domain.KV@214b5739 load err Unexpected end of ZLIB input stream

请问如何正确的替换ansj_seg项目中的crf.model

**Comment by shibing624** [comment]
CRF 训练，我提供一下工具，linux版和windows版都在，试用了，可行的。http://pan.baidu.com/s/1qYUC4US
