### ISSUE TITLE
如何在一个项目中有添加了不同词典的 分词器.

### ISSUE THREAD

**Issue by dulm** [NLPchina/ansj_seg#415]
比如分词器A: 默认的环境, 添加了一个 自定义的词典A1, 停用词典A2.
再另一个分词器B: 是默认自带词典, 外加自定义词典B1, 停用词典B1.

感觉项目中,如DicLibrary, 全是static变量, 很难定制.

**Comment by ansjsun** [comment]
ToAnalysis.parse(str, DicLibrary.get("dic1"), DicLibrary.get("dic2")))
