### ISSUE TITLE
5.1.1版本时如何加载已打入本jar包中的字典文件？

### ISSUE THREAD

**Issue by ywjno** [NLPchina/ansj_seg#420]
我已经把字典文件打包到jar包中并在 properties 文件中指定文件路径，在用 `java -jar` 命令来运行的时候还是会查 jar 文件同目录下的 library 文件夹

**Comment by ywjno** [comment]
应该用 `jar://library/default.dic` 这样的方式来加载

**Comment by ansjsun** [comment]
@ywjno  可以这么用吗?能使?

**Comment by ywjno** [comment]
可以用的，我现在就是那么写

**Comment by ywjno** [comment]
呃。。。貌似不行

**Comment by ansjsun** [comment]
@ywino  这么写试试 jar://org.ansj.dic.DicReader|/crf.model

jar://你的jar保重随便一个类,根据这个类我能找到jar包/文件名称.

/crf.model  代表jar的根目录,,    

crf.model 代表之前类的同级目录

**Comment by ansjsun** [comment]
ps
建议你用http方式...这样不用打包jar了....词典还能重用

目前支持如下方式

````
if (path.startsWith("file://")) {
				return new File2Stream().toStream(path);
			} else if (path.startsWith("jdbc://")) {
				return new Jdbc2Stream().toStream(path);
			} else if (path.startsWith("jar://")) {
				return new Jar2Stream().toStream(path);
			} else if (path.startsWith("class://")) {
				((PathToStream) Class.forName(path.substring(8).split("\\|")[0]).newInstance()).toStream(path);
			} else if (path.startsWith("http://")||path.startsWith("https://")) {
				return new Url2Stream().toStream(path);
			} else {
				return new File2Stream().toStream(path);
			}
````

**Comment by ywjno** [comment]
我是把用 maven 打包成一个 fat jar 传到服务器上，然后跑 main 方法实现一个功能，所以需要这么干

**Comment by ansjsun** [comment]
恩也是可以的...你试试

 jar://org.ansj.dic.DicReader|/crf.model 这种方式吧  org.ansj.dic.DicReader| 这里写一个类词典文件和类是在一个jar包中即可...

**Comment by ywjno** [comment]
嗯，我现在用的是 `jar://library/default.dic` 跳过检查，然后 `DicLibrary.insert(DicLibrary.DEFAULT, str);` 这样加载字典

**Comment by ansjsun** [comment]
对的这样也是可以的....
