### ISSUE TITLE
分词结果里Term们之间的指针并没有串起来……？

### ISSUE THREAD

**Issue by betty35** [NLPchina/ansj_seg#422]
Parse后得到的结果里面，每个Term的next都是null……

**Comment by ansjsun** [comment]
能给我看具体代码吗??在输出结果的时候..可能将所有的next都设置为null..term的next只为了分词找最优路径..找到之后..就把链接断开了.至于为什么.我也忘记了

**Comment by betty35** [comment]
具体代码都删了好久了……

我当时取了Result的第一个Term，打算用next()去做句式匹配，然后一个句式都没匹配出来，一头雾水，最后发现……诶？我词都哪儿去了？……就改从Result了取Term的List一个一个get了。

确实取List<Term>从功能上讲完全可以代替next()，但一个个get好像挺慢的……但我也是个菜鸟，并不知道next会不会更快……我只是来问一下，嗯。

总之，我也先去wiki加两笔吧，虽然说话不利索+1
