### ISSUE TITLE
用户自定义词典的词频设置

### ISSUE THREAD

**Issue by nanma** [NLPchina/ansj_seg#425]
我从网站 http://maven.nlpcn.org/down/library 下载了默认的用户词典 default.dic，里面的词语已经设置了词频（确切地说是文档频率）。如果我想向这个文件中添加新词，请问应该怎么取词频的数值？比如新加一个词“志明”，词频多少比较合理？

**Comment by ansjsun** [comment]
2000 就可以...只要是大于0的数字都可以
