### ISSUE TITLE
5.1.0后同义词词典怎么用

### ISSUE THREAD

**Issue by edwardzjl** [NLPchina/ansj_seg#426]
5.1.0之前是在配置文件里写
userLibrary=library/userLibrary/userLibrary.dic
synonymsLibrary=xxx

5.1.0把userLibrary改成了dic，但是没说synonymsLibrary要不要改
我写了synonymsLibrary=xxx，在启动的log中显示似乎是正确的：
init synonymsLibrary to env value is : dicts/synonyms.txt

但是词典似乎没有效果
比如我的 dicts/synonyms.txt 里的内容是
阿拉比卡 阿拉比加 阿拉毕卡

在一个包含了 “阿拉比卡” 的句子里，Term的getSynonyms()返回的却都是空
有同义词词典的使用说明吗？

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/recognition/impl/SynonymsRecgnitionTest.java

这个是同义词词典的例子

properties 应该这么加
````
synonymsLibrary=library/synonyms.dic
````

注意看日志是否提示加载成功.格式词与词之间是tab.就是\t切记

**Comment by edwardzjl** [comment]
试了一下，又看了一下你的代码，我用的5.1.1版本，应该是写成
`synonyms=dicts/synonyms.dic`
这样子了吧

另外，我想通过同义词词典进行替换，例如将 阿拉比卡 阿拉比加 阿拉毕卡 全都替换成 阿拉比卡
也就是对同义词进行标准化
这个通过 ansj 的同义词模块能实现吗？

**Comment by ansjsun** [comment]
在整理词典的时候将词语 位置排列好.

example
````
阿拉比卡 阿拉比加 阿拉毕卡
````
然后通过.term.getSynonyms().get(0)方式将第一个词作为你的结果使用既可以

**Comment by edwardzjl** [comment]
照你说的试了下，效果OK。
