### ISSUE TITLE
关键词抽取中IDF问题

### ISSUE THREAD

**Issue by lemonhu** [NLPchina/ansj_seg#428]
idf = Math.log(10000 + 10000.0 / (docFreq + 1));
这里的第一个10000是什么意思呢，不太明白，求解，谢谢！

**Comment by ansjsun** [comment]
Math.log(10000.0 / (docFreq + 1)) 党docfreq>10000的时候可能是一个负数.所以为了保证是正数加了这个..但是有个10000+ 不应该呀..应该是1+ 昏可能是我的bug

**Comment by ansjsun** [comment]
因为词频是用户自己定的.定多少不能限定..10000只是一个经验值.没有任何道理..的确是个前面的10000+的确是个bug感谢您的提醒

**Comment by hzqgithub** [comment]
搞明白了，谢谢！
