### ISSUE TITLE
mac地址识别

### ISSUE THREAD

**Issue by sunny800629** [NLPchina/ansj_seg#430]
您好，请问当前分词器支持mac地址识别么？如果支持，请问如何使用呢？谢谢！

**Comment by ansjsun** [comment]
你好目前不支持mac地址识别..你可以实现自己的recognition 像这样来实现https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/recognition/impl/BookRecognition.java

**Comment by sunny800629** [comment]
好的，谢谢。


sunny800629@sina.com
 
Sender: ansj
Send Time: 2017-03-10 20:51
Receiver: NLPchina/ansj_seg
cc: sunny800629; Author
Subject: Re: [NLPchina/ansj_seg] mac地址识别 (#430)
你好目前不支持mac地址识别..你可以实现自己的recognition 像这样来实现https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/recognition/impl/BookRecognition.java
