### ISSUE TITLE
position increment的问题导致es索引文档时出错

### ISSUE THREAD

**Issue by d4ksn** [NLPchina/ansj_seg#431]
es版本5.2.2，异常信息：
"cause": {
        "type": "illegal_argument_exception",
        "reason": "first position increment must be > 0 (got 0) for field 'title'"
      },
试着用analyze API分词，返回position的顺序是-1,0,2,5,9,14,20,27这样的，斐波拉契数列，但是其他分词器返回的一般都是0,1,2,3,4,5,6，这到底啥情况呢，我是es新人，哪位大牛可以解答一下？

**Comment by ansjsun** [comment]
@shi-yuan

**Comment by dhb-fly** [comment]
这个需要把源码里面的postion改成1。但是还有个问题，就是如果文本太长，就会出现postion越界的问题。这块不知道有没有什么方法解决。

**Comment by shi-yuan** [comment]
能提供text吗？

**Comment by d4ksn** [comment]
哦，这个问题我自己改了一下，已经搞定了。办法是在incrementToken方法中把position初始化为0

**Comment by ansjsun** [comment]
@d4ksn 我也发现了.之前不知道为啥写的是-1

**Comment by d4ksn** [comment]
提了个pullrequest， #446 大家可以对此讨论一下
