### ISSUE TITLE
请问你的CRF模型怎么实现的,也就是你的转移特征和状态特征怎么定的

### ISSUE THREAD

**Issue by kylinhao** [NLPchina/ansj_seg#432]
能具体说下嘛，急求，万分感谢了。

**Comment by ansjsun** [comment]
sbme 这4个标签的.... 好像是 0,1 |-1,0 |1,-!| -2,0,2|这么定义的

**Comment by kylinhao** [comment]
什么意思，骂人？

**Comment by ansjsun** [comment]
哥 @kylinhao s 是单独一个字,,b是begin开始. m 是中间.e是end...

crf标注字段额....

看这个文章..我昏

**Comment by kylinhao** [comment]
sorry, 这四个状态BMES,没见过这么读的，你发的那个链接是这样的，
![image](https://cloud.githubusercontent.com/assets/5234656/23820228/46a74c46-064f-11e7-908a-135324e4f84d.png) 是不是发错链接了

**Comment by ansjsun** [comment]
好吧,随手打了没多想.勿怪.链接我打开是没有错的..用电脑打开试试....

**Comment by kylinhao** [comment]
谢了
