### ISSUE TITLE
关于docFreq的问题

### ISSUE THREAD

**Issue by JoeZhouWenxuan** [NLPchina/ansj_seg#434]
你好，请问类KeyWordComputer中为什么可以用term.nature().allFrequency当做docFreq，不是很理解，希望能给予解答。谢谢

**Comment by ansjsun** [comment]
因为..计算词频就是idf..默认的话词语在每个词性的情况下有多个词频..但是关键词抽取.可以忽略语义词性.所以取所有词频之和作为idf

**Comment by JoeZhouWenxuan** [comment]
好的，谢谢！
