### ISSUE TITLE
CRF文本模型加载的问题

### ISSUE THREAD

**Issue by winder8x** [NLPchina/ansj_seg#439]
在使用CRF模型加载的时候，发现
CRFppTxtModel中

> private void loadFeatureWeight(BufferedReader br, int[] statusCoven, TreeMap<Integer, Pair<String, String>> featureNames) throws Exception {

方法读取特征值的时候，使用了featureNames.values()进行循环读取特征值。Map的Values顺序应该不是固定的，请问这种顺序是否是特征值的顺序？

同时对比了hanLP模型的加载，发现使用的是模型文件中的特征顺序（基于List）循环加载特征值，先加载了Bigram的特征值，然后加载Unigram的特征值。

**Comment by winder8x** [comment]
继续网上搜索CRF++的text model文件，有的说特征值是按照特征的id顺序存储的。每个特征有n（特征转换标签数量）个特征值。
目前读到
conver[i] = conver[(i - 4) / tagCnt] * tagCnt + conver[i % tagCnt] + tagCnt;
但不明白是什么意思。

**Comment by winder8x** [comment]
今天看到加载特征值的时候，
`
				for (int i = 0; i < len; i++) {
					temp = br.readLine();
					tag = statusCoven[i];
					tempW[i] = ObjConver.getFloatValue(temp);
				}
				this.featureTree.add(name, tempW); // 将特征增加到特征🌲中`
如果只有B、E、M、S四个标签，则statusCoven为[1,3,2,0]，但如果是大于4个标签，则statusCoven的值该怎么定义？

**Comment by ansjsun** [comment]
我争取重构下crf的方式把 。。目前来看好多类似的问题
