### ISSUE TITLE
如何设置特定短语不分词

### ISSUE THREAD

**Issue by initeasylife** [NLPchina/ansj_seg#440]
比如“互联网智能汽车”
我希望在分词结果中这是一个整词

**Comment by ansjsun** [comment]
""互联网智能汽车"" 这个加入到词典中

**Comment by initeasylife** [comment]
我看了看文档，加入词典中依然会被分开，应该是加入歧义词词典

2017-03-20 19:04 GMT+08:00 ansj <notifications@github.com>:

**Comment by ansjsun** [comment]
只有在发生歧义的时候才有可能分开...这么长的词分开概率很低了...不需要歧义词典的..文档没有我权威

**Comment by initeasylife** [comment]
谢谢你咯^_^

2017-03-21 11:25 GMT+08:00 ansj <notifications@github.com>:
