### ISSUE TITLE
关于自定义词典的问题

### ISSUE THREAD

**Issue by endymecy** [NLPchina/ansj_seg#444]
**例句如下:**
登陆新三板，标志着德邦大为的经营模式和理念已经得到资本市场认可，相信在公司上市后，凭借丰富的农业人才储备、领先的高端农机装备的研发能力、先进的农机装备生产制造能力和较强的资源整合优势，能够借助资本市场的力量，取得更加快速的发展。

**DicAnalysis的分词结果:**
登陆/vi,新/a,三板/mq,，/w,标志/n,着/uzhe,德/b,邦/ng,大为/d,的/ude1,经营/vn,模式/n,和/cc,理念/n,已经/d,得到/v,资本/n,市场/n,认可/vn,，/w,相信/v,在/p,公司/nis,上市/vn,后/f,，/w,凭借/p,丰富/a,的/ude1,农业/n,人才/n,储备/v,、/w,领先/vi,的/ude1,高端/nz,农机/n,装备/n,的/ude1,研发/v,能力/n,、/w,先进/a,的/ude1,农机/n,装备/n,生产/vn,制造/vn,能力/n,和/cc,较/d,强/a,的/ude1,资源整合/nz,优势/n,，/w,能够/v,借助/v,资本/n,市场/n,的/ude1,力量/n,，/w,取得/v,更加/d,快速/d,的/ude1,发展/vn,。/w

**动态加入之后的分词结果**
我把"德邦大为"这个词通过DicLibrary.insert(DicLibrary.DEFAULT, "德邦大为", "n", 1000);
动态加入词典,可以分出"**德邦大为**"这个词,结果是:
登陆/vi,新/a,三板/mq,，/w,标志/n,着/uzhe,德邦大为/n,的/ude1,经营/vn,模式/n,和/cc,理念/n,已经/d,得到/v,资本/n,市场/n,认可/vn,，/w,相信/v,在/p,公司/nis,上市/vn,后/f,，/w,凭借/p,丰富/a,的/ude1,农业/n,人才/n,储备/v,、/w,领先/vi,的/ude1,高端/nz,农机/n,装备/n,的/ude1,研发/v,能力/n,、/w,先进/a,的/ude1,农机/n,装备/n,生产/vn,制造/vn,能力/n,和/cc,较/d,强/a,的/ude1,资源整合/nz,优势/n,，/w,能够/v,借助/v,资本/n,市场/n,的/ude1,力量/n,，/w,取得/v,更加/d,快速/d,的/ude1,发展/vn,。/w

**在defalut.dic文件中添词后的结果**
我不通过代码加,而是在default.dic文件中添加"德邦大为"这个词,无法切分出来.可以确定default.dic文件加载正确.

org.ansj.library.DicLibrary info
load dic use time:975 path is : library/default.dic

**Comment by ansjsun** [comment]
default.dic 中分隔符必须是\t 编码必须是utf-8.

**Comment by endymecy** [comment]
我是在原有的default.dic文件后面添加的词.确认应该是utf-8.

龙神丐  n       2
龙纹尊  n       2
龙观站  n       2
龙语    nz      2
恒大    nt      20
跨界    nz      20
德邦大为    nt  10000

**Comment by endymecy** [comment]
分隔符也是\t

**Comment by ansjsun** [comment]
那你需要确定加载的词典路径是否正确,是不是加载的不是这本词典
你分词用的toanalysis 或是dicanalysis.

德邦大为 nt 10000 这句话..复制到中间位置试试


编辑器不要用windows记事本..用ue ide都可以...

**Comment by endymecy** [comment]
词典没错,因为我删掉之后,运行会报找不到文件的错.
德邦大为 nt 10000   放到中间也不起作用.

我用的版本是5.1.2

**Comment by endymecy** [comment]
sorry,我重启了一下intellij,可以了
