### ISSUE TITLE
词性过滤异常，以及词性标注跟文档不符

### ISSUE THREAD

**Issue by isAbird** [NLPchina/ansj_seg#445]
使用版本为5.0.1，
（1）最先发现的是在使用中使用一类词性做过滤，词性过滤没有生效。例如使用对词性为u的做过滤，但是下属的uzhe、uguo等二类词性对应的词都没有被过滤掉  
（2）怀疑是一类词性过滤没效果，改用二类词性做过滤测试。发现很多时候过滤掉的词和词性表对应的词不符合  
（3）于是使用词性标注接口，对几个词做了词性标注测试，发现词性跟文档说明中不符：
词性标注测试结果： 【的/uj, 得/ud, 云云/v, 了/ul, 过/ug, 来说/u】
而文档中：
  ude1 的 底
  ude2 地
  ude3 得
  udeng 等 等等 云云
  ule 了 喽
  uguo 过
  uls 来讲 来说 而言 说来
（4）使用词性标注中显示的词性做词性过滤，发现能够正常过滤
FilterRecognition fitler = new FilterRecognition();
fitler.insertStopNatures("uj"); // 助词
Result parse = ToAnalysis.parse("的得云云了来说").recognition(fitler);
结果：得  云云  了  来说
  
   主要是两个问题：
    1）无法根据一类词性对这一大类词做过滤
    2）二类词性跟说明文档不符合

**Comment by ansjsun** [comment]
我更新了一些文档..你去wiki看看吧
