### ISSUE TITLE
crf模型相关问题（语料名称、特征、crf.model.txt）

### ISSUE THREAD

**Issue by tiandiweizun** [NLPchina/ansj_seg#447]
您好，我发现您提供的CRF模型比HanLP（一个java版本的中文NLP工具）的CRF新词发现要好很多，且部分比LTP的也要好，我想知道您训练的**语料名称**（不需要语料，但是希望知道你拿哪些语料去训练的）以及**选取的特征**，最后，如果能提供**crf.model.txt**就真的感激不尽了（把数据加载进去，然后转成crf.model.txt真的很痛苦）。由于业务需要，我需要使用HanLP（工程化做的确实不错）已经写好的代码来加载CRF（需要txt格式）模型，比如过滤无关词等，而Ansj提供的CRF很多地方已经写死了，基本只能为分词服务，所以，希望能使用上您提供的模型和HanLP提供的代码。

**Comment by ansjsun** [comment]
我去找找crftxt的模型.找到了发你邮箱..当时建立模板的语句一并给你

**Comment by tiandiweizun** [comment]
感激不尽

**Comment by moshangshaoguang** [comment]
@ansjsun 可不可以也发我一份，非常感谢

**Comment by madong-fun** [comment]
@ansjsun 同求

**Comment by yyd12345** [comment]
@ansjsun 同求，非常感谢

**Comment by tiandiweizun** [comment]
历史总是不了了之

**Comment by BEshakalaka** [comment]
同求
