### ISSUE TITLE
最新版的歧义纠正词典没法动态添加

### ISSUE THREAD

**Issue by shiyuanhui** [NLPchina/ansj_seg#448]
请问，用 MyStaticValue.ambiguityLibrary = "歧异词典的路径" 来设定  这个方法我在源码里面也没看到，是删除了吗？

**Comment by ansjsun** [comment]
AmbiguityLibrary

看这里 https://github.com/NLPchina/ansj_seg/wiki/%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%85%B8
