### ISSUE TITLE
使用maven更新的最新版和手动下载的项目使用同一个分词方式结果不一样

### ISSUE THREAD

**Issue by moshangshaoguang** [NLPchina/ansj_seg#449]
![image](https://cloud.githubusercontent.com/assets/20895017/24281240/f85d3c56-1091-11e7-8743-9868c0d451ff.png)
这是直接用maven 调用方法显示的结果
![image](https://cloud.githubusercontent.com/assets/20895017/24281185/9203434c-1091-11e7-8d99-fd417a5ab711.png)
这是手动下载下来ansj项目调用方法显示的结果
是哪个文件没有配置吗

**Comment by ansjsun** [comment]
是不是没加载用户自定义词典..对比..启动日志应该可以看到

**Comment by moshangshaoguang** [comment]
谢谢解答，是因为我一开始没有把library文件放进用maven下载的项目中，所以导致分词结果不一样

**Comment by ansjsun** [comment]
ok
