### ISSUE TITLE
词性标注问题

### ISSUE THREAD

**Issue by zyc825onDataMining** [NLPchina/ansj_seg#450]
String str = "公信力，政府公信力";
Result str1 = ToAnalysis.parse(str);
切词的结果为：
公信力/nz,，/w,政府/n,公信力/nr
同样的词为什么词性标注会不一样。查找默认字典里‘公信力’这个词只有nz这一种词性

**Comment by ansjsun** [comment]
牛逼的人名识别导致的

用DicAnalysis, 

或者用用户词性
System.out.println(NlpAnalysis.parse("结婚的和尚未结婚的").recognition(new NatureRecognition()));
做词性修正,,

**Comment by zyc825onDataMining** [comment]
感谢，问题已解决
