### ISSUE TITLE
first position increment must be > 0 (got 0) for field 'content'

### ISSUE THREAD

**Issue by sunny800629** [NLPchina/ansj_seg#451]
first position increment must be > 0 (got 0) for field 'content'  在solr6.1.0和solr6.4.2，在测试通过lucene的indexwriter接口写入索引时抛出异常信息，content是应用ansi-seg分词字段。

**Comment by sunny800629** [comment]
我在AnsjAnalyzer里面增加了一个单个字段识别器`public void recognition(Result result) {
		// 获取词数组
		List<Term> terms = result.getTerms();
		for (Iterator<Term> iterator = terms.iterator(); iterator.hasNext();) {
			Term term = (Term) iterator.next();
			if (term.getName().length() == 1) {
				iterator.remove();
			}
		}
	}`目的是删除单个字符的词。

**Comment by sunny800629** [comment]
并且排在了所有识别器的最后一个。

**Comment by ansjsun** [comment]
你好这个是我的bug..之前有一版分词器posting位置错误...

看这里 https://github.com/NLPchina/ansj_seg/issues/441

**Comment by ansjsun** [comment]
AnsjTokenizer.java 中43行

````
int position = 0; //这里改为0 之前是-1
	@Override
	public final boolean incrementToken() throws IOException {
		if (result == null) {
			parse();
		}
````

**Comment by sunny800629** [comment]
已经解决了，是我在过滤的时候没有考虑位置移动，通过你说的方式也可以解决问题。在incrementToken方法中，通过过滤控制位置移动也可以解决。

**Comment by sunny800629** [comment]
谢谢孙健！

**Comment by ansjsun** [comment]
之前的写法彻底不对..那个写法不能做短语查询..现在改对了..你要是也改过最好check下..之前有个地方我理解有误
