### ISSUE TITLE
最新版（5.1.2）跑ansj_lucene5_plug/HeightLightTest.java时query的分词带问号

### ISSUE THREAD

**Issue by summer7611** [NLPchina/ansj_seg#452]
我跑了ansj_lucene5_plug/HeightLightTest.java这个test，得到的结果如下：

> 不强/v,不/d,强行/d,强/a,行/ng,上下车/vn,上下/f,上/f,下车/vi,下/f,车/n,，/w,做到/v,做/v,到/v,先下/t,先/d,下/f,后上/t,后/f,上/f,，/w,候车/v,候/v,车/n,要/v,排队/v,排/v,队/n,，/w,按/p,秩序/n,秩/ng,序/n,上车/v,上/f,车/n,；/w,下车/v,下/f,车/n,后/f,要/v,等/u,车辆/n,车/n,辆/q,开走/v,开/v,走/v,后/f,再行/d,再/d,行走/v,行/ng,走/v,，/w,如要/c,如/v,要/v,穿越/v,穿/v,越/d,马路/n,马/n,路/n,，/w,一定/d,一/m,定要/b,定/v,要/v,确保安全/ns,确保/v,确/d,保安/b,保/v,安全/ansj,安/ag,全/a,的/uj,情况/n,情/n,况/vg,下/f,穿行/v,穿/v,行/ng,；/w,交通信号/nz,交通/n,交/v,通信/vn,通/v,信号灯/n,信号/n,信/n,号灯/n,号/q,灯/n,的/uj,正确/a,正/d,确/d,使用/v,使/v,用/p,，/w,什么/r,什/ng,么/y,事/n,交通安全/ansj,交通/ansj,交/v,通/v,安全/ansj,安/ag,全/a,出行/v,出/vf,行/ng,交通信号/nz,交通/n,交/v,通信/vn,通/v,信号灯/n,信号/n,信/n,号灯/n,号/q,灯/n,的/uj,正确/a,正/d,确/d,使用/v,使/v,用/p,，/w,什么/r,什/ng,么/y,事/n,交通安全/ansj,交通/ansj,交/v,通/v,安全/ansj,安/ag,全/a,出行/v,出/vf,行/ng
> text:"交通安全 ? 交通 ? ? 交 ? ? ? 通 ? ? ? ? 安全 ? ? ? ? ? 安 ? ? ? ? ? ? 全 ? ? ? ? ? ? ? 出行 ? ? ? ? ? ? ? ? 出 ? ? ? ? ? ? ? ? ? 行"

可见query="\"交通安全出行\""在执行完
`System.out.println(new QueryParser("text", queryAnalyzer).parse(query));` 后，会多出很多问号。而且检索的结果要显示没有命中。

麻烦大大看一下，谢谢

**Comment by ansjsun** [comment]
还真是..我的错误.一直对lucene的 position 一知半解,目前已修复 你再pull下试试
