### ISSUE TITLE
想问下这ansj能支持多线程同时调用么

### ISSUE THREAD

**Issue by NoneElse** [NLPchina/ansj_seg#453]
* 场景是这样，我起一个服务，服务在启动时对ansj做一次初始化，然后再多线程调用```ToAnalysis.parse```或者```NlpAnalysis.parse```，这样会不会有问题？

**Comment by ansjsun** [comment]
不会有问题...多线程可用....

**Comment by ansjsun** [comment]
不会有问题..是线程安全的
