### ISSUE TITLE
使用index分词的phrase问题

### ISSUE THREAD

**Issue by summer7611** [NLPchina/ansj_seg#455]
我用ansj_lucene5_plug\HeightLightTest.java做的测试，将输入修改了一下，如下：

```
		DicLibrary.insert(DicLibrary.DEFAULT, "大", "ansj", 2000);
		DicLibrary.insert(DicLibrary.DEFAULT, "数据", "ansj", 2000);
		DicLibrary.insert(DicLibrary.DEFAULT, "大数据", "ansj", 2000);

		String content = "深圳中商情大数据股份有限公司";
                System.out.println(IndexAnalysis.parse(content));

                String query = "text:\"大数据股份\"";
                // 建立内存索引对象
		index(indexAnalyzer, content);

		// 查询
		search(queryAnalyzer, new QueryParser("text", queryAnalyzer).parse(query));

```

得到的标准输出为：

**深圳/ns,深/a,圳/n,中商/nt,中/f,商情/n,商/vg,情/n**,大数据/ansj,大数/n,大/ansj,数据/ansj,数/n,据/p,股份有限/n,股份/n,股/q,份/q**,有限公司/n,有限/a,有/vyou,限/v,公司/nis,公/ng,司/ng

text:"大数据 大数 大 数据 数 据 股份 股 份"
0**

也就是说content的分词把“股份有限”这个词放在了“股份”前面，导致搜索不到“大数据股份”

对于这种问题，大大有没有解决思路？

**Comment by ansjsun** [comment]
这个是很难解决的问题.

如果把 股份有限,股份 反过来, 变成股份
String query = "text:\"大数据股份\"";这句话是可以有召回的

现在是正向的比如你搜索  String query = "text:\"数据股份有限公司\""; 无法召回了.

建议这种情况精简词典...把"股份有限"这种词语删掉. 

至于是否翻转我还得琢磨下

**Comment by summer7611** [comment]
恩。我的用户词典中没有“股份有限”这个词。我需要怎么做才能屏蔽这个分词？

**Comment by ansjsun** [comment]
这个没有太好的办法。反转后还是有可能出错。所以。最好的方式还是细颗粒度的分词
