### ISSUE TITLE
“女装照”这个词分的有问题

### ISSUE THREAD

**Issue by Alisummer** [NLPchina/ansj_seg#456]
![-2660147d677aee30](https://cloud.githubusercontent.com/assets/7764726/24438163/17b9eac8-140b-11e7-92dc-ad2aa35db8be.jpg)
被分成了 女 装照 😂

**Comment by ansjsun** [comment]
为了分词稳定性建议你用 dicanalysis来分词...nlpanalysis太奔放了....话说你这是从哪弄的这个截图

**Comment by ansjsun** [comment]
我也有 :
http://www.nlpcn.org:9999/api/SegApi/nlpSeg?content=女装照

这个就是对的:
http://www.nlpcn.org:9999/api/SegApi/dicSeg?content=%E5%A5%B3%E8%A3%85%E7%85%A7

**Comment by Alisummer** [comment]
@ansjsun 好吧😂
自己截的呗(
