### ISSUE TITLE
Analysis 能不能增加类似停用词过滤的预处理功能？

### ISSUE THREAD

**Issue by pengfeis** [NLPchina/ansj_seg#457]
能不能增加类似停用词过滤过滤的预处理功能，把一些“噪音”，入空格等字符过滤掉之后再进行分词。

比如"南京 市长江大-桥很漂，亮"的分词结果：
“南京/ns,市/n,长江/ns,大/a,-,桥/n,很/d,漂/v,亮/v”

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/recognition/impl/FilterRecognitionTest.java 这个

**Comment by pengfeis** [comment]
谢谢@ansjsun的快速的回复，如果我没有理解错的话， 上面的StopRecognition是分词后对term做过滤。能不能在parse之前做下预处理，把空格，"-"这些特殊字符去掉，不是分词过后在过滤?

**Comment by ansjsun** [comment]
是的
