### ISSUE TITLE
http://www.nlpcn.org/resource/30这个小说的语料还有没有

### ISSUE THREAD

**Issue by kylinhao** [NLPchina/ansj_seg#458]
百度网盘的链接失效了。。。。

**Comment by ansjsun** [comment]
好像没有了.......

**Comment by wainshine** [comment]
NovelTXT ？我好像有，但是我没有解压密码，下了也没用啊

**Comment by ansjsun** [comment]
@wainshine 解压码我记得是`wenliangbing`或者`wenliangbin`试试

**Comment by wainshine** [comment]
链接: https://pan.baidu.com/s/1slrZadZ 密码: a4hw

**Comment by kylinhao** [comment]
多谢了

**Comment by klisly** [comment]
> @wainshine 解压码我记得是`wenliangbing`或者`wenliangbin`试试

密码是wenliangbin
多谢啊，泪流满面，终于找到密码了
