### ISSUE TITLE
ToAnalysis在用户自定义词典的情况下，是否还应该加载默认词典"library/default.dic"

### ISSUE THREAD

**Issue by selfpoised** [NLPchina/ansj_seg#461]
按照说明文档：https://github.com/NLPchina/ansj_seg/wiki/%E5%88%86%E8%AF%8D%E6%96%B9%E5%BC%8F
“ToAnalysis 精准分词

精准分词是Ansj分词的***店长推荐款***

它在易用性,稳定性.准确性.以及分词效率上.都取得了一个不错的平衡.如果你初次尝试Ansj如果你想开箱即用.那么就用这个分词方式是不会错的.”

对于上述文档，我的直观理解是，不论用户是否自定义词典，ToAnalysis都会使用"library/default.dic"，作为一种快速上手或者不在意词典的情况下使用。

我的使用场景是DicAnalysis 和ToAnalysis并用，用户可以指定分词算法类型。这种情况下指定自定义词典路径：MyStaticValue.ENV.put("dic",ansj_dic_path)。实际上跟踪调试后发现，会由基类Analysis统一加载自定义词典，也就是说ToAnalysis也会使用"library/default.dic"，不知道这个是不是作者的初衷？

尽管可以通过ToAnalysis.parse(text,forests)自己强制创建"library/default.dic"的forests绕过去，但是直观上来说还是会误解。

**Comment by ansjsun** [comment]
"dic" 这个key如果不做更改的话默认就是default.dic , 

当用户一个forsest不传的情况下就用dic这个key的forest,

当用户传size为0 ,的forest的话就一本词典也不用.

你可以ToAnalysis.parse(test,new Forest[0]) ;

是所有的分词算法都支持自定义词典的..dic和to的区别是.自定义词典的优先级dic高于to

**Comment by selfpoised** [comment]
ok，那么也就是说ToAnalysis.parse(test,new Forest[0])，通过new Forest[0]=Library.makeForest(“mydic”)，是可以在具体分词时灵活指定分词词典是吧？我这种用法没有问题吧？

**Comment by ansjsun** [comment]
是的没有问题.... 代码不怎么对.意思对了...
