### ISSUE TITLE
spark 集群上用 ansj 5.0.3 报错

### ISSUE THREAD

**Issue by chenruiSundun** [NLPchina/ansj_seg#462]
17/04/01 10:27:08 ERROR DICLOG: not find field by copyright.string
17/04/01 10:27:08 ERROR DICLOG: not find field by maven.version.number
17/04/01 10:27:08 ERROR DICLOG: not find field by version.number
17/04/01 10:27:08 ERROR DICLOG: not find field by osgi.version.number
17/04/01 10:27:08 WARN DICLOG: Init user library  error :library/default.dic because : not find that file !

**Comment by madong-fun** [comment]
加载路径的问题，如果是启动的spark-shell 在spark-shell启动的路径下 建立library/default.dic，如果是集群，指定spark classpath，要么手动加载

**Comment by madong-fun** [comment]
或者在调用分词前，设置变量
MyStaticValue.ENV.put("dic","doc/analysis_beijing.dic")

**Comment by ansjsun** [comment]
需要增加.ansj_library.properties 指定词典..

当然也可以用 @madong-fun 的方式,对于spark加你加载方式.不要用物理路径可以使用restful的方式来加载.这样词典中央端留一份就可以了.jar包也小
