### ISSUE TITLE
计算二元权重的问题

### ISSUE THREAD

**Issue by endymecy** [NLPchina/ansj_seg#465]
在MathUtil文件中，下面的代码公式前一项加一个常数80000是什么原因？

double value = -Math.log(dSmoothingPara * frequency / (MAX_FREQUENCE + 80000) + (1 - dSmoothingPara) * ((1 - dTemp) * nTwoWordsFreq / frequency + dTemp));

**Comment by ansjsun** [comment]
这个我也不知道了...经验公式吧...拍脑袋写的..

**Comment by endymecy** [comment]
历史终将不了了之
