### ISSUE TITLE
5.1.0版本添加自定义词典失败

### ISSUE THREAD

**Issue by liuboya** [NLPchina/ansj_seg#468]
在添加用户自定义词典时报空指针异常  
 DicLibrary.insert(key, word, "ud", 1000);

报错：
java.lang.NullPointerException
	at org.nlpcn.commons.lang.tire.library.Library.insertWord(Library.java:104)
	at org.nlpcn.commons.lang.tire.library.Library.insertWord(Library.java:75)
	at org.ansj.library.DicLibrary.insert(DicLibrary.java:63)

如果在library.properties中添加了如下配置
dic_entity=library/entity.dic
词典可以像default.dic一样自动加载，是吗？

**Comment by FelixHo** [comment]
1.空指针问题是因为你insert指定的key值不存在，默认词典的key是"dic",即DicLibrary.DEFAULT

2.配置文件这样写 dic_entity=library/entity.dic 可以加载你的自定义词典，此时该词典的key为 dic_entity

- 所以你可以这样添加自定义词典

library.properties：
`dic_entity=library/entity.dic`

- 然后这样往自定义词典插入新词

`DicLibrary.insert("dic_entity"," word", "ud", 1000);`

**Comment by ansjsun** [comment]
@liuboya 
@FelixHo  我把你拉到我们group把...
楼上正解你也可以通过,代码方式制定path


````
String key = "dic_mykey" ;
		DicLibrary.put(key, key, new Forest());
		DicLibrary.insert(key, "增加新词", "我是词性", 1000);
		Result parse = DicAnalysis.parse("这是用户自定义词典增加新词的例子",DicLibrary.gets(key));
		System.out.println(parse);
````
