### ISSUE TITLE
CRF load err Not in GZIP format

### ISSUE THREAD

**Issue by yyd12345** [NLPchina/ansj_seg#469]
大神，我加载自已的CRF模型时，遇到以下错误，请问，如何解决：
四月 11, 2017 10:15:03 上午 org.ansj.library.CrfLibrary error
**严重: org.ansj.domain.KV@ea30797 load err Not in GZIP format**
**四月 11, 2017 10:15:04 上午 org.ansj.library.DATDictionary info**
信息: init core library ok use time : 375
四月 11, 2017 10:15:04 上午 org.ansj.library.NgramLibrary info
信息: init ngram ok use time :304
四月 11, 2017 10:15:04 上午 org.ansj.splitWord.analysis.NlpAnalysis warn
警告: not find any crf model, make sure your config right? 

我的模型是为CRF++在ubuntu和windows7下都生成过，都不行。

**Comment by ansjsun** [comment]
crf是个大坑...我会近期内解决掉的...

**Comment by yyd12345** [comment]
虽然有java.util.zip.ZipException: Not in GZIP format这个错误，但是自定义的CRF是可用的

**Comment by chaoliu1024** [comment]
**org.ansj.domain.KV@77f03bb1 load err Not in GZIP format**
init core library ok use time : 608
init ngram ok use time :575
**not find any crf model, make sure your config right?** 
欢迎/v,使用/v,ansj/en,的/uj,crf/en,功能/n,!

同样有错误提示，但可运行，因此就不清楚到底有没有使用自己训练的CRF模型分词。

**Comment by HuarongLi** [comment]
@ansjsun @yyd12345 遇到相同的问题，问一下要怎么解决呢？

**Comment by HuarongLi** [comment]
已经解决
`NlpAnalysis nlpAnalysis = new NlpAnalysis();`
`nlpAnalysis.setCrfModel(new SplitWord(new CRFppTxtModel().loadModel("library/galaxy.model.txt")));`
`nlpAnalysis.parseStr("str")`
