### ISSUE TITLE
CRF++模型训练失败

### ISSUE THREAD

**Issue by yyd12345** [NLPchina/ansj_seg#470]
608600.. 608700.. 608800.. 608900.. 609000.. 609100.. 609200.. 609300.. 609400.. 609500.. 609600.. 609700.. 609800.. 609900.. 610000.. 610100.. 610200.. 610300.. 610400.. 610500.. 610600.. 610700.. 610800.. 610900.. 611000.. 611100.. 611200.. 611300.. 611400.. 611500.. 611600.. 611700.. 611800.. 611900.. 612000.. 612100.. 612200.. 612300.. 612400.. 612500.. 612600.. 612700.. 612800.. 612900.. 613000.. 613100.. 613200.. 613300.. 613400.. 613500.. 613600.. 613700.. 613800.. **terminate called after throwing an instance of 'std::bad_alloc'**
  what():  std::bad_alloc
Aborted (core dumped)
root@ubuntu:/opt/CRF++-0.58# 

如何解决？

**Comment by yyd12345** [comment]
使用的语料是swresult.txt

**Comment by semsevens** [comment]
@yyd12345 可能是内存不够了, 试着加内存, 或者训练的时候添加 -f 参数, 减少特征试试.

**Comment by UCASREN** [comment]
您好，请问您最后是怎么解决的？

**Comment by HuarongLi** [comment]
@yyd12345 @ansjsun 遇到同样的问题，想问一下最后怎么解决的呢？

**Comment by wutong92120** [comment]
@HuarongLi 我换了一台32G的机器就跑完了
