### ISSUE TITLE
請問有沒有辦法自定義nature

### ISSUE THREAD

**Issue by bejoechen** [NLPchina/ansj_seg#471]
請問一下nature的定義表格在哪？
有沒有辦法自己新增詞性(nature)和生詞呢?
謝謝

**Comment by pengfeis** [comment]
试试这个:
`DicLibrary.insert(DicLibrary.DEFAULT, "hello", "foo", DicLibrary.DEFAULT_FREQ);
 DicLibrary.insert(DicLibrary.DEFAULT, "world", "bar", DicLibrary.DEFAULT_FREQ);`
