### ISSUE TITLE
关于词典路径配置的问题

### ISSUE THREAD

**Issue by madong-fun** [NLPchina/ansj_seg#472]
假如我的词典这样配置的： dic=library/default.dic
在我启动项目时，如果我启动项目时 路径是/home/admin下，词典路径会识别成 /home/admin/library/default.dic ,而不是项目下的文件路径
这种情况下，可以通过设置   System.setProperty("user.dir",""); 解决，也可以配置绝对路径
所以有个疑问，为什么不提供相对路径 词典加载方式？

**Comment by madong-fun** [comment]
@ansjsun

**Comment by ansjsun** [comment]
相对路径。。是相对于项目启动目录和classpath来做的你可以参看 ，fileFinder类这个是寻找文件的方式
