### ISSUE TITLE
关于ansj人名识别理论基础的问题

### ISSUE THREAD

**Issue by Royhoo** [NLPchina/ansj_seg#473]
请问AsianPersonRecognition这个类里面人名识别的算法，是以张华平的论文[基于角色标注的中国人名自动识别研究](https://wenku.baidu.com/view/02a8cc65ddccda38376baf94.html)为理论基础吗？
另外，下面这两行代码：
`allFreq += Math.log(term.termNatures().allFreq + 1);`
`allFreq += -Math.log((freq));`
以"张华平"的"张"为例，term.termNatures().allFreq是"张"出现的总次数，freq是"张"出现在三字人名首位的次数。
以事件A表示：遇到"张"这个字；事件B表示：一个字是三字人名的姓氏。
那么，上面这两行代码，是在求P(B|A)这个条件概率吗？
以上我的理解正确吗？

**Comment by ansjsun** [comment]
好久了..应该是这么搞的...算是基于词的概率计算
