### ISSUE TITLE
CRF模型训练语料格式生成

### ISSUE THREAD

**Issue by chenying99** [NLPchina/ansj_seg#475]
大神好，人民日报分词语料是带词性标注和空格的

我用ansj里面的生成工具生成crf格式语料，里面的斜杠 / 也会生成一行 / M

比如人民日报语料里面可能还带有命名实体  中括号包含的[]

如果是纯粹的以空格隔开的语料 处理没问题

是不是没有对带有词性的语料 没有做处理呢？谢谢

**Comment by ansjsun** [comment]
人民日报的格式需要自己整理成标准的格式.就是一个词一个词.把词性相关的东西去掉..中括号建议合并成一个词语..
