### ISSUE TITLE
下载地址访问不正常

### ISSUE THREAD

**Issue by tianxinghd** [NLPchina/ansj_seg#478]
http://maven.ansj.org/org/ansj/
http://maven.ansj.org/org/ansj/tree_split/
http://maven.ansj.org/org/ansj/ansj_seg/
这几个地址现在都访问不了
Problem accessing /org/ansj/ansj_seg/. Reason:

    Not Found

**Comment by FelixHo** [comment]
下载JAR:
http://maven.nlpcn.org/org/ansj/
或者 maven构建
```
<dependency>
    <groupId>org.ansj</groupId>
    <artifactId>ansj_seg</artifactId>
    <version>5.1.1</version>
</dependency>
```

**Comment by shi-yuan** [comment]
https://mvnrepository.com/artifact/org.ansj/ansj_seg/5.1.1

**Comment by shi-yuan** [comment]
maven中央仓库就有

**Comment by tianxinghd** [comment]
http://maven.ansj.org/org/ansj/tree_split/  这个没有用到了吗？maven上没有了“No sources to compile
”

**Comment by shi-yuan** [comment]
不用了吧
