### ISSUE TITLE
文档一致性问题

### ISSUE THREAD

**Issue by newyangyang** [NLPchina/ansj_seg#479]
我如果要通过 maven 使用，应该使用哪一种方法？是像项目介绍中引入<groupId>org.ansj</groupId>
<artifactId>ansj_seg</artifactId>，还是像 wiki 中一样的写法，还是说他们等价？

另外 wiki 中说：让分词运行需要两个jar，分别是 tree_split 和 ansj_seg 的jar 。但我通过第一种 maven 下载下来的没有 tree_split，有nlp-lang，请问这两个是一回事吗？

Thanks in advance.

**Comment by shi-yuan** [comment]
ansj_seg 就行

```xml
<dependency>
	<groupId>org.ansj</groupId>
	<artifactId>ansj_seg</artifactId>
	<version>5.1.1</version>
</dependency>
```
