### ISSUE TITLE
分词问题

### ISSUE THREAD

**Issue by winboy1988** [NLPchina/ansj_seg#481]
首先感谢开源，辛苦了；然后菜鸟上手，分词一个问题：“续约客服顾问”，为什么自定义添加“续约”都没有办法分对，还是“续约客”。。。表示不理解，有没有哪位大大帮我看看？谢谢

**Comment by ansjsun** [comment]
用DicAnalysis的方式去分词...如果还是关闭人名识别 MyStaticValue.isNameR..=false ;

**Comment by winboy1988** [comment]
谢谢 已经解决
