### ISSUE TITLE
Ansj_seg出现问题

### ISSUE THREAD

**Issue by maybefeicun** [NLPchina/ansj_seg#482]
您好： 
       我使用ansj_seg工具进行中文分词，出现了：
四月 25, 2017 10:01:16 下午 org.ansj.util.MyStaticValue <clinit>
警告: not find library.properties in classpath use it by default !
四月 25, 2017 10:01:16 下午 org.ansj.library.UserDefineLibrary loadLibrary
警告: init userLibrary  warning :E:\dream\file_io\library\default.dic because : file not found or failed to read !
四月 25, 2017 10:01:16 下午 org.ansj.library.UserDefineLibrary initAmbiguityLibrary
警告: init ambiguity  warning :E:\dream\file_io\library\ambiguity.dic because : file not found or failed to read !
四月 25, 2017 10:01:17 下午 org.ansj.library.DATDictionary loadDAT
信息: init core library ok use time :1234
四月 25, 2017 10:01:18 下午 org.ansj.library.NgramLibrary <clinit>
信息: init ngram ok use time :678
我不知道怎么解决，希望大神可以帮帮忙。

**Comment by shi-yuan** [comment]
配置了自定义词典吗，如果没有，这些警告，不用理会

**Comment by moshangshaoguang** [comment]
这不是提示你的ansj中没有这三个文件吗，你补充进去就行了。有个三个文件和没有这个三个文件，对应同一句话时，分词的结果也不一样
