### ISSUE TITLE
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic 

### ISSUE THREAD

**Issue by gravin** [NLPchina/ansj_seg#483]
光快不行啊,这都是啥错啊啥错啊
啥错啊
啥错啊
啥错啊

四月 26, 2017 5:19:56 下午 org.ansj.util.MyStaticValue warn
警告: not find library.properties in classpath use it by default !
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/default.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.DicLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/default.dic file:F:\src\crawel4j_test\library\default.dic not found or can not to read, path: library/default.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
四月 26, 2017 5:19:56 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:F:\src\crawel4j_test\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
四月 26, 2017 5:19:57 下午 org.ansj.library.DATDictionary info
信息: init core library ok use time : 312
四月 26, 2017 5:19:57 下午 org.ansj.library.NgramLibrary info
信息: init ngram ok use time :484

**Comment by shi-yuan** [comment]
应该是词典路径，配置的有问题

**Comment by zgj0607** [comment]
我也有这个问题，我想问一下，字典的路径是在什么地方配置的？在ansj_library.properties的配置感觉没有奏效
我的报错：
org.ansj.library.AmbiguityLibrary] Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:/Users/zhou/library/ambiguity.dic not found or can not to read, path: library/ambiguity.dic
我没有指定路径到我系统用户的home下。

麻烦大神帮我看一下是什么问题？

**Comment by shibing624** [comment]
ansj_library.properties 可以放到resources下看看。
