### ISSUE TITLE
5.1.1版本, 用户自定义词典, 使用配置文件的方式不成功.

### ISSUE THREAD

**Issue by jingwangfei** [NLPchina/ansj_seg#484]
- 在resouce目录中, 新建` library.properties` 文件,
  添加属性. `dic=library/default.dic`

- 在resouce目录下, 创建`library`目录,
  并新建, `default.dic`文件, 
  内容为, `坐着火车  njh 1000`

- String a = "坐着火车去旅行...";
  Result parse = DicAnalysis.parse(a);
 并没有将,  `做着火车` 解析为一个词语

**Comment by jingwangfei** [comment]
上面的问题已经, 解决了. 是路径的问题.

- 配置log4j日志输出, 打印日志
之前, 没有打印日志, 导致错误信息不全, 无法定位详细的错误位置,  因此需要配置log4j日志打印日志.
在resouce目录下, 新建` log4j.properties` 文件,  内容如下
  ```
log4j.rootLogger=INFO,systemOut

#输出到控制台
log4j.appender.systemOut= org.apache.log4j.ConsoleAppender 
log4j.appender.systemOut.layout= org.apache.log4j.PatternLayout 
log4j.appender.systemOut.layout.ConversionPattern= [%-5p][%-22d{yyyy/MM/dd HH:mm:ssS}][%l]%n%m%n 
log4j.appender.systemOut.Threshold= DEBUG 
log4j.appender.systemOut.ImmediateFlush= TRUE 
log4j.appender.systemOut.Target= System.out 
```
日志打印, 提示如下:
`Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/userLibrary.dic file:D:\workspace\idea\spark_01001\library\userLibrary.dic not found or can not to read, path: library/userLibrary.dic`
说明dic词典文件的路径不对.

**Comment by Armstrongya** [comment]
@jingwangfei 请问你最后是怎么解决的呢？单纯的调整dic的文件路径就好了？我遇到跟你一样的问题，即便按照日志里的提示修改了词典路径之后，在dic文件存在的情况下，分词的时候依然没有按照我自定义的词来分。但是我自己用代码显式的添加自定义词汇的时候，是可以按预期分词的。
`      DicLibrary.insert(DicLibrary.DEFAULT, "坐着火车", "n", 1000);//代码显式指定是OK的
        String str1 = "坐着火车去旅行，豌豆荚是个app";
        logger.debug(DicAnalysis.parse(str1).toStringWithOutNature());`

**Comment by ansjsun** [comment]
词典词语之间用 tab 就是\t 就是制表符隔开.

词典必须utf-8编码

看日志路径.词典路径是否正确..

**Comment by Armstrongya** [comment]
@ansjsun 多谢，后来发现是自己在词典词语之间没有用tab 分隔，囧。ps：有一个小疑问，您在设计ansj的时候为何没有把词库位置放在resource目录下呢？毕竟这样看起来使用更方便。

**Comment by eblly** [comment]
同意的 @Armstrongya 的说法，特别是在有多层项目的情况下。

**Comment by ansjsun** [comment]
我考虑考虑是否把根目录改为resource目录
