### ISSUE TITLE
请问可以给一份词性注释表么  

### ISSUE THREAD

**Issue by FayuanLi** [NLPchina/ansj_seg#486]
如题  现在感觉分词功能很强大  现在要对分词结果处理  需要根据词性来做一定处理  只是不知道每个词性指的是什么意思    一些常用的词性还是可以猜出来的  有些就不知道是什么意思了

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/ansj_seg/wiki/%E8%AF%8D%E6%80%A7%E6%A0%87%E6%B3%A8%E8%A7%84%E8%8C%83

**Comment by FayuanLi** [comment]
感谢楼上
