### ISSUE TITLE
"惠城区鹅岭南路" 分词问题

### ISSUE THREAD

**Issue by tianxinghd** [NLPchina/ansj_seg#487]
用在线网址来分词
http://www.nlpcn.org:9999/api/SegApi/nlpSeg?content=惠城区鹅岭南路
结果是{"obj":[{"name":"惠城区鹅岭南路","natureStr":"ns","newWord":true,"offe":0,"realName":"惠城区鹅岭南路"}],"ok":true}

但是我自己用5.1.1版本进行分词，分词结果为 惠城区/ns,鹅/n,岭南/s,路/n。 有什么需要配置的地方吗？

**Comment by ansjsun** [comment]
分词用NlpAnalysis的方式来分

**Comment by tianxinghd** [comment]
看到网址是nlpseg，我用的也是用NlpAnalysis。

Result parse = NlpAnalysis.parse("惠城区鹅岭南路");

**Comment by ansjsun** [comment]
这就奇怪了..应该是可以的你把完整的代码贴一下我看看

**Comment by tianxinghd** [comment]
只是简单的测试分词功能
import org.ansj.domain.Result;
import org.ansj.splitWord.analysis.NlpAnalysis;
import org.ansj.splitWord.analysis.ToAnalysis;



public class WordSegTest {
	
	public static void main(String[] args) {
		
		Result parse = NlpAnalysis.parse("惠城区鹅岭南路");
		System.out.println(parse);
	}

}

**Comment by tianxinghd** [comment]
下载了5.1.2的版本，就可以了

**Comment by ansjsun** [comment]
@tianxinghd 你从哪里下载的5.1.2??我在maven库里没有找到额

**Comment by tianxinghd** [comment]
在git上下载的。 pom上写的版本是5.1.2 
<modelVersion>4.0.0</modelVersion>
	<groupId>org.ansj</groupId>
	<artifactId>ansj_seg</artifactId>
	<packaging>jar</packaging>
	<name>ansj_seg</name>
	<version>5.1.2</version>

**Comment by ansjsun** [comment]
哦晓得了你自己编译的啊
