### ISSUE TITLE
how to add stop words?   version: 5.1.1 main 

### ISSUE THREAD

**Issue by rtygbwwwerr** [NLPchina/ansj_seg#488]
**I add some stop words like this:**
StopLibrary.insertStopWords(StopLibrary.DEFAULT, "的", "呵呵", "哈哈", "噢", "啊");
Result terms = ToAnalysis.parse("英文版是小田亲自翻译的");
System.out.println(terms);

but it seems not work, the output is:
英文版/n,是/v,小田/nr,亲自/d,翻译/v,的/uj

the stop word "的" has been set yet, it still lefts in the result

**Comment by ansjsun** [comment]
you need use stop to  recognition

````
StopLibrary.insertStopWords(StopLibrary.DEFAULT, "的", "呵呵", "哈哈", "噢", "啊");
		Result terms = ToAnalysis.parse("英文版是小田亲自翻译的");
		//使用停用词
		System.out.println(terms.recognition(StopLibrary.get()));
````

**Comment by rtygbwwwerr** [comment]
thanks! it's working
