### ISSUE TITLE
地名分词结果与Demo不符

### ISSUE THREAD

**Issue by CarlDong** [NLPchina/ansj_seg#492]
使用5.1.1版本默认ToAnalysis分词  : 

  val str = "上海市金山区宠魅宠物店"

结果为：

上海市/ns,金/b,山区/n,宠/v,魅,宠物/n,店/n

但在 http://demo.nlpcn.org/demo.jsp# 这个demo中， 该句的分词结果为 ： 
上海市 金山区 宠 魅 宠物店 

其他Analysis方法也尝试了， 均无法获得“金山区”。
因为暂时没有字典训练能力，求助如何调整才能获得如Demo中所示的 ”金山区”一类的地名。

**Comment by ansjsun** [comment]
增加用户自定义词那..`金山区` 
我的demo是加载词典后的结果
