### ISSUE TITLE
core.dic里的内容是怎么来的？里面的结构能解释下不

### ISSUE THREAD

**Issue by 1148270327** [NLPchina/ansj_seg#494]
内部某行：    20110	于	66007	-1	2	{d=1, n=0, ng=0, nr=3, p=1131, v=0}
代码看的迷糊了，分词都是直接从这个core.dic中查词，这里面每一行数据代表什么呢？另外和训练好的crf模型有什么联系？
问题如果太小白还请见谅，谢谢

**Comment by 1148270327** [comment]
另外，发现有些名词我在自定义词典里设置的词如果也在核心词典中、但词性不同，这个自定义词就不会被识别成用户定义的。这是怎么回事

**Comment by MRSUNGIT** [comment]
感觉这个是不是专门为了生成双数组trie树而专门定义的词典结构，我也看不太懂是怎么使用的，需要了解下双数组trie树的实现思想吧

**Comment by 1148270327** [comment]
这个字典结构已经弄明白了，实质上是一个双数组Trie树格式的词典，用文本的形式储存了索引，字串，base，check，status与词性。
      check是check数组的值。check是用来验证这个词是从哪个状态转换过来的。比如是由转换过来的。base[105540] + 21160 = 126700.
      status是term的成词状态：1:继续 2:是个词语但是还可以继续 3:确定。


不过目前依旧没弄清楚core.dic中的词是怎么来的，大概猜测应该来自网络上现有的基本词典构造出来的。
希望我的理解能帮到您。

**Comment by MRSUNGIT** [comment]
你说的对，应该是从网上或者其他途径拿到的词典，构造了双数组trie树，你有没有看过那个Bigram.dic的词典，这个词典是不是有点鸡肋，大多数二元词都不在里面

**Comment by shibing624** [comment]
可以训练自己的词典。训练方法代码已经有提供的。
