### ISSUE TITLE
索引分词IndexAnalysis问题

### ISSUE THREAD

**Issue by springylm** [NLPchina/ansj_seg#497]
初次使用, 运行以下代码:
String str = "洁面仪配合洁面深层清洁毛孔" ;
System.out.println(IndexAnalysis.parse(str));
控制台打印:
洁/ag,面/n,仪/k,配合/v,洁/ag,面/n,深层/b,清洁/a,毛孔/n
这个结果和https://github.com/NLPchina/ansj_seg/wiki/%E5%88%86%E8%AF%8D%E6%96%B9%E5%BC%8F
上面IndexAnalysis写的结果不一样
洁/ag,面/n,仪/k,配合/v,配/v,合/v,洁/ag,面/n,深层/b,深/a,层/qv,清洁/a,清/tg,洁/ag,毛孔/n

请问是什么问题导致的？ansj_seg版本为5.1.1

**Comment by ansjsun** [comment]
应该是没有挂载用户自定义词典
