### ISSUE TITLE
DicAnalysis切词时，有些自定义词未切出来

### ISSUE THREAD

**Issue by liuboya** [NLPchina/ansj_seg#498]
添加了两个自定义词，包括"骁龙"， "魅族"。通过DicAnalysis切不出来，ToAnalysis可以

     String key = "dic_entity" ;
        DicLibrary.put(key, key, new Forest());
        DicLibrary.insert(key, "魅族", "entity", 1000);
        DicLibrary.insert(key, "骁龙", "entity", 1000);
        System.out.println(DicAnalysis.parse("魅族",DicLibrary.gets(key)));
        System.out.println(ToAnalysis.parse("魅族",DicLibrary.gets(key)));
        System.out.println(DicAnalysis.parse("骁龙",DicLibrary.gets(key)));
        System.out.println(ToAnalysis.parse("骁龙",DicLibrary.gets(key)));

result：
魅,族/ng
魅族/entity
骁,龙/n
骁龙/entity

@ansjsun

**Comment by ansjsun** [comment]
请问您的版本是?可能是版本问题.目前在我的代码中是正常的.您可以尝试升级最新版本

````
魅族/entity
魅族/entity
骁龙/entity
骁龙/entity
````

**Comment by liuboya** [comment]
我用的版本是5.1.0 
      <dependency>
            <groupId>org.ansj</groupId>
            <artifactId>ansj_seg</artifactId>
            <version>5.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.ansj</groupId>
            <artifactId>tree_split</artifactId>
            <version>1.5</version>
        </dependency>
        <dependency>
            <groupId>org.nlpcn</groupId>
            <artifactId>nlp-lang</artifactId>
            <version>1.7.2</version>
        </dependency>

**Comment by ansjsun** [comment]
升级到5.1.2 吧.这个版本是有问题的...ps maven只需要些
<dependency>
        <groupId>org.ansj</groupId>
        <artifactId>ansj_seg</artifactId>
        <version>5.1.2</version>
    </dependency>

其他都不用写..
