### ISSUE TITLE
关于数字和数量词的合并有个bug

### ISSUE THREAD

**Issue by chiyang10000** [NLPchina/ansj_seg#499]
parser.setIsQuantifierRecognition(false);
只是把parser的isQuantifierRecognition设置了

而ansj_seg\src\main\java\org\ansj\recognition\arrimpl\NumRecognition.java中
```
			// 如果是数字结尾
			if (MyStaticValue.isQuantifierRecognition && temp.termNatures().numAttr.numEndFreq > 0) {
				terms[i].setName(terms[i].getName() + temp.getName());
				temp = temp.to();
			}
```
访问的还是全局的isQuantifierRecognition

**Comment by ansjsun** [comment]
thx 已修复
