### ISSUE TITLE
运行倒是可以了 不过有一大堆警告

### ISSUE THREAD

**Issue by Azusanya** [NLPchina/ansj_seg#500]
五月 18, 2017 7:47:16 下午 org.ansj.util.MyStaticValue warn
警告: not find library.properties in classpath use it by default !
五月 18, 2017 7:47:16 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/ambiguity.dic
五月 18, 2017 7:47:16 下午 org.ansj.library.AmbiguityLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:C:\App\Java项目\Divid\library\ambiguity.dic not found or can not to read, path: library/ambiguity.dic
五月 18, 2017 7:47:16 下午 org.ansj.dic.impl.File2Stream info
信息: path to stream library/default.dic
五月 18, 2017 7:47:16 下午 org.ansj.library.DicLibrary error
严重: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/default.dic file:C:\App\Java项目\Divide\library\default.dic not found or can not to read, path: library/default.dic
五月 18, 2017 7:47:17 下午 org.ansj.library.DATDictionary info
信息: init core library ok use time : 383
五月 18, 2017 7:47:17 下午 org.ansj.library.NgramLibrary info
信息: init ngram ok use time :425
洁/ag,面/n,仪/k,配合/v,洁/ag,面/n,深层/b,清洁/a,毛孔/n, ,清洁/a,鼻孔/n,面/n,膜/n,碎/a,觉/v,使劲/v,挤/v,才/d,能/v,出/v,一/m,点点/q,皱纹/n, ,脸颊/n,毛孔/n,修复/v,的/uj,看/v,不/d,见/v,啦/y, ,草莓/n,鼻/ng,历史/n,遗留/vn,问题/n,没辙/v, ,脸/n,和/c,脖子/n,差不多/l,颜色/n,的/uj,皮肤/n,才/d,是/v,健康/a,的/uj, ,长期/d,使用/v,安全/an,健康/a,的/uj,比/p,同龄人/n,显/v,小/a,五/m,到/v,十/m,岁/q, ,28/m,岁/q,的/uj,妹子/n,看看/v,你们/r,的/uj,鱼尾纹/n

我已经把ansj_seg-5.1.2，tree_split-1.5，nlp-lang-1.7.2都导入到ClassPath里面了

**Comment by ansjsun** [comment]
这个警告是没有相关词典，加入即可。不影响后续分词
