### ISSUE TITLE
如何去除重复的词？

### ISSUE THREAD

**Issue by wangqianfront** [NLPchina/ansj_seg#503]
欢迎使用ansj_seg,(ansj中文分词)在这里如果你遇到什么问题都可以联系我.我一定尽我所能.帮助大家help everybody.ansj_seg更快,更准,更自由

欢迎/v,使用/v,ansj/en,_,seg/en,ansj/en,中文/nz,分词/v,在/p,这里/rzs,如果/c,你/rr,遇到/v,什么/ry,问题/n,可以/v,联系/v,我/rr,我/rr,一定/b,尽我所能/l,帮助/v,大家/rr,help/en, ,everybody/en,ansj/en,_,seg/en,准/a,自由/a

欢迎 使用 ansj _ seg ansj 中文 分词 在 这里 如果 你 遇到 什么 问题 可以 联系 我 我 一定 尽我所能 帮助 大家 help   everybody ansj _ seg 准 自由 欢迎 

这里分词之后有一些重复性的词，如何去除？

**Comment by hyhyxu** [comment]
set去重吗

**Comment by shibing624** [comment]
你这是用索引分词的结果吗？index是用于搜索处理的，索引分词结果是这样的。如果不用重复的词，请使用BaseAnalysis就可以。
