### ISSUE TITLE
邮箱分词有误

### ISSUE THREAD

**Issue by wangqianfront** [NLPchina/ansj_seg#504]
String str = "欢迎使用ansj_seg,(ansj中文分词)在376921646@qq.com这里如果你遇到什么问题都可以联系我.我一定尽我所能.帮助大家help everybody.ansj_seg更快,更准,更自由,欢迎联系front2015@163.com" ;
System.out.println(ToAnalysis.parse(str).recognition(new EmailRecognition()));

欢迎/v,使用/v,ansj_seg/userDefine,,,(,ansj/en,中文/nz,分词/n,),在/p,376921646/m,@,qq/en,./m,com/en,这里/r,如果/c,你/r,遇到/v,什么/r,问题/n,都/d,可以/v,联系/v,我/r,./m,我/r,一定/d,尽我所能/l,./m,帮助/v,大家/r,help/en, ,everybody/en,./m,ansj_seg/userDefine,更快/d,,,更/d,准/a,,,更/d,自由/a,,,欢迎/v,联系/v,front/en,2015/m,@,163./m,com/en,!

**Comment by ansjsun** [comment]
here https://github.com/NLPchina/ansj_seg/blob/c1924a2fc2c978423f6963ac5dc340c6efc94ac0/src/test/java/org/ansj/recognition/impl/EmailRecognitionTest.java
