### ISSUE TITLE
ambiguityLibrary路径配置不生效bug

### ISSUE THREAD

**Issue by frank20171214** [NLPchina/ansj_seg#508]
健哥好：
      在使用5.1.2版本时发现一个bug，如图

![dingtalk20170601105540](https://cloud.githubusercontent.com/assets/25507367/26662816/218ec45c-46b9-11e7-9bf9-4fa5c13b80c9.png)

配置了ambiguityLibrary为ansj_library/ambiguity.dic，但是加载的时候还是library/ambiguity.dic
麻烦帮忙看下呢

**Comment by ansjsun** [comment]
1.properties 的key写这样

````
#path of userLibrary this is default library
dic=library/default.dic

#path of crfModel
#crf_dic1=library/crf.model

#stop_dic1=library/stop.dic

#redress dic file path
ambiguity=library/ambiguity.dic
synonyms=library/synonyms.dic

#set real name
isRealName=true

#isNameRecognition default true
isNameRecognition=true

#isNumRecognition default true
isNumRecognition=true

#digital quantifier merge default true
isQuantifierRecognition=true



````

`ambiguity=library/ambiguity.dic` 不叫 ambiguityLibrary了

**Comment by buaanie** [comment]
@ansjsun 想问下5.1版本之后这个配置 stop_dic1=library/stop.dic 是不是不起作用？
