### ISSUE TITLE
UserDefineLibrary.removeWord

### ISSUE THREAD

**Issue by hyhyxu** [NLPchina/ansj_seg#510]
3.7.5 UserDefineLibrary.removeWord 会把系统的词也去掉吗？而5以上好像是只会把用户自定义的词去掉

**Comment by shibing624** [comment]
UserDefineLibrary.removeWord 只删自定义词。

**Comment by Inspiring26** [comment]
自定义词典的功能现在不能用了吗？？

**Comment by ansjsun** [comment]
@Inspiring26 放到DicLibrary中了
