### ISSUE TITLE
版本5.1.2 自定义词典切分不准确

### ISSUE THREAD

**Issue by ishoxing** [NLPchina/ansj_seg#511]
---library.properties---

dic=library/userDefault.dic
ambiguityLibrary=library/ambiguity.dic
synonymsLibrary=/library/synonyms.dic

---userDefault.dic---
四川在线	n	1000
滚动新闻	n	1000
四川新闻	n	1000
四川频道 	n	1000

---分词代码---
// DicLibrary.insert(DicLibrary.DEFAULT, "四川频道", "n", 1000);
String str = "四川频道四川在线-滚动新闻";
StopRecognition fitler = new StopRecognition();
//fitler.insertStopWords(new String[] { "四川新闻", "滚动新闻", "_", "-" });
Result result = DicAnalysis.parse(str);
List<Term> terms = result.getTerms();
System.out.println(terms);

---分词结果---
[四川/ns, 频道/n, 四川在线/n, -, 滚动新闻/n]

问题：为什么“四川频道”没有切分出来，其他则切分出来了。但是加上代码DicLibrary.insert(DicLibrary.DEFAULT, "四川频道", "n", 1000);，结果就正确了。

**Comment by shibing624** [comment]
请注意文件格式，我复制你的userDefault.dic之后，四川频道和n之间是空格隔开的，要求是用\t隔开。改正后就可以了。用notepad++或者UE可以很方便看出格式问题，请使用一个好用的文本编辑器。

**Comment by 1148270327** [comment]
之前没有DicAnalysis的时候，我是改的ToAnalysis时修正词典优先的问题。5.1.2版本的自定义词库貌似会丢掉第一个文件的第一行，流读取的时候少了文件与文件间添加换行符。

**Comment by ansjsun** [comment]
现在应该好了。。。。
