### ISSUE TITLE
V5.1.2 NlpAnalysis分词 新词发现出现非汉字非英文非数字字符问题

### ISSUE THREAD

**Issue by MouH** [NLPchina/ansj_seg#512]
以下为代码段和输出结果

        String test = "[科技]速度对比！小米6 大战 三星S8！贵不一定好 这种对比手段特别傻逼～真的。\n" +
                "一点意义也没有～\n" +
                "另外，好好练习你的普通发～";

        KeywordsExtractor k = KeywordsExtractor.getInstance();

        for (Term term : NlpAnalysis.parse(test)) {
            System.out.println(term.getName()+" : "+term.getNatureStr());
        }

[ : null
科技 : n
] : null
速度 : n
对比 : v
！ : w
小米 : n
6 : m
  : null
大战 : n
  : null
三星 : nz
s : en
8 : m
！ : w
贵 : a
不 : d
一定 : d
好 : a
  : null
这种 : r
对比 : v
手段 : n
特别 : d
傻逼 : nw
～真 : nw    => 这里的符号～和真字一起被抽成了一个新词
的 : uj
。 : w

 : null
一点 : m
意义 : n
也 : d
没有 : v
～ : w

 : null
另外 : c
， : w
好好 : d
练习 : v
你 : r
的 : uj
普通 : a
发～ : nw   => 这里的符号～和真字一起被抽成了一个新词

**Comment by ansjsun** [comment]
fixed
