### ISSUE TITLE
NoSuchMethodError的問題

### ISSUE THREAD

**Issue by melonsir7788** [NLPchina/ansj_seg#513]
你好，請教一下，我用ansj_seg-5.1.1、nlp-lang-1.7布置在Java專案中，在運行時init library還沒事，load dic之後就會拋NoSuchMethodError，這是甚麼原因?
六月 10, 2017 11:56:23 下午 org.ansj.util.MyStaticValue info
資訊: init ambiguityLibrary to env value is : library/ambiguity.dic
六月 10, 2017 11:56:23 下午 org.ansj.util.MyStaticValue info
資訊: init isQuantifierRecognition to env value is : true
六月 10, 2017 11:56:23 下午 org.ansj.util.MyStaticValue info
資訊: init isRealName to env value is : true
六月 10, 2017 11:56:23 下午 org.ansj.util.MyStaticValue info
資訊: init isNameRecognition to env value is : true
六月 10, 2017 11:56:23 下午 org.ansj.util.MyStaticValue info
資訊: init synonymsLibrary to env value is : library/synonyms.dic
六月 10, 2017 11:56:23 下午 org.ansj.util.MyStaticValue info
資訊: init isNumRecognition to env value is : true
六月 10, 2017 11:56:23 下午 org.ansj.util.MyStaticValue info
資訊: init dic to env value is : library/default.dic
六月 10, 2017 11:56:23 下午 org.ansj.dic.impl.File2Stream info
資訊: path to stream library/ambiguity.dic
六月 10, 2017 11:56:23 下午 org.ansj.library.AmbiguityLibrary info
資訊: load dic use time:1 path is : library/ambiguity.dic
Exception in thread “main" java.lang.NoSuchMethodError: org.nlpcn.commons.lang.util.logging.LogFactory.getLog()Lorg/nlpcn/commons/lang/util/logging/Log;
at org.ansj.library.DicLibrary.(DicLibrary.java:23)
at org.ansj.splitWord.Analysis.(Analysis.java:67)
at org.ansj.splitWord.analysis.ToAnalysis.(ToAnalysis.java:82)
at org.ansj.splitWord.analysis.ToAnalysis.parse(ToAnalysis.java:90)
at trysplit.test.main(test.java:15)
謝謝

**Comment by shibing624** [comment]
你先clone一下代码看看，是否有在最外层有library的文件夹，下面有ambiguity.dic、default.dic、synonyms.dic等文件及其格式是否正确（均是以\t间隔）。再看一下maven依赖是否正确。

**Comment by melonsir7788** [comment]
抱歉
小弟我不懂maven沒有使用，讓我從頭說細說一次我的問題好了

我開啟一個 Java project
並且加入lib放jar，然後build path
(jar檔來源:
ansj_seg-5.1.1.jar:[url]https://oss.sonatype.org/content/repositories/releases/org/ansj/ansj_seg/[/url]
nlp-lang-1.7.jar:[url]https://oss.sonatype.org/content/repositories/releases/org/nlpcn/nlp-lang/[/url]
)
再將含有.dic檔的library拉進來
將library.properties放進src
(library、library.properties取自[url]https://github.com/NLPchina/ansj_seg[/url])
最後建立類別作測試
(類別測試內容來自[url]http://blog.csdn.net/yongh701/article/details/47271935[/url])

[img]https://lh4.googleusercontent.com/rJDtVdQNkbqmIG7yPsY6dXpAlwj5gLjqk0lCnkds297XhxoIWpVQ1exzNy_wC9VJfeS2XJZQ9yvVvUM=w1366-h662-rw[/img]

結果:
六月 13, 2017 10:21:24 下午 org.ansj.util.MyStaticValue info
資訊: init ambiguityLibrary to env value is : library/ambiguity.dic
六月 13, 2017 10:21:24 下午 org.ansj.util.MyStaticValue info
資訊: init isQuantifierRecognition to env value is : true
六月 13, 2017 10:21:24 下午 org.ansj.util.MyStaticValue info
資訊: init isRealName to env value is : true
六月 13, 2017 10:21:24 下午 org.ansj.util.MyStaticValue info
資訊: init isNameRecognition to env value is : true
六月 13, 2017 10:21:24 下午 org.ansj.util.MyStaticValue info
資訊: init synonymsLibrary to env value is : library/synonyms.dic
六月 13, 2017 10:21:24 下午 org.ansj.util.MyStaticValue info
資訊: init isNumRecognition to env value is : true
六月 13, 2017 10:21:24 下午 org.ansj.util.MyStaticValue info
資訊: init dic to env value is : library/default.dic
六月 13, 2017 10:21:24 下午 org.ansj.dic.impl.File2Stream info
資訊: path to stream library/ambiguity.dic
六月 13, 2017 10:21:24 下午 org.ansj.library.AmbiguityLibrary info
資訊: load dic use time:5 path is : library/ambiguity.dic
Exception in thread "main" java.lang.NoSuchMethodError: org.nlpcn.commons.lang.util.logging.LogFactory.getLog()Lorg/nlpcn/commons/lang/util/logging/Log;
	at org.ansj.library.DicLibrary.<clinit>(DicLibrary.java:23)
	at org.ansj.splitWord.Analysis.<init>(Analysis.java:67)
	at org.ansj.splitWord.analysis.ToAnalysis.<init>(ToAnalysis.java:82)
	at org.ansj.splitWord.analysis.ToAnalysis.parse(ToAnalysis.java:90)
	at trysplit.Test.main(Test.java:14)

網路上有一ˋ些示範(如[url]http://blog.csdn.net/yongh701/article/details/47271935[/url])看起來沒有用maven
雖然我也試了幾種版本
例如網友說是3合一的ansj_seg-3.0等
但我就是裝不起來

懇請賜教，謝謝您

**Comment by shibing624** [comment]
Maven疑难解答

3.0.4等较早的Maven版本可能会产生NoSuchMethodError等异常情况。解决办法是将Maven升级到最新版本。
在安装Maven之后，您还有可能收到如下信息：mvn is not recognised as an internal or external command, operable program or batch file. （无法识别mvn为任何内部或外部命令、可执行文件或批处理文件。）这说明需要在PATH变量中添加Maven，修改方法和其他环境变量一样。

**Comment by wkq278276130** [comment]
add

```text
    <dependency>
            <groupId>org.nlpcn</groupId>
            <artifactId>nlp-lang</artifactId>
            <version>1.7.2</version>
        </dependency>
```
