### ISSUE TITLE
lucene插件是怎么进行停用词过滤的？现在使用的是Lucene6，完全找不到对应的方法啊！

### ISSUE THREAD

**Issue by Recurso** [NLPchina/ansj_seg#514]
Analyzer analyzer = new AnsjAnalyzer(TYPE.nlp_ansj);
 IndexWriterConfig iwc = new IndexWriterConfig(analyzer);
不知道有没有办法给AnsjAnalyzer配置停用词？

**Comment by shi-yuan** [comment]
```java
Map<String, String> args = new HashMap<String, String>();
args.put("type",AnsjAnalyzer.TYPE.nlp_ansj.name());
args.put(StopLibrary.DEFAULT, "停用词典KEY");
args.put(DicLibrary.DEFAULT, "自定义词典KEY");
args.put(SynonymsLibrary.DEFAULT, "同义词典KEY");
args.put(AmbiguityLibrary.DEFAULT, "歧义词典KEY");
args.put("isNameRecognition", "是否开启人名识别, 默认true");
args.put("isNumRecognition", "是否开启数字识别, 默认true");
args.put("isQuantifierRecognition", "是否开启量词识别, 默认true");
args.put("isRealName", "是否保留原字符, 默认false");
Analyzer analyzer = new AnsjAnalyzer(args);
IndexWriterConfig iwc = new IndexWriterConfig(analyzer);
```

**Comment by Recurso** [comment]
@shi-yuan 首先，谢谢您及时的回答，我看到的时候已经是下午了：）十分抱歉没有及时回复您。其次是，这样就能直接过滤停用词，不需要再显示地调用过滤的方法了吗？NlpAnalysis.parse(str, forest)**.recognition(s)**，在手动添加的时候都需要加个.recognition(s)，不知道在lucene插件中有类似的需要吗？

**Comment by Recurso** [comment]
刚刚修改了程序，然而没什么效果啊，加载信息里显示;六月 16, 2017 2:42:25 下午 org.ansj.library.StopLibrary warn
警告: STOP 停用词典KEY not found in config 看样子是找不到文件，但是我在properties里配置了，还有args.put(StopLibrary.DEFAULT, "停用词典KEY");里“停用词典KEY”是做什么用的

**Comment by shi-yuan** [comment]
[配置文件](https://github.com/NLPchina/ansj_seg/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E)里定义的：
```properties
#用户自定词典配置
dic: default.dic #也可以写成 file//default.dic , 如果未配置dic,则此词典默认加载
# http方式加载
#dic_d1: http://xxx/xx.dic
# jar中文件加载
#dic_d2: jar://org.ansj.dic.DicReader|/dic2.dic
# 从数据库中加载
#dic_d3: jdbc:mysql://xxxx:3306/ttt?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull|username|password|select name as name,nature,freq from dic where type=1
# 从自定义类中加载,YourClas  extends PathToStream
#dic_d3: class://xxx.xxx.YourClas|ohterparam

#停用词典配置
#stop: http,file,jar,class,jdbc 都支持
#stop_key1: ...

#歧义词典配置
#ambiguity: http,file,jar,class,jdbc 都支持
#ambiguity_key1: ...

#同义词词典配置
#synonyms: http,file,jar,class,jdbc 都支持
#synonyms_key1: ...
```

**Comment by yanhuasanyue1015** [comment]
@shi-yuan  您好,哪个版本可以使用 StopLibrary 呢?
目前:
 <dependency>
            <groupId>org.ansj</groupId>
            <artifactId>ansj_seg</artifactId>
            <version>5.0.4</version>
        </dependency>

ansj_lucene6_plug-3.7.3.jar,
还有一个小小的问题:
ansj_lucene6_plug-3.7.3.jar可以也上传到maven仓库中就更好了,不然有些可以使用maven进行版本控制,有些不可以,时间短的话还没事儿,时间长了,就很容易忘记了

**Comment by shi-yuan** [comment]
最新版本吧，[5.1.2](https://mvnrepository.com/artifact/org.ansj/ansj_seg/5.1.2)

[ansj_lucene6_plug](https://mvnrepository.com/artifact/org.ansj/ansj_lucene6_plug)包maven仓库中有的
