### ISSUE TITLE
不使用maven的話可以嗎

### ISSUE THREAD

**Issue by momoumn** [NLPchina/ansj_seg#516]
我不想用maven
如果不使用maven的話該怎麼做呢

**Comment by otreven** [comment]
在README中有描述：[下载jar](https://github.com/NLPchina/ansj_seg#下载jar)。
不过没描述清楚，下载后的jar包导入到工程classpath中。

**Comment by shi-yuan** [comment]
自己本地打包或者去maven中央仓库下载
