### ISSUE TITLE
加载自定义词库太耗时，求最佳实践

### ISSUE THREAD

**Issue by frank20171214** [NLPchina/ansj_seg#517]
@ansjsun 健哥你好，我遇到个比较困惑的问题，就是ansj_seg自带的词库里面的词太少，不能覆盖大多数场景下的中文分词，往往会出现一个完整的词被拆分成2个词的情况，如果使用自定义词库的话，加入搜狗词库全部的词，启动时加载又会非常耗时。像这种情况，在实际工程中，一般会采取怎样的方式来处理呢？
我觉得要是有个数量刚刚好，又覆盖了大部分常用词的词典可能会解决这种问题，但是人工去整理添加又会消耗大量的人力成本，所以目前卡在这个地方了。

**Comment by a822631129** [comment]
加入搜狗词库，启动加载耗时，我感觉能接受吧，因为这相当于项目初始化，第一次加载好之后，后边分词的时候很快啊，完全不影响业务。

**Comment by shibing624** [comment]
自定义词典加载慢，而且不经常更改的话，我的处理是放到DoubleArrayTrie中，保存成二进制文件，下次加载时直接加载生成文件，这样的处理就更加载core.dic原理一样，速度也一样快。
