### ISSUE TITLE
java.lang.NoSuchMethodError: org.ansj.splitWord.analysis.ToAnalysis   具体原因找出来了

### ISSUE THREAD

**Issue by yanhuasanyue1015** [NLPchina/ansj_seg#519]
先说下版本:
<dependency>
            <groupId>org.ansj</groupId>
            <artifactId>ansj_seg</artifactId>
            <version>5.1.1</version>
        </dependency>
插件的版本
ansj_lucene6_plug-3.7.3.jar

然后就出错了
打开源码,找到出错的位置:
AnsjAnalyzer中的:
tokenizer = new AnsjTokenizer(new ToAnalysis(reader, new Forest[0]), filter);
然后又打开ToAnalysis,只发现两个构造方法
	public ToAnalysis() {
		super();
	}

	public ToAnalysis(Reader reader) {
		super.resetContent(new AnsjReader(reader));
	}
	
结论:ansj_seg5.1.1跟插件ansj_lucene6_plug-3.7.3不兼容

**Comment by shi-yuan** [comment]
ansj_lucene6_plug使用[5.1.1](https://mvnrepository.com/artifact/org.ansj/ansj_lucene6_plug)以上的

**Comment by yanhuasanyue1015** [comment]
最新版本不就是5.1.1吗

**Comment by shi-yuan** [comment]
[5.1.2.0](https://mvnrepository.com/artifact/org.ansj/ansj_lucene6_plug/5.1.2.0)
