### ISSUE TITLE
library/ 目录没有打包入 jar 包里

### ISSUE THREAD

**Issue by Dieken** [NLPchina/ansj_seg#521]
ansj_library.properties 没打包可以理解，供使用者覆盖，但 library/ 下的 dic 文件没打包导致使用者比较麻烦，README.md 里也没提到这个，issues 里很多人反映这个问题，elasticsearch-analysis-ansj 也有这个问题，导致默认的分词效果很差，修正这个问题后效果好很多。

建议把 library/ 打包进去，6.1 MB 而已，使用者想覆盖的话可以修改 library.properties 定制路径，这样可以避免大家对 ansj 分词质量的误解。

**Comment by ansjsun** [comment]
是的的确美打包进去。。。您提的意见可以考虑。但是现在jar包已经不小了。。需要再思考一下
