### ISSUE TITLE
多线程调用是否会增加效率

### ISSUE THREAD

**Issue by pachirayz** [NLPchina/ansj_seg#524]
1、对同一段文本，直接使用DicAnalysis.parse进行分词；
2、将文本分为N份，N个线程分别调用DicAnalysis.parse去分词
两种方式速度是否有比较大的差别？

分词使用的CPU数是否会由所差别？

**Comment by ansjsun** [comment]
可以提升。。。。

多线程肯定占用更多的cpu。

具体提升和及其性能关系挺大
