### ISSUE TITLE
能否识别一下url？

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#527]
att
我发现ansj一直不管url，然后就会把一个url拆成好多个en。。
于是我自己改了一下，加了个URL类型。
于是我发现每次我想升级ansj我都要把我的改动merge一遍，心好累啊~

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/recognition/impl/URLRecognitionTest.java
