### ISSUE TITLE
标点符号都只显示/w, 没有如文档那样细分，另外英文逗号无法识别

### ISSUE THREAD

**Issue by 1148270327** [NLPchina/ansj_seg#529]
如题，最近在过滤词性分析时，发现词性还有些小bug，不知道是不是我个人使用方式不对造成的，特来请教。

**Comment by ansjsun** [comment]
是的。目前标点词典还是很弱没有很好整理。。你可以通过自定义词典的方式。在分完词后。。做一次词性修正。。可以。。将标点符号的词性修复详细

**Comment by aaronjiu** [comment]
具体怎么写，有没有个例子？

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/recognition/impl/NatureRecognitionTest.java
