### ISSUE TITLE
如何在ansj_library.properties中配置自定义stop词典？

### ISSUE THREAD

**Issue by buaanie** [NLPchina/ansj_seg#533]
现在使用5.1.2版本，发现在properties 按照stop=xx.dic 或者 stop_dic1=xx.dic的方式，无法正确加载停用词典。难道现在无法使用配置方法加载嘛？

**Comment by ansjsun** [comment]
你需要调用`StopRecognition` 来进行停用词处理

参见 https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/recognition/impl/FilterRecognitionTest.java

**Comment by sandyfog** [comment]
我配置了停用词也不行，必须要写代码才行吗？

**Comment by zw231212** [comment]
我的library.properties
![image](https://user-images.githubusercontent.com/12821929/29741510-47c9d220-8aa1-11e7-96d9-a8f7dde40e4e.png)
然后library文件夹是放在和src目录同级的
最后也是能加载的
![image](https://user-images.githubusercontent.com/12821929/29741519-6d3bcbb2-8aa1-11e7-8472-cec51cd37ee9.png)
使用stop_dic1这样的形式不知道能不能行，
但是我自定义的形式dic_person这样的形式是meiyou没有被加载的，（配置被读取了，但是没加载使用词典，于是我将person的词典也放置在了customdic（这个名字是我自己起的名字）目录下于是起了作用）
dic_[key],stop_[key]……这些配置还有待研究。
我的library目录：
![image](https://user-images.githubusercontent.com/12821929/29741540-c2252416-8aa1-11e7-9aa6-09e46fd91667.png)

**Comment by zw231212** [comment]
最后附上wiki里面的配置说明网址：[配置网址](https://github.com/NLPchina/ansj_seg/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E)

**Comment by buaanie** [comment]
@zw231212 非常感谢！我试试，最开始我也发现加载了词典但是不生效，读源代码发现其实默认只读取了歧义词典和默认词典。。
