### ISSUE TITLE
作者可不可以兼容一下Android

### ISSUE THREAD

**Issue by longwangzhimian** [NLPchina/ansj_seg#536]
我使用Android Studio跑了个项目，在上面导入SDK并且分词是没问题的，但是如果使用词典和纠正语句会有问题，主要是的ambiguity.dic等文件配置的问题。还有就是好像很多关键词改了，但是没有更新操作文档（*—*）。

**Comment by ansjsun** [comment]
后续会就考虑如何兼容android感谢你的提议
