### ISSUE TITLE
“吃饭”这个词的分词不一致问题

### ISSUE THREAD

**Issue by weiweiwang** [NLPchina/ansj_seg#537]
尝试了ToAnalysis和IndexAnalysis
吃饭->吃/v,饭/n
提醒我吃饭吧->提醒/v,我/r,吃饭/v,吧/y
提醒我吃饭->提醒/v,我/r,吃/v,饭/n

**Comment by ansjsun** [comment]
起始于一个例子

他 马上 就 下来 了
他 从 马 上 掉了 下来

你懂的，这种问题可以通过挂载自定义词典来解决
