### ISSUE TITLE
分词时遇到回车换行符应该怎么办？

### ISSUE THREAD

**Issue by henghanan** [NLPchina/ansj_seg#538]
hi，请问下，如果要对一篇文章进行分词，里面有回车换行符，应该怎么办才好呀？
比如：`中华人\r\n民共和国`

**Comment by ansjsun** [comment]
把换行替换掉把。。 replace \r \n

**Comment by henghanan** [comment]
如果换行符左右是英文的话，直接去掉换行符又会有问题，比如ansj\r\nseg，要判断了。。。

**Comment by ansjsun** [comment]
这个的确是需要自己判断的。。原始文本的格式问题。这个锅分词背不起呀

**Comment by henghanan** [comment]
哈哈，对一整篇文章分词好像确实比较麻烦
