### ISSUE TITLE
加载CRF模型问题

### ISSUE THREAD

**Issue by jhao104** [NLPchina/ansj_seg#540]
wiki中说的加载crf模型使用这样的代码:
```MyStaticValue.CRF.put(MyStaticValue.CRF_DEFAULT,"/Users/sunjian/Documents/src/CRF++-0.58/test/model.txt")```

但是我下载的最新的代码中 `MyStaticValue`并没有 `CRF.put()`这个方法。

这是文档没更新吗？如果是文档没有更新，能否说下正确的加载方法？

**Comment by ansjsun** [comment]
有个CRFLibrary. 可以试试

**Comment by jhao104** [comment]
@ansjsun 搞定了。正确方法应该是:
`MyStaticValue.putLibrary(CrfLibrary.DEFAULT, "/src/main/resources/model.txt");`

j建议更新下wiki

**Comment by jhao104** [comment]
感谢
