### ISSUE TITLE
你好，孙健，我想知道动态添加用户自定义的词，为何在配置文件里看不到新添加的内容呢，或者说这种方式新添加的词添加到什么地方了？

### ISSUE THREAD

**Issue by jurfliu** [NLPchina/ansj_seg#542]
/**
* 动态添加删除用户自定义词典!
* 
* @author ansj
* 
*/
public class DynamicWordDemo {
public static void main(String[] args) {
// 增加新词,中间按照'\t'隔开
UserDefineLibrary.insertWord("ansj中文分词", "userDefine", 1000);
List<Term> terms = ToAnalysis.parse("我觉得Ansj中文分词是一个不错的系统!我是王婆!");
System.out.println("增加新词例子:" + terms);
// 删除词语,只能删除.用户自定义的词典.
UserDefineLibrary.removeWord("ansj中文分词");
terms = ToAnalysis.parse("我觉得ansj中文分词是一个不错的系统!我是王婆!");
System.out.println("删除用户自定义词典例子:" + terms);
}
}

问题疑惑：
通过上面的代码，动态添加用户自定义的词，这些词被添加到什么地方了？或者怎么看到新添加的词？

**Comment by jurfliu** [comment]
麻烦，各位大牛，看一下这个问题

**Comment by ansjsun** [comment]
动态添加是放到内存中的。一重启就没了。。

加入到默认的自定义词典中了。

还有这段代码是老版本的了。现在已经改成DicLibrary来替代了
