### ISSUE TITLE
ansjTokenizer 去掉了 \n

### ISSUE THREAD

**Issue by Waterimelon** [NLPchina/ansj_seg#543]
我想做 paragraph search， 但是发现 ansjTokenizer 把 /n 去掉了，导致
无法提取 paragraph endings 的信息了，怎么解决？ 谢谢！！！

**Comment by Waterimelon** [comment]
ansjTokenizer 中调用的是 Analysis 的 parse() 无参方法，
他会寻找子类通过构造方法传入的reader去分词。
这种调用方式就会把 \n 给去掉。
所以是不是只能去改 ansjTokenizer 的调用方式了 ？

**Comment by ansjsun** [comment]
这个是我用AnsjReader重写了bufferedreader 。造成的。因为我需要取得正确的位置。有的文本换行是\r\n . 会造成标红错位。。paragraph search我不太了解其工作原理，如果你有需要。目前只能自己分好段落再传入到分词器中了。
