### ISSUE TITLE
你好，请问我想通过自定义词典来进行分词，自定义词典中的词是要手工添加吗？还有就是怎么把DicAnalysis分词的结果输出来保存到本地，以txt文本的形式保存？本人是个程序菜鸟，望指导下，非常感谢！

### ISSUE THREAD

**Issue by wangyongmas** [NLPchina/ansj_seg#545]

**Comment by buaanie** [comment]
工程library里面有default.dic，你仿照着自定义就可以，用配置或者程序加载都可以，分词结果调用tosting或者toStringWithoutNature输出结果，自己选择保存方式。

**Comment by wavwind** [comment]
小白求教， 我是下了你的jar包， 想增加自定义词典怎么办呢。  下的5.1.3没有看到default.dic啊

**Comment by wavwind** [comment]
大神能说下default.dic里的最后一列数字是什么意思吗？  另外第二列的词性对结果也没有影响？ 还是说只是个类似注释的东西？

**Comment by ansjsun** [comment]
参见wiki
