### ISSUE TITLE
关于添加自定义词无法写入到词典文件中

### ISSUE THREAD

**Issue by jiangjing32** [NLPchina/ansj_seg#546]
你好，当使用
`DicLibrary.insert("dic_user", "我想要", "ud", 1000);`
动态添加自定义词到自定义词典时，虽然后续分割有效果，但程序运行结束后，“我想要”这个词并不会被写入到词典中，请问怎样才能将词永远写到文件中？或者运行时批量导入新定义词？

**Comment by ansjsun** [comment]
手动写进去。。通过这种方式。只是在内存中动态添加
