### ISSUE TITLE
最新版的，同义词要怎么配才生效啊，synonyms.dic

### ISSUE THREAD

**Issue by WeiSam** [NLPchina/ansj_seg#547]
最新版的，同义词要怎么配才生效啊，synonyms.dic，试了好几次都不成功，到底要怎样才能使同义词功能生效，还有用户自定义词典和同义词一起使用，然后找去其中一个，麻烦大神求解，在线等，急，谢谢！！！！

**Comment by shi-yuan** [comment]
[配置文件说明](https://github.com/NLPchina/ansj_seg/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E)

**Comment by WeiSam** [comment]
试了但是不生效，麻烦详细说明一下好吗

配置文件是这样的

#path of userLibrary
synonyms_[key]=library/synonymsLibrary.dic
dic=library/userLibrary.dic
ambiguityLibrary=library/ambiguity.dic
isNumRecognition=true

**Comment by shi-yuan** [comment]
```java
new NlpAnalysis()
                .setIsNumRecognition(MyStaticValue.isNumRecognition)
                .setAmbiguityForest(AmbiguityLibrary.get("ambiguityLibrary"))
                .setForests(DicLibrary.get("dic"))
                .parseStr("测试文本")
                .recognition(new SynonymsRecgnition("synonyms_[key]"))
```

**Comment by WeiSam** [comment]
但是要和DicAnalysis自定义词典一起使用，可以吗，自定义词典可以生效，但是同义词词典就不管用了，想这样，市桥	市桥街道	市桥大街	市桥街
番禺	番禺市
试了好多遍，都不行，实在是没辙了，能给个完整的案例吗？万分感谢！！！

**Comment by shi-yuan** [comment]
library.properties:
```properties
synonyms_custom=library/synonyms.dic
dic_custom=library/userLibrary.dic
```
synonyms.dic:
```
市桥	市桥街道	市桥大街	市桥街
```
userLibrary.dic:
```
市桥	a	2000
```
TestCase:
```java
new DicAnalysis()
                .setForests(DicLibrary.get("dic_custom"))
                .parseStr("市桥")
                .recognition(new SynonymsRecgnition("synonyms_custom")).forEach(t -> {
            System.out.println("Name: " + t.getName());
            System.out.println("Nature: " + t.getNatureStr());
            System.out.println("Synonyms: " + t.getSynonyms());
            System.out.println("Offset: " + t.getOffe());
            System.out.println("RealName: " + t.getRealName());
        });
```
Result:
![image](https://user-images.githubusercontent.com/8057153/30408739-62c108e6-9933-11e7-9a2f-78c0305bc652.png)

**Comment by WeiSam** [comment]
请问t是什么？

**Comment by shi-yuan** [comment]
是指[词性](https://github.com/NLPchina/ansj_seg/wiki/%E8%AF%8D%E6%80%A7%E6%A0%87%E6%B3%A8%E8%A7%84%E8%8C%83)？

**Comment by WeiSam** [comment]
t -> {
            System.out.println("Name: " + t.getName());
            System.out.println("Nature: " + t.getNatureStr());
            System.out.println("Synonyms: " + t.getSynonyms());
            System.out.println("Offset: " + t.getOffe());
            System.out.println("RealName: " + t.getRealName());

这里的t

**Comment by shi-yuan** [comment]
哦，这是java8的lambda表达式

**Comment by WeiSam** [comment]
好，非常感谢，请问对于地址分词有什么好的方案吗？我能想到的就是使用自定义字典，但建字典很麻烦

**Comment by shi-yuan** [comment]
我所知道的，如您所说，也就是`分词器 + 自定义词表`

**Comment by WeiSam** [comment]
非常感谢您的解惑！！！

**Comment by shi-yuan** [comment]
![image](https://user-images.githubusercontent.com/8057153/30463160-c425edb2-99fc-11e7-9070-de13478b8015.png)bukeqi不客气

**Comment by WeiSam** [comment]
请问部署到tomcat上后字典文件就找不到了，而且读取字典的路径不是tomcat下的而是eclipse下项目存放的路径，怎么解啊？

**Comment by ansjsun** [comment]
tomcat 如果相对路径。。默认根目录是在tomcat/bin目录下，绝对路径看ansj_library.properties。

你是否把properties文件打包到jar里面了？

**Comment by WeiSam** [comment]
没有啊，properties文件放到resource目录下，自定义字典的路径是写相对路径，dic=library/userLibrary.dic
，tomcat部署后执行action时，报的是说在eclipse的工作路径下找不到userLibrary.dic。部署到tomcat执行时寻找字典文件不是应该要到tomcat的webapp目录下找吗，项目是要部署到Linux上执行的

**Comment by ansjsun** [comment]
把这个文件 https://github.com/NLPchina/ansj_seg/blob/master/ansj_library.properties  放到你的classpath下面。把里面路径写对了。。

**Comment by WeiSam** [comment]
用到是5.x的啊，ansj_library.properties 文件是放在classpath路径下，但是执行项目时不是在tomcat部署项目里找字典文件的，而是yEclipseWorkspaces路径下找的
