### ISSUE TITLE
想问一下，地名和机构名的识别是单纯根据词典的吗？还是有类似人名的算法？

### ISSUE THREAD

**Issue by LuckQQ** [NLPchina/ansj_seg#548]

**Comment by ansjsun** [comment]
机构名用的crf 。用nlpanalysis可以识别部分机构名。 最早以前的版本是类似人名的算法

**Comment by LuckQQ** [comment]
@ansjsun  你好。
我现在是想把 ansj 的分词结果作为输入整合到我的实体识别中，但是我想要的分词结果是不带任何实体识别的纯分词（用的ToAnalysis分词）。不走 userDefineRecognition  好像可以达到这个目的，因为我看词典里人名地名机构名的标注占了一部分。所以我想问一下，不使用自带的用户自定义词典对于纯分词的准确率影响大不大呢？

**Comment by LuckQQ** [comment]
还有一个问题，关掉人名识别后输入“陈晓燕”，分词结果是“陈晓/nr, 燕/nr”。
这个词性标注就是这样的吗？虽然关掉人名识别，但是词性仍然是 nr .

**Comment by ansjsun** [comment]
是词典中有陈晓这个词造成的。
你可以用BaseAnalysis进行分词。这个是最细颗粒度的。
