### ISSUE TITLE
加载MySQL中的词典的方法

### ISSUE THREAD

**Issue by charlesqzy** [NLPchina/ansj_seg#550]
大师，能否提供从mysql中加载词典的样例代码？
使用wiki中的方式，在library.properter文件中定义了dic_mysql，系统启动时，打印以下信息，但实测词典无效。
init dic_mysql to env value is : jdbc://jdbc:mysql://10.10.102.201:3306/betty?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull|betty|********|select name,nature,freq from dic_bot

具体该如何使用呢？

**Comment by ansjsun** [comment]
这个是加载成果了。。但是你词典命名是dic_mysql , 所以你分词的时候需要制定这个词典。。DicAnalysisi.parse("","dic_mysql") ;或者你把dic_mysql 改为dic=....则是默认词典了

**Comment by charlesqzy** [comment]
public static Result parse(String str, Forest... forests);;;;;
DicAnalysisi.parse()第二个参数是Forest，但是Library.makeForest()只能传一个文件path作为参数，dic_mysql传进去不行。
不知道是不是版本的问题。
另外也尝试了“把dic_mysql 改为dic=....”，用DicAnalysisi.parse(“2017年销量”)，任然是系统默认的词典标注。

**Comment by shi-yuan** [comment]
```java
DicAnalysis.parse("", DicLibrary.get("dic_mysql"))
```

**Comment by ansjsun** [comment]
如果你需要让你的自定义词性优先用如下方式

System.out.println(NlpAnalysis.parse("结婚的和尚未结婚的孙建是一个好人").recognition(new NatureRecognition(DicLibrary.get("dic_mysql"))));

**Comment by charlesqzy** [comment]
@shi-yuan 多谢，可以使用。
@ansjsun ，使用下面的方式，也是自定义词典优先：
 Forest forest = DicLibrary.get("dic_mysql");
        MyStaticValue.putLibrary(DicLibrary.DEFAULT, "", forest);
        System.out.println(DicAnalysis.parse(str));
