### ISSUE TITLE
英文单词被拆分

### ISSUE THREAD

**Issue by yaojl2006** [NLPchina/ansj_seg#551]
您好，我在使用ansj（version：5.1.1）进行分词时发现英文长单词有时会以字母o为中心被拆分，请问这是为什么？谢谢！

原句：以二羟基二过碘酸合镍(IV)钾（Potassium Diperiоdatоnickelate）或二过碘酸合铜（III）钾（potassium diperiodatocuprate (III)）作为引发剂为合成纳米粒，用作药物传递载体。
分词结果：[以/p, 二/m, 羟基/n, 二/m, 过/ug, 碘/n, 酸合/nw, 镍/n, (, iv/en, ), 钾/n, （/w, potassium/en,  , diperi/en, о, dat/en, о, nickelate/en, ）/w, 或/c, 二/m, 过/ug, 碘/n, 酸/n, 合铜/nw, （/w, iii/en, ）/w, 钾/n, （/w, potassium/en,  , diperiodatocuprate/en,  , (, iii/en, ), ）/w, 作为/v, 引发剂/nw, 为/p, 合成/v, 纳米粒/nr, ，/w, 用作/v, 药物/n, 传递/v, 载体/n, 。/w]

这里的字母o后面也没有显示词性，很奇怪

**Comment by ansjsun** [comment]
在demo中并没有出现此问题http://demo.nlpcn.org/demo.jsp 可能是你文本的确有某个不可见字符。。

**Comment by yaojl2006** [comment]
试了一下似乎确实是字符的问题，多谢
