### ISSUE TITLE
请教下，Lucene7、如何结合anjs关键字提取功能

### ISSUE THREAD

**Issue by chenmurong88** [NLPchina/ansj_seg#552]
`
public List<NsEntity> searchRecord(String key) throws Exception {

        List<NsEntity> nsEntityList = new ArrayList<NsEntity>();
        Directory dir = FSDirectory.open(Paths.get(file_path));
        IndexReader reader = DirectoryReader.open(dir);
        IndexSearcher is = new IndexSearcher(reader);
        BooleanQuery.Builder booleanQuery = new BooleanQuery.Builder();
        PerFieldAnalyzerWrapper analyzer = new PerFieldAnalyzerWrapper(new AnsjAnalyzer(TYPE.index_ansj));

        QueryParser parser = new QueryParser("key", analyzer);
        Query query = parser.parse(key);

        booleanQuery.add(query, BooleanClause.Occur.SHOULD);

        TopDocs hits = is.search(booleanQuery.build(), 100);

        for (ScoreDoc scoreDoc : hits.scoreDocs) {

            Document doc = is.doc(scoreDoc.doc);

            NsEntity nsEntity = new NsEntity();
            nsEntity.setcId(doc.get(("id")));
            nsEntity.setcContent(doc.get(("content")));

            nsEntityList.add(nsEntity);
        }

        return nsEntityList;
    }
`

      刚刚接触anjs，感觉这个分词器很强大，但是还有很多弄不明白的地方，所以想请教下，上面这段代码能否继续优化？
比如：我想要投诉XXX。
这句话分词出来，假设关键字是“投诉”，但是上面字段代码，会把包含“我”、“要”等分词的词条也搜索出来，如果只搜索“投诉”，应该怎么改呢？

**Comment by ansjsun** [comment]
这个只能你针对query判断出来用户的意图是什么。
然后重新构造query 了
