### ISSUE TITLE
ansj可以通过配置文件配置同义词吗，可以的话怎么配置？

### ISSUE THREAD

**Issue by jurfliu** [NLPchina/ansj_seg#554]

**Comment by shi-yuan** [comment]
See issue [最新版的，同义词要怎么配才生效啊，synonyms.dic](https://github.com/NLPchina/ansj_seg/issues/547)

**Comment by jurfliu** [comment]
new NlpAnalysis()
                .setIsNumRecognition(MyStaticValue.isNumRecognition)
                .setAmbiguityForest(AmbiguityLibrary.get("ambiguityLibrary"))
                .setForests(DicLibrary.get("dic"))
                .parseStr("测试文本")
                .recognition(new SynonymsRecgnition("synonyms_[key]"))
这段代码，ansj_seg-1.4.jar，tree_split-1.4.jar这两个jar包没有上面的方法，是jar包版本低吗？

**Comment by shi-yuan** [comment]
以上的示例是用的新的版本
