### ISSUE TITLE
jar 版本号没有对应的ansj分支branch

### ISSUE THREAD

**Issue by hefeiyun** [NLPchina/ansj_seg#555]
jar版本5.x, branch只有3.x

**Comment by ansjsun** [comment]
并没有一个版本打一个分值。。5.x是master版本

**Comment by zhanghuaren** [comment]
希望发jar包能前打个tag。
冒昧地推荐一个git分支模型：
https://mp.weixin.qq.com/s?__biz=MjM5MzA0OTkwMA==&mid=210436461&idx=2&sn=0e097ed80074c6fc9641c738511d5bd6#rd

**Comment by ansjsun** [comment]
@zhanghuaren 您教训的是。我改
