### ISSUE TITLE
定制自己CRF模型，百度网盘里的测试语料，是否需要保留标注的词性

### ISSUE THREAD

**Issue by chaoliu1024** [NLPchina/ansj_seg#556]
根据wiki的给的教程：[定制你自己的CRF模型](https://github.com/NLPchina/ansj_seg/wiki/%E5%AE%9A%E5%88%B6%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84CRF%E6%A8%A1%E5%9E%8B)，提供的测试语料标注了词性，如下
```
迈向/v  充满/v  希望/n  的/u  新/a  世纪/n  ——/w  一九九八年/t  新年/t  讲话/n  （/w  附/v  图片/n  1/m  张/q  ）/w

中共中央/nt  总书记/n  、/w  国家/n  主席/n  江泽民/nr

（/w  一九九七年/t  十二月/t  三十一日/t  ）/w

12月/t  31日/t  ，/w
中共中央/nt  总书记/n  、/w  国家/n  主席/n  江泽民/nr  发表/v  1998年/t  新年/t  讲话/n  《/w  迈向/v  充满/v  希望/n  的/u  新/a  世纪/n  》/w  。/w
（/w  新华社/nt  记者/n  兰红光/nr  摄/Vg  ）/w
```

但在教程中的准备训练语料，没有标注词性，如下显示
```
在	1998年	来临	之际	，
我	十分	高兴	地	通过	中央	人民	广播	电台	、	中国	国际	广播	电台	和	中央	电视台	，
向	全国	各	族	人民	，
向	香港	特别	行政区	同胞	、	澳门	和	台湾	同胞	、	海外	侨胞	，
向	世界	各	国	 的	朋友	们	，
致以	诚挚	的	问候	和	良好	的	祝愿	！
```
详细阅读了5.1.5版本，MakeTrainFile的源码，若单词包含词性时，打**字标注类型**SBME时，词性也会被打在内，这样生成的train.txt中，E 始终标注为 en1

因此，有点疑问
1. 打SBME时，词性不应该包含在内吧？
2. 百度网盘中给的测试语料，需要进行处理，去掉词性的吧？

**Comment by chaoliu1024** [comment]
该问题已回答过了，见：[issues#475](https://github.com/NLPchina/ansj_seg/issues/475)。
另外，在[定制你自己的CRF模型](https://github.com/NLPchina/ansj_seg/wiki/%E5%AE%9A%E5%88%B6%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84CRF%E6%A8%A1%E5%9E%8B)教程中，最后利用训练出来的模型分词，在ansj_seg5.1.3中，直接使用是报错的。
源码要改点：CrfLibrary.java
`SplitWord crfSplitWord = new SplitWord(Model.load(CRFModel.class, is));`
改为：
`SplitWord crfSplitWord = new SplitWord(Model.load(CRFppTxtModel.class, is));`

**Comment by ansjsun** [comment]
这个。。你需要调用CRFppTxtModel.load()吧
