### ISSUE TITLE
FilterModifWord停用词过滤好像没有了？

### ISSUE THREAD

**Issue by wilsonliuliu** [NLPchina/ansj_seg#557]
看示例有这个功能：
//增加两个停用词
FilterModifWord.insertStopWord("并且") ;
FilterModifWord.insertStopWord("但是") ;

但是导入和查看代码都没有找到这个函数，这个版本是取消了吗？5.1.3版本

**Comment by shi-yuan** [comment]
[StopLibrary](https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/library/StopLibrary.java) & [StopRecognition](https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/recognition/impl/StopRecognition.java)
