### ISSUE TITLE
请问如何同时加载多个dic词库？

### ISSUE THREAD

**Issue by arraysnow** [NLPchina/ansj_seg#558]
因为需求特殊，所以需要同时加载两个DicLibrary的词库
类似于这样吧：new UserDicNatureRecognition(forestsDIC1, forestsDIC2, forestsDIC3);

但是我看到DicLibrary.get(key)或者DicLibrary.put(key,   path)只能将名为“dic”的词库覆盖掉

所以有什么办法来使“dic”/"dic1"/"dic2"，这样的Forests同时存在？
@ansjsun

**Comment by ansjsun** [comment]
ToAnalysis.parse(content,DicLibrary.get(词典1),DicLibrary.get(词典2),DicLibrary.get(词典3))

ps:词典是有优先级的。前面的分词结果和后面发生交叉。前面词典优先
