### ISSUE TITLE
入门 新手 疑问

### ISSUE THREAD

**Issue by ambjlon** [NLPchina/ansj_seg#562]
刚接触自然语言处理的新人, 简单了解了几天后, 有下面这些主要的疑问, 希望有人可以帮我解惑. 这些问题也是新手共有的吧.

1. 四个分词方式分别使用了什么算法? 都是基于统计学习的算法吗?
2. 只有crf支持用户训练新的模型吗? ansj自带hmm crf模型是基于什么语料训练出来的呢?
3. 用户自定义词典起什么作用? 实现上怎么起作用的呢?

**Comment by shibing624** [comment]
代码有写呀。
