### ISSUE TITLE
NlpAnalysis里看不到词性标注呢...

### ISSUE THREAD

**Issue by ambjlon** [NLPchina/ansj_seg#563]
NlpAnalysis有一句注释:

// 词性标注
List<Term> result = getResult();

但是这里并没有词性标注NatureRecognition.recognition的调用呢, 其他地方也没看到....

**Comment by ansjsun** [comment]
默认词性是这个词语词频最高的的词性。。所以没有进行标注。如果需要标注。才走naturerecognition

**Comment by ambjlon** [comment]
恩 谢谢你的回复.
这样的话, 如果我有需要  还得自己修改源码吧?

**Comment by ansjsun** [comment]
嗯好的。如果有其他建议可以提哈。。
