### ISSUE TITLE
Ansj并没有使用HMM做分词吧?

### ISSUE THREAD

**Issue by ambjlon** [NLPchina/ansj_seg#564]
Ansj分词的最核心过程在于Graph类的构图以及实施了viterbi(或者只是Dijkstra算法)的walk函数, 这些算是基于统计的分词方法吧, 并不是基于HMM的.
当然, 在NlpAnalysis中有使用crf进行分词做新词发现.

**Comment by ansjsun** [comment]
hmm就是基于统计出来的

**Comment by ambjlon** [comment]
奥, 也可以这么说吧
