### ISSUE TITLE
请问一下 同义词 怎么测试？

### ISSUE THREAD

**Issue by iusofts** [NLPchina/ansj_seg#566]
看了下文档 没有同义词相关测试介绍 同义词已经加载 然后调用IndexAnalysis.parse(str) 没效果

**Comment by shi-yuan** [comment]
```java
new IndexAnalysis()
                .setForests(DicLibrary.get("dic_custom"))
                .parseStr(str)
                .recognition(new SynonymsRecgnition("synonyms_custom")).forEach(t -> {
            System.out.println("Name: " + t.getName());
            System.out.println("Nature: " + t.getNatureStr());
            System.out.println("Synonyms: " + t.getSynonyms());
            System.out.println("Offset: " + t.getOffe());
            System.out.println("RealName: " + t.getRealName());
        });
```
或者
在配置文件里配置synonyms，然后IndexAnalysis.parse(str)

**Comment by iusofts** [comment]
@shi-yuan  好的 谢谢  再请问一下 我在elasticsearch-analysis-ansj里面配置了synonyms es启动的时候提示也加载了
但是测试index_ansj 没把同义词提取出来 是用的方式不对 还是遗漏了配置项？

**Comment by shi-yuan** [comment]
plugin版本是？配置文件是怎么配置的？

**Comment by iusofts** [comment]
# 全局变量配置方式一
ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  #用户自定词典配置
  #dic: default.dic #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
  dic: plugins/elasticsearch-analysis-ansj/mydic/
 # http方式加载
  #dic_d1: http://xxx/xx.dic
  # jar中文件加载
  #dic_d2: jar://org.ansj.dic.DicReader|/dic2.dic
  # 从数据库中加载
  #dic_d3: jdbc:mysql://xxxx:3306/ttt?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull|username|password|select name as name,nature,freq from dic where type=1
  # 从自定义类中加载,YourClas  extends PathToStream
  #dic_d3: class://xxx.xxx.YourClas|ohterparam

  #过滤词典配置
  #stop: http,file,jar,class,jdbc 都支持
  #stop_key1: ...
  stop: plugins/elasticsearch-analysis-ansj/stop/
  #stop_key1: file://extra_stopword.dic

  #歧义词典配置
  #ambiguity: http,file,jar,class,jdbc 都支持
  #ambiguity_key1: ...

  #同义词词典配置
  #synonyms: http,file,jar,class,jdbc 都支持
  #synonyms_key1: ...
  synonyms: plugins/elasticsearch-analysis-ansj/synonyms/

调用接口
http://192.168.1.231:9201/_analyze?text=5日&analyzer=index_ansj

配了5日=5天

**Comment by iusofts** [comment]
5.6.2的版本

**Comment by shi-yuan** [comment]
[synonyms.dic](https://github.com/NLPchina/ansj_seg/blob/master/library/synonyms.dic)的格式对吗？

**Comment by iusofts** [comment]
ansj:
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  dic: plugins/elasticsearch-analysis-ansj/mydic/

  stop: plugins/elasticsearch-analysis-ansj/stop/

  synonyms: plugins/elasticsearch-analysis-ansj/synonyms/

就配了这些

**Comment by iusofts** [comment]
格式是对的 dic自定义词典已经生效了  我配的都是目录 目录里面有好几个词典

**Comment by iusofts** [comment]
@shi-yuan 
感谢，已经解决了，dic文件里面有乱码  另外格式好像确实不对 不能用空格隔开 要用一个tab隔开
