### ISSUE TITLE
spring boot 项目打包为jar包, 如何在library.properties里引用 resources/library/default.dic ?

### ISSUE THREAD

**Issue by chilejiang1024** [NLPchina/ansj_seg#568]
在library.properties配置 
`dic = projcet_name/src/main/resources/library/default.dic`
本地调试可以用, 打包为jar包就不行了 ..
应该如何配置呢?
试过
```
dic = library/default.dic
dic = /library/default.dic
```

**Comment by loveoaim** [comment]
有可能是打的jar包没有将资源文件一起打包。
看下解包后meta-inf 有没有你要的文件。

没有就查下pom.xml文件 有没有添加这样的配置
`<resource>
	<directory>src/main/resources</directory>
	<targetPath>META-INF/resources</targetPath>
	<includes>
		<include>**/**</include>
	</includes>
</resource>`
