### ISSUE TITLE
分词结果中包含空格tab等

### ISSUE THREAD

**Issue by iusofts** [NLPchina/ansj_seg#573]
在停止词中添加空格和tab也无法过滤
{
            "token": " ",
            "start_offset": 1,
            "end_offset": 2,
            "type": "null",
            "position": 1
        }
请问采用什么方式可以将空格去除掉？

**Comment by shi-yuan** [comment]
stop空格的话，得用正则了：
![image](https://user-images.githubusercontent.com/8057153/30245486-d4a3c2e2-960d-11e7-8704-198002c105f3.png)

**Comment by zhaoweijing2003** [comment]
@shi-yuan 楼上正解，谢谢！
