### ISSUE TITLE
ansj自定义分词器没有生效

### ISSUE THREAD

**Issue by saintbjw** [NLPchina/ansj_seg#577]
我在ansj.cfg.yml文件中配置的自定义分词器，同时向用es自带的trim filter，结果测试分词时候提示 failed to find global analyzer [cust_query_ansj]

index:
  analysis:
    analyzer:
      cust_query_ansj:
       type: custom
       tokenizer: query_ansj
       filter:[trim]   ----------没有这行也不行

**Comment by shi-yuan** [comment]
ansj.cfg.yml配置文件只是ansj分词插件的配置，不涉及es的分词器。
以上分词器要能在es里使用，必须在es中[配置](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html)
