### ISSUE TITLE
高效载入大规模自定义词典

### ISSUE THREAD

**Issue by pachirayz** [NLPchina/ansj_seg#578]
请问是否有高效的载入大规模自定义词典的方法？
从之前的issue中看到有提到将DAT存为二进制文件，再载入时直接读取这个文件会比较快。这个方法是否可行？是否有提供方法或工具？
谢谢！

**Comment by ansjsun** [comment]
可行也是下一步打算做的。下一个版本肯定会提升加载速度

**Comment by pachirayz** [comment]
@ansjsun 谢谢健哥。
