### ISSUE TITLE
索引分词的问题

### ISSUE THREAD

**Issue by anoteboy** [NLPchina/ansj_seg#582]
我有在官网看到的索引分词，比如 入耳式耳机，索引分词会分为  入耳式 入耳 入 耳 式 耳机 耳 机
但是我在实际使用的5.1.1的版本中 在main中直接中直接调用分词  
Result parse = IndexAnalysis.parse("入耳式耳机");
		System.out.println(parse.size());
		for(int i=0;i<parse.size();i++){
			System.out.println(parse.get(i).getName());;
		}
显示的结果为
  入耳/a,式/k,耳机/n
只有这三种分词结果，是我的使用方式不对吗 还是说在5版本把这个分词的功能移除了，望回复谢谢

**Comment by ansjsun** [comment]
你需要挂一个外部词典。。
