### ISSUE TITLE
对数字进行分词的时候有个小问题没考虑到

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#583]
例如 3d 4g这种词，会被分成一个数字和一个英文。

**Comment by ansjsun** [comment]
这个在用户自定义词典里加吧。。

**Comment by chenjinyuan87** [comment]
我觉得数字后面跟上字母一般都是特殊词，所以我改了源代码，在处理数字的时候判断了一下，都标成en了。加词典还是比较麻烦的吧，不知道有多少这种形式的东西

**Comment by chenjinyuan87** [comment]
哦，对了，还有o2o，b2b什么的。。。也会被分开

**Comment by ansjsun** [comment]
的确。你说的有道理。数字和英文连续很可能是一个实体。

但是这么加进去可能发生
52nlp.com
version3.4

都会被合成一个词语

**Comment by chenjinyuan87** [comment]
第一个例子我觉得无所谓，52nlp.com也有可能是一个域名，只是我们的背景知识告诉我们，52大概是在说我爱的意思。。这种歧义问题不应该是分词层面解决的问题。

第二个例子确实没有什么好办法解决。所以提供一个英文-数字结合名词的recognition？对于这种结合词，在index索引的时候我们应该分成分成，version3.4 version 3.4。事实上，我目前的做法也是这样的。不过我结合的时候没考虑到.也有可能是数字的一部分。。所以只能处理 iPhone7之类的词@@

还有个事，你的numrecoginition第140行左右，i--应该改成i = temp.getOffe() - 1。 因为在前面识别*.*的时候有一次i--了，然后如果又去识别量词，就会变成i-2.如果诸如“3.2亿元"这种词出现在第一位，下一次循环就会变成-1，然后arrayindex***exception了。。。

**Comment by wainshine** [comment]
但MD5加密的结果，也是数字加字母啊，但他并不是一个实体。
md5(admin,16) = 7a57a5a743894a0e。

**Comment by chenjinyuan87** [comment]
md5加密结果更不应该被分成多个词啊。。
难道看到7a57a5a743894a0e 你觉得正确的分词结果是：
7 a 57 a 5 a 743894 a 0 e ?

并不一定是实体，只是一个特殊的字符串就可以了。
例如url email这种，实际上也并不是什么实体。。

**Comment by ansjsun** [comment]
@chenjinyuan87 数字那个我按照你说的改了啊。。

ps我邀请你假如group了。应该可以直接提交代码了。。。你直接改了吧。。

这次更新改动较大。所以很多地方测试不多。。。

**Comment by ansjsun** [comment]
我觉得数字英文合并可以考虑。做一个Recognition 让用户自己选择是否使用算了。。

**Comment by chenjinyuan87** [comment]
嗯。做个recognition比较合理

**Comment by HuarongLi** [comment]
@ansjsun 您好，我想问一下这个英文数字合并的Recognition做了么？

**Comment by chenjinyuan87** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
没做。我用的时候直接改了源码了。。
    在2018年4月19日 17:46，HuarongLi<notifications@github.com> 写道： 


@ansjsun 您好，我想问一下这个英文数字合并的Recognition做了么？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  





        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }

**Comment by HuarongLi** [comment]
@chenjinyuan87 好的，非常感谢，那我自己实现一个Recognition吧！
