### ISSUE TITLE
提个bug。人名识别出错了

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#586]
@ansjsun 
对这一句话进行分词，会出错。
她的母亲臧儿是秦末燕王臧荼的孙女，但是当时家族已经没落了，当她女儿到了及笄之年时，便将其嫁给一个叫金王孙的平民，不久还生了个女儿。

顺便，请问修改后能否通知我，急着用，谢谢
主要是我没法确定有多少类似的错误。你那段代码我看不懂。。

**Comment by chenjinyuan87** [comment]
for (int j = term.getOffe() - beginOff; j < end; j++) {
                if (terms[j] != null) {
                    len += Math.min(end - j, terms[j].getName().length());
                }
            }
是否应该这样改？我的理解是这里把之前拆掉但是后面没有找到新人名的词加回来。
然后我决定后面那段代码也应该改改：
                int beginIndex = term.getOffe() - beginOff;

                Term f1 = terms[beginIndex].from();

                for (int j = beginIndex; j < end; j++) {
                    terms[j] = null;
                }

                terms[term.getOffe() - beginOff] = term;

                TermUtil.termLink(f1, term);
                TermUtil.termLink(term, terms[beginIndex + term.getName().length()]);

改成：
                int beginIndex = term.getOffe() - beginOff;

                Term f1 = terms[beginIndex].from();

                for (int j = beginIndex+1; j < end; j++) {
                    terms[j] = null;
                }

                TermUtil.termLink(f1, term);
                TermUtil.termLink(term, terms[beginIndex + term.getName().length()]);

没什么区别吧？更简洁明了

**Comment by ansjsun** [comment]
你的意思是去掉 `terms[term.getOffe() - beginOff] = term;` 这一句吗

`terms[term.getOffe() - beginOff] `不赋值的话会是错误的吧？这个term是从set中搞出来的。

链表虽然连起来了。但是for 遍历的时候可能还是有错误

**Comment by chenjinyuan87** [comment]
嗯。是这个意思。
不需要赋值啊，进入这个循环的前提条件是 terms[term.getOffe() - beginOff] != null 啊。否则根本进不来

**Comment by ansjsun** [comment]
问题是。terms[term.getOffe() - beginOff]  != term ..

```
terms[term.getOffe() - beginOff] = 通
terms[term.getOffe() - beginOff+1] = 向

term = 通向
```

这个拆分是因为

费孝通向人大常委会提交xx报告。。。。

第一次分词结果是

费 孝 通向 人大 常委会

这时候人名和下文粘连了。so 拆分

拆分后

费 孝 通 向 人大 常委会

之后我发现通+向 = 通向。。那么移掉 这两个单字替换回 通向 这个词语。

当然这个例子有问题。。这里面真实通向是不要替换回去的

**Comment by chenjinyuan87** [comment]
测试没发现，因为通向就不会进到那个循环里。。
不过以防万一还是你的做法靠谱，谢谢

**Comment by ansjsun** [comment]
你测试这句。

我通向了幸福之路


````
//					terms[term.getOffe() - beginOff] = term;

					graph.printGraph();
````

结果是
````
我	0.0 ,
了	0.0 ,
幸福	0.0 ,
之路	0.0 ,
END	0.0 ,
我/r 通向/v 了/u 幸福/a 之路/r 
````

terms中间的通向丢了。terms数组 和 链表 不同步。这个可能在后续的recognition 的中出错。结果是以列表出来的不会有错。
