### ISSUE TITLE
又发现个BUG

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#587]
在url识别和email识别时，如果一个不全的url/email出现在文字的末尾，程序会报错。
例如：
这不是个网址http://
这也不是个email，abc@

先提一下，我要去改了。。。心好累

**Comment by chenjinyuan87** [comment]
这样子改：
    public List<List<Term>> findAll() {
        if (taskResults == null) {
            return Collections.emptyList();
        }

        List<List<Term>> result = new ArrayList<>(taskResults.size());

        RESULT:
        for (ExtractingTask task : taskResults) {
            List<Term> tempList = new ArrayList<>();
            for (List<Term> list : task.getList()) {
                if (list == null)
                    continue RESULT;
                for (Term term : list) {
                    tempList.add(term);
                }
            }
            result.add(tempList);

        }
        return result;
    }

**Comment by ansjsun** [comment]
直接提 request吧 。。省的我。。去改了额

**Comment by chenjinyuan87** [comment]
咋提。。新建个branch，push上去么0 0

**Comment by ansjsun** [comment]
我邀请你到group了。。你同意后直接可以提代码了哦

**Comment by chenjinyuan87** [comment]
之前就发现了。
可怜我用idea，之前用git导出好像不能提交，必须用github导出。又要重新导出一遍。
那个nlp-lang 1.7.7你好像还没有提交到公共库上，我下不到啊。

改到1.7.7好像是你昨天开始的工作，这个是要做什么？。。我可以继续跟么

我会说我是直接跑几亿的新闻数据么。。跑到挂了我就查错，哈哈

**Comment by ansjsun** [comment]
nlp-lang 1.7.7 在git里面没有发布到maven下面

你可以用
![image](https://user-images.githubusercontent.com/1221947/33358384-47e292f4-d503-11e7-8f39-d38efc8085ac.png)
这种方式集成进来，

感谢提交错误哈哈。。好测试
