### ISSUE TITLE
“高清真机”的分词结果好差啊

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#589]
会被分成 高 清真 机。
然后我发现除非我用dicanalysis，不然用户词典是不起作用的。即使我把高清和真机都加到词典里。
测试代码如下``
		DicLibrary.insert(DicLibrary.DEFAULT,"高清");
		DicLibrary.insert(DicLibrary.DEFAULT,"真机");
		System.out.println(DicAnalysis.parse("高清真机"));
		System.out.println(ToAnalysis.parse("高清真机"));``
看了一下userdicrecognition的代码，有点不明白为什么用户词典每次都是传入term的？因为原始分词是高/清真/机，然后识别的时候，高是1，再然后传入的就是清真了，因为不存在高清真，所以整个都没识别出来。。

**Comment by ansjsun** [comment]
是的 toanalysis 是。核心词典优先。。第一步就分词错误了。。后期不好改了。。除非把所有的词语加入到核心词表。。。这显然不可能。。。这种情况还是建议用dicanalysis把

**Comment by ansjsun** [comment]
userdicrecognition 是基于第一次细分结果之后的词语合并。。之前错误的合并不会拆开

**Comment by risan95** [comment]
太逗了

**Comment by ansjsun** [comment]
DicLibrary.insert(DicLibrary.DEFAULT,"高清","pos",100000);
		DicLibrary.insert(DicLibrary.DEFAULT,"真机","describe",100000);

		System.out.println(DicAnalysis.parse("高清真机"));


result

高清/pos,真机/describe

再次仔细看。 是#608的bug

**Comment by chenjinyuan87** [comment]
不是啊。这个和那个是两回事。
这个例子里面dicAnalysis其实没有出bug。我是不明白to为什么不能正确的分词。
第一次切分是 高/清真/机
然后to里面不是有用户词典么，在用户词典识别的时候，
逻辑是这样的：
高 -> 有后续词
清真 -> 只找到高清，没找到高清真，跳过
机 -> 结束

而我认为正常应该是：
高-> 有后续词
清-> 找到高清，插入图中
真-> 有后续词
机-> 插入真机。
重新计分
最后得到： 高清/真机

**Comment by ansjsun** [comment]
第一次切分是

0 高 高清
1 清 清真
2 真
3 机

找最短路径

高 清真 机 > 高清 真 机 所以第一步切分就错了


第二步。用户自定义词典。在第一步的切分结果上。做词语合并就对不了了。


我想了想608那个fix可能会有异常。最近事情挺多。只能断断续续维护了

**Comment by chenjinyuan87** [comment]
嗯。理解。
我只是不明白为什么不能把用户词典和系统词典等同。
这样第一次切分就是：
0 高 高清
1 清 清真
2 真 真机
3 机
然后最短路径应该就是 高清 真机 了。

**Comment by ansjsun** [comment]
不能简单的最短路径。还是有各个维度来增加计算权重的。这个平衡是最难的。机械的东西模仿自然本身就是一个不完备的命题。只能尽可能模拟吧
