### ISSUE TITLE
AmbiguityLibrary有一个bug

### ISSUE THREAD

**Issue by lyaohe** [NLPchina/ansj_seg#592]
org.ansj.library.AmbiguityLibrary文件103行
```
if (split.length % 2 != 0) {
	LOG.error("init ambiguity  error in line :" + temp + " format err !");
	continue;
}
```
文档中歧义纠正辞典格式是
`大和尚	大	a	和尚	n`

是不是文档没更新？不然

split.length % 2 是不是应该要改成 != 1 ？

需要提pull request 吗？

**Comment by ansjsun** [comment]
新的里面不需要 写完整的词语

直接写 

`大 a 和尚 n`即可
