### ISSUE TITLE
如何控制分词粒度？

### ISSUE THREAD

**Issue by ShortFinger** [NLPchina/ansj_seg#594]
找了一圈代码好像不能控制分词粒度，有考虑加这个吗？

**Comment by ansjsun** [comment]
ansj用不通的分词方式来控制颗粒度
baseanalysis是最细粒度的

**Comment by chenjinyuan87** [comment]
分完了之后自己再查词典细分一遍。。。
其实我一直不明白分词粒度这个需求到底是哪里冒出来的？ 
嫌太长的话直接把过长的词从词典里删掉就好了。。。

**Comment by ShortFinger** [comment]
那如果要粗的粒度呢？
比如“和平条约”->“和平”   "条约"

**Comment by chenjinyuan87** [comment]
把和平条约加到词典里啊

**Comment by lock19434** [comment]
分词的粒度怎么控制呀
