### ISSUE TITLE
NlpAnalysis中的新词发现确实有比较不对的情况出现，好像没有什么关掉的地方，但我不想用其它的分词的方式，怎么办？

### ISSUE THREAD

**Issue by jiangzIT** [NLPchina/ansj_seg#595]

**Comment by chenjinyuan87** [comment]
用ToAnalysis
或者自己自定义一个也可以

顺便，不对的地方是什么地方，请举例？
我之前测试过，nlp还是比to要好一点。。

**Comment by jiangzIT** [comment]
像一些机构名等不会被折开，分词细粒度会粗一点，

**Comment by jiangzIT** [comment]
我把NlpAnalysis中140行左右的代码注释掉，貌似可行。
	new NewWordRecognition(learn).recognition(graph);
	graph.walkPathByScore();

**Comment by chenjinyuan87** [comment]
机构名本来就不拆开啊。合到一起有什么问题？ 
如果你要索引的话，就用indexanalysis。
如果你既要新词发现又要索引，就自己参照index实现一个。。

**Comment by chenjinyuan87** [comment]
注释掉140之后，你干嘛还用nlp。。我说了让你用to你又不用。。。nlp和to的区别主要就是这一行

**Comment by jiangzIT** [comment]
我之前也尝试用了to，但实践证明，nlp还是会分词粗一点。所以我还是选择用nlp。

**Comment by chenjinyuan87** [comment]
你去掉新词发现（140行）之后，nlp基本上就退化成to了。自己比较一下源代码就知道了

**Comment by jiangzIT** [comment]
谢谢提醒。
