### ISSUE TITLE
词性标准问题

### ISSUE THREAD

**Issue by jianfeihit** [NLPchina/ansj_seg#597]
1、请问有词性说明吗？最近在看org.ansj.app.keyword.KeyWordComputer中POS_SCORE中存放了一些词性的默认权重值，但是没有找到准确的这些词性的含义。我看了北大的词性标注标准，没有找到en等词性的含义说明。
2、除了重写KeyWordComputer类以外，打分公式可以自定义吗？比如设计一个抽象类，用户可以根据该抽象类自定义打分公式

**Comment by ansjsun** [comment]
有几个我自定义的词性，如 en  nw 很少的几个

**Comment by jianfeihit** [comment]
感谢解答！有相关的说明文档吗？如果以北大标注为准的话，能说明一下自定义的就行

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/wiki/%E8%AF%8D%E6%80%A7%E6%A0%87%E6%B3%A8%E8%A7%84%E8%8C%83 这个由。自定义的词性就是 en ，和 nw 好像没有其它了

**Comment by chenjinyuan87** [comment]
路过。。其实你现在还自定义了例如 url book之类的东西啊，哈哈。
还有就是 i/l这两个好像有点混乱，俚语之类的东西，我也不知道是什么鬼
