### ISSUE TITLE
发现一个bug，DicAnalysis分词自定义词会跳过

### ISSUE THREAD

**Issue by 1148270327** [NLPchina/ansj_seg#598]
我用于单位的识别，如mol/L、mmHg等，老版本5.1.5修改后能识别，但是遇到了篡改词性的问题，故更新至5.1.6，然而新版本发现自定义词会被.getAllwords()跳过。
		while ((temp = word.getAllWords()) != null) {
						if (graph.terms[word.offe] == null) {
							continue;
						}
内存中确定自定义词已加入新版本的forest，但getAllWords只会get一个，对新格式的forest拿不到数据。
新版的forest会把共同的smartbanrch合并。

**Comment by ansjsun** [comment]
我没有太理解。。。能给一个具体的例子吗？这里是continue不是break理论上不会跳过吧

**Comment by 1148270327** [comment]
不好意思，可能描述的不太到位。是这样的：自定义词库里有
mmol/L	danwei	10000
/HP	danwei	10000
℃	danwei	10000
mmHg	danwei	10000

然后用Dicanalysis分词“速度0.2mmol/L, Hg高88mmHg，体温为31.5℃”
结果为“速度/n 0.2/m mmol/en //w L/en ，/w Hg/en 高/a 88/m mmHg/en ，/w 体温/n 为/p 31.5/m ℃/danwei”

内存分析，可以看到自定义词已加入forest，但是word.getAllWords())只能执行一次，获取到℃，，后面temp都为null了。应该是lang包内修改的问题。

**Comment by 1148270327** [comment]
自定义词装载出我改了原来的代码，变成保留大小写，所以mmHg可以识别

**Comment by ansjsun** [comment]
默认分词大小写不敏感。所以你需要把词转为小写

````
MyStaticValue.isQuantifierRecognition = false ;

		DicLibrary.insert(DicLibrary.DEFAULT,"mmol/L".toLowerCase(),"danwei",10000);
		DicLibrary.insert(DicLibrary.DEFAULT,"/HP".toLowerCase(),"danwei",10000);
		DicLibrary.insert(DicLibrary.DEFAULT,"mmHg".toLowerCase(),"danwei",10000);
		DicLibrary.insert(DicLibrary.DEFAULT,"℃".toLowerCase(),"danwei",10000);


		Result recognition = ToAnalysis.parse("速度0.2mmol/L, Hg高88mmHg，体温为31.5℃").recognition(new UserDicNatureRecognition());
		System.out.println(recognition);
		recognition = DicAnalysis.parse("速度0.2mmol/L, Hg高88mmHg，体温为31.5℃");
		System.out.println(recognition);
````

**Comment by ansjsun** [comment]
如果大小写对你来说很重那个要会造成失误我可以在程序里面加个开关。

````
public Graph(String str) {
		this.str = str ;
		this.chars = WordAlert.alertStr(str);//这个是对原始文本转换的。把全角 大写都转换为小写了
````

**Comment by 1148270327** [comment]
谢谢，可以了。是我改代码改的不到位导致的。原因是Natures.class里的static final EN在并行dicanalysis时居然改变了。。。找到时对Natures里的Nature变量赋值了，然后无缘无故，Natures里的static final的变量自动错乱了。。。。。
