### ISSUE TITLE
孙大神你好,我直接使用ToAnalysis发现有些词本该识别为疑问代词结果识别为普通代词,是哪里可以设置吗?

### ISSUE THREAD

**Issue by lxxj422092598** [NLPchina/ansj_seg#600]
比如
这是哪?
这/r是/v哪/r?/w

**Comment by lxxj422092598** [comment]
好不上面那句话不太正常
这是哪?
这/r是/v哪/r?/w

**Comment by lxxj422092598** [comment]
五种analysis我都用了，这句话结果一样。百度中搜索ansj分词教程中，有 
vshi 动词“是” 
ry 疑问代词
ryt 时间疑问代词
等非常详细的分类，是我哪里操作不对吗……识别不出这么细

**Comment by ansjsun** [comment]
应该没有这么丰富的词性。可能词典之前有给删了。很遗憾的说ansj目前没有专门实现这块

**Comment by lxxj422092598** [comment]
好的，谢谢孙健大神。
