### ISSUE TITLE
为什么跑IndexAnalysis的demo得到的结果跟wiki中的不一样？

### ISSUE THREAD

**Issue by pdu** [NLPchina/ansj_seg#602]
Maven的配置是：

    <dependency>
            <groupId>org.ansj</groupId>
            <artifactId>ansj_seg</artifactId>
            <version>5.1.5</version>
    </dependency>
    <dependency>
            <groupId>org.nlpcn</groupId>
            <artifactId>nlp-lang</artifactId>
            <version>1.7.7</version>
    </dependency>

代码是：

    String str = "洁面仪配合洁面深层清洁毛孔 清洁鼻孔面膜碎觉使劲挤才能出一点点皱纹 脸颊毛孔修复的看不见啦 草莓鼻历史遗留问题没辙 脸和脖子差不多颜色的皮肤才是健康的 长期使用安全健康的比同龄人显小五到十岁 28岁的妹子看看你们的鱼尾纹" ;
    System.out.println(IndexAnalysis.parse(str));

输出结果是：

    /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java -Didea.launcher.port=7536 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/tools.jar:/Users/peng/work/visenze/weardex-service/Service/nlpcn/target/classes:/Users/peng/.m2/repository/org/ansj/ansj_seg/5.1.5/ansj_seg-5.1.5.jar:/Users/peng/.m2/repository/org/nlpcn/nlp-lang/1.7.7/nlp-lang-1.7.7.jar:/Users/peng/.m2/repository/ch/qos/logback/logback-core/1.1.11/logback-core-1.1.11.jar:/Users/peng/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar:/Users/peng/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/peng/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:/Users/peng/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.25/log4j-over-slf4j-1.7.25.jar:/Users/peng/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar:/Users/peng/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/Users/peng/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar:/Users/peng/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/peng/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/peng/.m2/repository/org/apache/commons/commons-pool2/2.3/commons-pool2-2.3.jar:/Users/peng/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar:/Users/peng/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/Users/peng/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/Users/peng/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/Users/peng/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/peng/.m2/repository/joda-time/joda-time/2.8.2/joda-time-2.8.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain com.weardex.visearch.nlpcn.Bootstrap
    15:43:38.882 [main] WARN org.ansj.util.MyStaticValue - not find library.properties in classpath use it by default !
    15:43:38.889 [main] INFO org.ansj.dic.impl.File2Stream - path to stream library/ambiguity.dic
    15:43:38.889 [main] ERROR org.ansj.library.AmbiguityLibrary - Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/ambiguity.dic file:/Users/peng/work/visenze/weardex-service/library/ambiguity.dic not found or can not to read, path: library/ambiguity.dic
    15:43:38.890 [main] DEBUG org.ansj.library.DicLibrary - begin init dic !
    15:43:38.890 [main] INFO org.ansj.dic.impl.File2Stream - path to stream library/default.dic
    15:43:38.890 [main] ERROR org.ansj.library.DicLibrary - Init dic library error :org.ansj.exception.LibraryException:  path :library/default.dic file:/Users/peng/work/visenze/weardex-service/library/default.dic not found or can not to read, path: library/default.dic
    15:43:40.221 [main] INFO org.ansj.library.DATDictionary - init core library ok use time : 1167
    15:43:40.627 [main] INFO org.ansj.library.NgramLibrary - init ngram ok use time :403
    洁/ag,面/q,仪/k,配合/v,洁/ag,面/q,深层/b,清洁/a,毛孔/n, ,清洁/a,鼻孔/n,面膜/n,碎/a,觉/v,使劲/v,挤/v,才能/v,出/v,一/m,点点/v,皱纹/n, ,脸颊/n,毛孔/n,修复/v,的/u,看/v,不见/v,啦/y, ,草莓/n,鼻/ng,历史/n,遗留/vn,问题/n,没辙/v, ,脸/n,和/c,脖子/n,差不多/l,颜色/n,的/u,皮肤/n,才/d,是/v,健康/a,的/u, ,长期/d,使用/v,安全/an,健康/a,的/u,比/p,同龄人/n,显/v,小/a,五/m,到/v,十岁/mq, ,28岁/mq,的/u,妹子/n,看看/v,你们/r,的/u,鱼尾纹/n
    
    Process finished with exit code 0

[wiki](https://github.com/NLPchina/ansj_seg/wiki/%E5%88%86%E8%AF%8D%E6%96%B9%E5%BC%8F)里面的结果是：

    洁/ag,面/n,仪/k,配合/v,配/v,合/v,洁/ag,面/n,深层/b,深/a,层/qv,清洁/a,清/tg,洁/ag,毛孔/n,毛/n,孔/n, ,清洁/a,清/tg,洁/ag,鼻孔/n,鼻/ng,孔/n,面膜/n,面/nf,膜/n,碎/a,觉/v,使劲/v,使/v,劲/n,挤/v,才能/n,才/d,能/v,出/v,一点点/m,一点/mq,一/m,点点/v,点/qt,点/qt,皱纹/n,皱/v,纹/ng, ,脸颊/n,脸/n,颊/ng,毛孔/n,毛/n,孔/n,修复/v,修/v,复/dg,的/uj,看不见/v,看/v,不见/v,不/d,见/v,啦/y, ,草莓/n,草/n,莓/n,鼻/ng,历史/n,历/vg,史/ng,遗留问题/nz,遗留/v,遗/vg,留/v,问题/n,问/v,题/n,没辙/v,没/d,辙/n, ,脸/n,和/c,脖子/n,脖/ng,子/ng,差不多/l,差/a,不多/m,不/d,多/a,颜色/n,颜/ng,色/ng,的/uj,皮肤/n,皮/n,肤/ng,才/d,是/v,健康/a,健/ag,康/ag,的/uj, ,长期/d,长/a,期/qv,使用/v,使/v,用/p,安全/an,安/ag,全/a,健康/a,健/ag,康/ag,的/uj,比/p,同龄人/n,同龄/vi,同/p,龄/ng,人/n,显/v,小/a,五/m,到/v,十岁/m,十/m,岁/qt, ,28岁/m,岁/qt,的/uj,妹子/n,妹/n,子/ng,看看/v,看/v,看/v,你们/r,你/rr,们/k,的/uj,鱼尾纹/n,鱼尾/n,鱼/n,尾/ng,纹/ng

**Comment by ansjsun** [comment]
没有加自定义词典吧。。。https://github.com/NLPchina/ansj_seg/tree/master/library 这个目录下下来放你项目根目录里面

**Comment by pdu** [comment]
可以了，谢谢大神！
