### ISSUE TITLE
自定义词，为什么无法分出

### ISSUE THREAD

**Issue by jcnlp** [NLPchina/ansj_seg#603]
例如：插入“芭提雅”
 DicLibrary.insert("dic", "芭提雅", "user", 100000);
System.out.println(DicAnalysis.parse("芭提雅"));
分词结果：芭,提/v,雅/ag，分词无法按照词典分词，大部分词都是可以正常按照词典分词的

while ((str = gwi.allWords()) != null) { // 是不是这里有问题
gp.addTerm(new Term(str, gwi.offe, gwi.getItem()));
}

备注一下，依赖的ansj版本具体是哪一个忘了（pom版本做了修改），org.nlpcn依赖的版本是1.7.2，使用最新版的ansj源码是ok的

**Comment by ansjsun** [comment]
下载最新版的ansj吧。。这个。。我也不确定了。但是nlp-lang 1.7.2 应该是比较旧的版本了。
