### ISSUE TITLE
PersonRecognition是不是有性能问题

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#604]
？这两天大批量拷贝数据的时候发现好多线程都卡这里了。
看了下代码，复杂度是N^2，而传入的graph可能是一整段很长的话。这种情况下会很慢吧？

**Comment by chenjinyuan87** [comment]
哦，不对。。好像不是这么回事。。但是确实所有线程都在这个循环里面。。

**Comment by ansjsun** [comment]
是的这个做了一次重构。重构实现了完整的版本。。之前是简化版本。速度能保证。但是准确率稍差。具体性能我还没有做过。开启和关闭人名识别的测试。但是我估计人名识别快不了了

**Comment by chenjinyuan87** [comment]
我输入的时候是把整篇文章一起放进去分词的。
感觉这样子会导致复杂度高很多吧？
但是我这边有些处理不好先拆行/句子，再分词。
所以我准备在person里面拆一下，这样应该复杂度会低很多吧

在 2017年12月14日 上午10:53，ansj <notifications@github.com>写道：

**Comment by ansjsun** [comment]
应该不会降低。viterbi是线性复杂度的。 你可以尝试。分词100句 和分词把100句拼起来。测试速度区别。。

**Comment by chenjinyuan87** [comment]
不是viterbi，应该是List<PersonNode> result这个集合太大了，你后面有个j=i;
j<n，这样子复杂度就是result长度的平方了


2017-12-14 11:21 GMT+08:00 ansj <notifications@github.com>:

**Comment by chenjinyuan87** [comment]
仔细看了一下，感觉for (int j = i + 1; j < result.size(); j++) { p2 =
result.get(j);...
这一段，j应该不需要到result.size吧？ 加个其他的停止条件？

在 2017年12月14日 下午1:34，陈金元 <chenjinyuan87@gmail.com>写道：

**Comment by chenjinyuan87** [comment]
也不是这个原因。。好像EDZ总能在几个词之后找到。
但是我测试的时候，这个循环确实消耗了20多秒。而其他过程加起来也就几秒。
原因还在找。
如果分开一行一行计算的话，速度是正常的

在 2017年12月14日 下午1:39，陈金元 <chenjinyuan87@gmail.com>写道：

**Comment by chenjinyuan87** [comment]
找到原因了，因为你的result是linkedlist。用下标遍历显然会非常慢。。

在 2017年12月14日 下午1:47，陈金元 <chenjinyuan87@gmail.com>写道：

**Comment by ansjsun** [comment]
cool 要么你改了帮我提交下吧。我偷个懒

**Comment by chenjinyuan87** [comment]
提了pull request了

2017-12-14 14:13 GMT+08:00 ansj <notifications@github.com>:

> cool 要么你改了帮我提交下吧。我偷个懒
>
> > On 14 Dec 2017, at 1:58 PM, chenjinyuan87 <notifications@github.com

**Comment by ansjsun** [comment]
cool  merged !
