### ISSUE TITLE
自定义分词优先有个小缺陷很尴尬）

### ISSUE THREAD

**Issue by 1148270327** [NLPchina/ansj_seg#608]
我用的分词，核心是5.1.6版本，DicAnalysis分词，自定义词其实某些情况下并不优先：
eg. 当内置的core中有的词性，会优先组合，例如，自定义词有“心 pos 1000”、“律齐 describe 1000”，此时分词结果为: 心律/n 齐/d。。。。。。
理想结果我认为是： 心/pos 律齐/describe

个人分析过程：句子>>拆成单个字组成graph >> 根据内置的核心core（gwi）跑了一遍graph，把内置词优先组合形成最短路径 >>userDefineRecognition跑自定义词，形成最短graph(这一步，因为'心律已被之前给合并了，所以没有自定义词能缩短路径')。

个人认为，既然是自定义词优先分词，应该是先跑用户自定义词组成graph（最长词优先），然后才为核心分词（长词优先）。

以上是个人意见，希望大大给予反驳0.0

**Comment by chenjinyuan87** [comment]
。。DicAnalysis的说明是： 默认用户自定义词性优先，而不是自定义词的权重高于系统词典。
说回你这个问题，假设你自定义词典中没有 心律 这个词（更准确的说，如果你的自定义词典不够完善），那么你所设想的第一步操作会出现很多不可逆的错误。这些错误无法通过系统词典纠正。最后分词效果显然很差。因为你只给了一个很简单的例子，所以我也只能很模糊的给你分析一下。

而且就说你那个例子吧，反正我是不知道为什么心要单独一个字。

如果你非要做这个事情，可以自己改一下Analysis这个类。

btw：我更奇怪的是，为什么自定义词典和系统词典不整合到一起，在Analysis里面处理，然后一起评分。我觉得这样子能解决之前说的那个“高清真机”的问题吧？合并到一起的缺点是什么？担心自定义词典的质量不好么 @ansjsun

**Comment by ansjsun** [comment]
@1148270327 @chenjinyuan87 

删掉 

public class DicAnalysis

75行
````
						if (graph.terms[word.offe] == null) {
							continue;
						}
````

心/pos,律齐/describe
我的/nt,心/pos,律齐/describe,身体/n,神/n,健康/a
就好了

这个应该是改出来的bug 。。用户自定义词典分词。差不多是按照 @chenjinyuan87 说的方式来做的

**Comment by chenjinyuan87** [comment]
刚发现DicAnalysis不是用的UserDefineRecognition，那为什么UserDefineRecognition的处理方式是只合并系统词典的词，而不会有新的切分呢？表示不理解这么做的原因啊。我好想下手改掉它~

**Comment by ansjsun** [comment]
toanalysis 或者其他方式的分词是不破坏第一步细分结果的基础上进行二次分词。UserDefineRecognition  主要处理这个问题。dicanalysis是个特例。所以拿出来单写了
