### ISSUE TITLE
自定义词的词性覆盖原始词库词性

### ISSUE THREAD

**Issue by cbangyu-zju** [NLPchina/ansj_seg#611]
Library.insertWord(newDictTree, new Value("即刻", "nt", "1000"));

有一个APP名称是“即刻”，所以想用 即刻/nt，而系统词性是d，我们分出来的词最终都是d。
请问有什么办法让自定义词的词性覆盖原始词库词性呢？

**Comment by ansjsun** [comment]
两个办法。
1.用dic做分词
或者
2.使用 .recognition(new NatureRecognition()))
