### ISSUE TITLE
AmbiguityLibrary歧异词典不生效

### ISSUE THREAD

**Issue by zhangxuelai** [NLPchina/ansj_seg#612]
词典已经按照”词1  词1词性  词2  词2词性“定义，且已经正常加载。
# 歧义词典内容
`
查	v	本省	n
`
# 测试语句
查本省今天天气情况
# 分词结果
查本省 今天 天气 情况 （其中查本省被认为是人名）

# 问题分析
1. Analysis.analysisStr 确实按照歧义词典先进行了划分，”查本省“也被分开了
2. 后面在执行CRF的分词时，”查本省“ 又被分到了一起。

这个是不是应该先分词，再过歧义词典，以保证歧义词典的优先级？

**Comment by zhangxuelai** [comment]
代码中用的是NLPAnalysis

**Comment by shi-yuan** [comment]
用[5.1.5](https://mvnrepository.com/artifact/org.ansj/ansj_seg/5.1.5)测试结果：
`查/v,本省/r,今天/t,天气/n,情况/n`

您用的是哪个版本？歧义词典内容之间是用Tab分隔的吗？

**Comment by zhangxuelai** [comment]
呃，之前是5.1.1，昨天换到了5.1.5，难道是用法不对
词库是用tab分隔的，调试过
Analysis.analysisStr的代码，在这里从歧义词库中已经对查本省进行了分割。

我直接调用了NLP的parse，后面是自定义的词库，结果”查本省“被当作了nw新词。（抱歉上面写成了人名）
`
NlpAnalysis.parse(text, DicLibrary.get("sys"))
`

**Comment by ansjsun** [comment]
可能是有个bug 。。。。建议你用 ToAnalysis来分。或者dicAnalysis来分
