### ISSUE TITLE
添加自定义词典无效(ansj:5.1.1, nlp-lang:1.7.2)？

### ISSUE THREAD

**Issue by andyxzq** [NLPchina/ansj_seg#614]
我在maven项目根目录下，src同一级别，增加了library/default.dic，然后同级目录下添加了library.properties文件，里面内容是: dic=library/default.dic。
项目中的代码是
```
val forest = DicLibrary.get()
    if(forest == null){
      DicLibrary.put(DicLibrary.DEFAULT, DicLibrary.DEFAULT, new Forest())
    }
DicLibrary.insert(DicLibrary.DEFAULT, "弹幕墙", "n", 1000)
```
但是default.dic中的词“弹幕墙”还是被分开了。

**Comment by ansjsun** [comment]
查看启动日志。是否提示词典加载成功？

这种通过程序的方式理论上是不会有问题的。。

你用DicAnalysis来切分试试

DicLibrary.insertOrCreate(DicLibrary.DEFAULT,"弹幕墙","n",1000);

		System.out.println(DicAnalysis.parse("进来教你弹幕墙制作O(∩_∩)O~_日常_生活_bilibili_哔哩哔哩"));
		System.out.println(NlpAnalysis.parse("进来教你弹幕墙制作O(∩_∩)O~_日常_生活_bilibili_哔哩哔哩"));
		System.out.println(ToAnalysis.parse("进来教你弹幕墙制作O(∩_∩)O~_日常_生活_bilibili_哔哩哔哩"));


····
进来/vf,教/v,你/rr,弹幕墙/n,制作/v,O/en,(/w,∩/w,_,∩/w,)/w,O/en,~/w,_,日常/b,_,生活/vn,_,bilibili/en,_,哔/n,哩/y,哔/n,哩/y
进来/v,教/v,你/r,弹幕墙/n,制作/v,O/en,(/w,∩/w,_,∩/w,)/w,O/en,~/w,_,日常/b,_,生活/vn,_,bilibili/en,_,哔,哩哔/nw,哩/y
进来/v,教/v,你/r,弹幕墙/n,制作/v,O/en,(/w,∩/w,_,∩/w,)/w,O/en,~/w,_,日常/b,_,生活/vn,_,bilibili/en,_,哔,哩/y,哔,哩/y
····

**Comment by andyxzq** [comment]
@ansjsun ,我这边跑的是spark任务，词典放在根目录下的library/default.dic，启动日志提示找不到路径“ERROR library.DicLibrary: Init ambiguity library error :org.ansj.exception.LibraryException:  path :library/default.dic file:/data/hdfs/yarn/local/usercache/dev/appcache/application_1513841950272_164870/container_1513841950272_164870_01_000001/library/default.dic not found or can not to read, path: library/default.dic”，这要怎么解决？

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/issues/373

或者将词典打入到jar包

**Comment by SewellLeung** [comment]
DicLibrary.insert( "/library/user.dic","西红柿炖牛腩","userDefine", 1000);
报错dic library/user.dic not found in config 
5.1.6最新版本的，有没有大佬帮我看一下最新版应该怎么添加词到自定义词典啊

**Comment by ansjsun** [comment]
第一个参数不是路径 是key diclibrary.dic




在2019年05月06日 20:25，SewellLeung 写道：

DicLibrary.insert( "/library/user.dic","西红柿炖牛腩","userDefine", 1000);
报错dic library/user.dic not found in config
5.1.6最新版本的，有没有大佬帮我看一下最新版应该怎么添加词到自定义词典啊

**Comment by SewellLeung** [comment]
那请问怎么设置可以将自定义词典放在一个我自定的路径下呢

**Comment by ansjsun** [comment]
通过library.properties 设置路径




在2019年05月06日 20:47，SewellLeung 写道：

那请问怎么设置可以将自定义词典放在一个我自定的路径下呢

**Comment by SewellLeung** [comment]
谢了

**Comment by ansjsun** [comment]
嗯看看wiki吧




在2019年05月06日 20:57，SewellLeung 写道：

谢了

**Comment by SewellLeung** [comment]
你好，新版的应该调用什么方法可以将添加的新词保存到本地词典文件中，我看到网上的一些示例代码用的DicLibrary.insert（）自己测试好像只能操作内存

**Comment by ansjsun** [comment]
不能添加 没有这个功能





在2019年05月06日 22:51，SewellLeung 写道：

你好，新版的应该调用什么方法可以将添加的新词保存到本地词典文件中，我看到网上的一些示例代码用的DicLibrary.insert（）自己测试好像只能操作内存
