### ISSUE TITLE
MyStaticValue 更新到5.1.5之后没有了

### ISSUE THREAD

**Issue by adoniswu** [NLPchina/ansj_seg#616]
您好！我项目之前用到的是5.0.4，这个版本中是有MyStaticValue这个类的，
我是用：MyStaticValue.ambiguityLibrary = path 和 MyStaticValue.DIC.put(MyStaticValue.DIC_DEFAULT, path)
想请问下升级为5.1.5 之后 怎么赋值？

**Comment by shi-yuan** [comment]
```java
AmbiguityLibrary.put(...)
DicLibrary.put(...)
```
