### ISSUE TITLE
分词结果不正确的问题

### ISSUE THREAD

**Issue by wuyoubei1** [NLPchina/ansj_seg#620]
你好作者：这句话“在宴会上上了头条” 在分词后的结果为：在/p,宴会/n,上上/t,了/u,头条/n  ， 按照语义应该是 “在/p,宴会/n,上/f,上/v,了/u,头条/n ”才对，“上上”不应该单独分出一个词，这种问题怎么能解决？  
在歧义字典里配置“宴会上”的词后，分词依然是“上上/t”。

**Comment by ansjsun** [comment]
你好可能是新加的词典造成的。。我看了下历史版本问题不大

http://www.nlpcn.org/ <http://www.nlpcn.org/>

````
ToAnalysis:在/p,宴会/n,上上/t,了/u,头条/n
NlpAnalysis:在/p,宴会/n,上上/t,了/u,头条/n
DicAnalysis:在/p,宴/ng,会上/n,上/f,了/ule,头条/n
BaseAnalysis:在/p,宴会/n,上/f,上/f,了/u,头/n,条/q

````

下一个版本词典中我会将。上上这个词语移除掉。目前建议考虑DicAnalysis来控制。

**Comment by wuyoubei1** [comment]
好  多谢
