### ISSUE TITLE
关于core.dic词典

### ISSUE THREAD

**Issue by wuyoubei1** [NLPchina/ansj_seg#623]
请问core.dic词典中的3、4、5、6列的值是怎么计算出来的？
这个词典中的有些词，在分词时会产生误差，比如：发展中国家庭养猪事业，分词后是“发展中国/nw,家庭/n,养猪/v,事业/n，” 实际语义应该是 “发展  中国  家庭/n,养猪/v,事业/n”，发现在core.dic中有 “发展中国”这个词，
在歧义词典中配置“中国家庭”后，也没有效果，我用的是nlp分词。

**Comment by ansjsun** [comment]
可能歧义词典再nlp方式中不生效。
目前来看toanalysis对这句话的分词是正确的。

词典中计算是 dat的方式。wiki里面有介绍
