### ISSUE TITLE
写一个完整的crf训练方式

### ISSUE THREAD

**Issue by ansjsun** [NLPchina/ansj_seg#625]
写一个完整的crf训练方式

**Comment by Silencezjl** [comment]
https://github.com/NLPchina/ansj_seg/wiki/%E5%AE%9A%E5%88%B6%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84CRF%E6%A8%A1%E5%9E%8B

**Comment by ansjsun** [comment]
。。。。。。 這是我寫的。。。
