### ISSUE TITLE
有没有ansj的python实现？

### ISSUE THREAD

**Issue by ShaoStrong** [NLPchina/ansj_seg#639]
各位大佬好， 有没有ansj的python实现？

**Comment by shibing624** [comment]
还没有，有相似的。snownlp,jieba,nltk等库。

**Comment by ShaoStrong** [comment]
加自定义的词性标识还是ansj方便，  ansj是2-gram，  按理比jieba的1-gram更好。 有时间我想实现一个python版本的。
