### ISSUE TITLE
如何预加载library

### ISSUE THREAD

**Issue by wangsm123** [NLPchina/ansj_seg#644]
在demo中都是每次分词都加载一次library，而加载library时间较长，能否预先加载好library，在调用parse的时候就不需要再加载了

**Comment by hanzeyao** [comment]
请问您这个问题解决了吗  我也想问下这个问题

**Comment by shi-yuan** [comment]
程序运行过程中，只会加载一次的，
如果要自行加载的话，可以调用不同library的get方法
