### ISSUE TITLE
crf++训练语料的api：crf.MakeTrainFile是不是不太对啊

### ISSUE THREAD

**Issue by 1148270327** [NLPchina/ansj_seg#655]
您好，大牛。，我用网盘里的语料，执行:java org.ansj.app.crf.MakeTrainFile [inputPath] [outputPath]，生成了形如
“迈 B
向 E
充 B
满 E
希 B
望 E
的 S
新 S
世 B
纪 E”
的train.txt，但是crf++只是reading train file，结束后就停止了。。。然后我发现，和crf中的example中的示例不太一样，少了一列，这是正常吗？？模板采用的是如下
“
#Unigram
U00:%x[-2,0]
U01:%x[-1,0]
U02:%x[0,0]
U03:%x[1,0]
U04:%x[2,0]
U5:%x[-2,0]/%x[-1,0]
U6:%x[-1,0]/%x[0,0]
U7:%x[0,0]/%x[1,0]
U8:%x[1,0]/%x[2,0]

# Bigram
B
”

**Comment by 1148270327** [comment]
已经发现问题所在了，windows下的版本容易停止处理返回到命令行。在linux下可以不间断，不过一直卡在shrinking size很慢很慢

**Comment by ansjsun** [comment]
應該。。是吧 我也不太清楚。。
