### ISSUE TITLE
能否给出 Recognition 的规则的文档说明

### ISSUE THREAD

**Issue by gladuo** [NLPchina/ansj_seg#660]
Ansj 至今仍是我评测过最优秀的分词 repo
我想贡献一些 rule-based 的 recognition，类似于现在的 [EmailRecognition.java](https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/recognition/impl/EmailRecognition.java) 和 [URLRecognition.java](https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/recognition/impl/URLRecognition.java)，例如现在的 [URLRecognition](https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/recognition/impl/URLRecognition.java#L26) 似乎只能识别网站而不能更鲁棒的识别长而复杂的网址。我注意到代码里的规则似乎不完全是正则的方式，而有一些自定义的 DSL，烦请给一些更详细的说明和 motivation，方便大家扩展。

**Comment by shi-yuan** [comment]
这是基于ansj_seg里的[抽取引擎](https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/app/extracting/Extracting.java)实现的， 
@ansjsun 是不是可以加个wiki说明下？

**Comment by shi-yuan** [comment]
[wiki/规则引擎](https://github.com/NLPchina/ansj_seg/wiki/%E8%A7%84%E5%88%99%E5%BC%95%E6%93%8E)

**Comment by gladuo** [comment]
THX!

**Comment by gladuo** [comment]
『名称:0;限定:2;目的:(个数) 是之后的抽取内容，可以作为只是抽取。0代表第一个括号命中，即糖尿病， 2代表第二个括号命中 几并发症』

这一部分没有看懂『之后的抽取内容』『只是抽取』『0代表第一个括号命中，即糖尿病， 2代表第二个括号命中 几并发症』这几个部分都没太看懂。

**Comment by chenjinyuan87** [comment]
。。。url这个规则是不是被我改过，我好像直接提交到最新版了@@

**Comment by chenjinyuan87** [comment]
最后说一声。。童鞋，你需要加强一下代码阅读能力+调试能力
我当时其实压根没看过规则，直接就给改掉了，嘿嘿

**Comment by gladuo** [comment]
@chenjinyuan87 不太会写 Java，其实跟我理解的差不多，但是直接自己改了一直不生效。。。怕揣测错了，我再看看，THX

**Comment by ansjsun** [comment]
不要用那個了。你那個還是實驗性的產品。所以連文檔都沒有。目前我可能沒有經歷維護了
