### ISSUE TITLE
nlp分词“崔永元炮轰范冰冰”的结果简直不能忍

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#661]
崔永元炮/轰范/冰冰
如果把用户词典放到新词发现之后，那么崔永元这个词都不存在
如果把用户词典放在新词发现之前，最后评分的时候还是把正确结果干掉了。即使我把3个词都加到用户词典里。。
我个人觉得optimalroot那个函数是不是哪里逻辑不太对？
但是我对这个函数的原理没有深究，所以自己看不出来

**Comment by ansjsun** [comment]
不知道你使用的版本我的测试结果如下

System.out.println(ToAnalysis.parse("崔永元炮轰范冰冰").getTerms().toString());

[崔永元/nr, 炮轰/v, 范冰冰/nr]

**Comment by chenjinyuan87** [comment]
我说的是nlpanalysis啊。
后来我做了大规模的测试，感觉新词发现的优先级太高了还是不行。
所以我整个自己实现了一遍，新词发现只对词典中已存在的词进行合并操作，而不会拆分。
也就是说，如果词典有 ab cd ef，新词发现可以出来abcd，但是不能是abc d ef这种

**Comment by ansjsun** [comment]
年度清理
