### ISSUE TITLE
ToAnalysis的Bug 2

### ISSUE THREAD

**Issue by chenjinyuan87** [NLPchina/ansj_seg#664]
千万别在追多
分词结果为：
千万/m,万别/nrf,在/p,追/v,多/a

感觉明明和上一个bug类似啊。。心好累啊

**Comment by chenjinyuan87** [comment]
嗯，确实类似。
只是一个是量词出问题，一个是数词出问题而已

**Comment by ansjsun** [comment]
之前看到這個bug 天佑改好了。。。。阿彌陀佛
