### ISSUE TITLE
分词正确但是无词性，单独输入有词性，或者在末尾加上标点符号后又有词性

### ISSUE THREAD

**Issue by fine145** [NLPchina/ansj_seg#665]
例如：不远，分词为“不”，词性为“u”，“远”，词性为“null”
单独输入“远”，分词为“远”，词性“a”
或者输入“不远。”，后面多了个句号，“远”也会有词性
不知道为啥，希望作者指教
因为实际需求修改过core.dic里的status，将某些“3”改为了“1”，这个应该只影响分词，不知为何会没词性了

**Comment by fine145** [comment]
public List<Term> cutWors(String string) throws Exception {
		System.out.println("进来处理的句子-->" + string);
		List<Term> list = new ArrayList<Term>();
		Forest forest = new Forest();
		List<String> dataList = FileUtils.readFile2List(path, "UTF-8");
		List<String> fantiList = FileUtils.readFile2List(fantipath, "UTF-8");
		// 加载自定义词典
		for (String str : dataList) {
			String[] strings = str.split("\\t");
			forest.addBranch(strings[0], new String[] { strings[1], "10000" });
		}
		// 加载繁体词典
		for (String str : fantiList) {
			String[] strings = str.split("\\t");
			forest.addBranch(strings[0], new String[] { strings[1].trim(), "100000000" });
		}
		// string = JianFan.f2j(string);
		// 增加新词,中间按照'\t'隔开
		Result terms = DicAnalysis.parse(string, forest);
		for (Term t : terms.getTerms()) {
			// System.out.println(t.getName() + "-->" + t.getNatureStr() + "-->"
			// + t.getOffe());
			list.add(t);
		}
		return list;
	}

**Comment by chenjinyuan87** [comment]
3改为1？ 我记不清楚status的意义了，但是这个status不应该被随意更改。。。
数字是表示当前位置的状态的，这是和词典密切相关的，词典确定的情况下status也就确定了。
你如果非要自定义，不仅要改dic，还要对应改baseanalyze
