### ISSUE TITLE
请问，分词可以使用自定义词典及按照自定义中文词库分值排序吗？

### ISSUE THREAD

**Issue by fenght** [NLPchina/ansj_seg#668]

**Comment by ansjsun** [comment]
只有发生冲突的时候才使用分值.

example  中国家     

中国 5分  国家 10分..结果就是  中 国家

**Comment by ansjsun** [comment]
但是这个前提是核心词典处理后发生冲突...再此之前是核心词典优先..建议你使用DicAnalysis应该最接近你的需求..
