### ISSUE TITLE
 Part of speech tagging:

### ISSUE THREAD

**Issue by dreambander** [NLPchina/ansj_seg#669]
Hello, I have seen more than 40 part-of-speech meanings on the wiki, but there are still many meanings such as NRF. Do you have all the corresponding part-of-speech meanings used in the dictionary? Thank you very much for your reply.

**Comment by ansjsun** [comment]
nrf 是外国人名..我只能保证核心词典的词性.default.dic属于用户自定义词典.是可变奔放的..有些词性我想说..你猜
