### ISSUE TITLE
分词出现明显错误

### ISSUE THREAD

**Issue by wzlsquall** [NLPchina/ansj_seg#670]
例句：
请问贵司英文公司名为何?

分词结果：
请问:v 贵司:nr 英文:nz 公司:n 名:q 为:p 何?:nr

【何?】被作为一个整体进行分词了

**Comment by wzlsquall** [comment]
另外ToAnalysis和NLPAnalysis对下面这句话分词结果也不一样，比较奇怪
例句：
支付所使用的发票付汇联如何送到银行核销？

ToAnalysis：支付:vn 所:u 使用:v 的:u 发票:n 付汇联:n 如何:r 送到:v 银行:n 核销:v ？:w
NLPAnalysis：支付:vn 所:u 使用:v 的:u 发票:n 付汇联:n 如何:r 送:v 到:v 银行:n 核销:v ？:w 

送到这个词被做了不同的分解

**Comment by ansjsun** [comment]
如果一樣的話。。爲啥要做兩個
