### ISSUE TITLE
自定义分词的效果问题

### ISSUE THREAD

**Issue by wwwwushaoxiong** [NLPchina/ansj_seg#674]
1、System.out.println(NlpAnalysis.parse("本月工资明细"));
Value value_new = new Value("本月工资", "本月", "nt", "工资", "j");
Library.insertWord(AmbiguityLibrary.get(), value_new);		
System.out.println(NlpAnalysis.parse("本月工资明细"));
//这边解读出来的把“本月工资”当做一个新词（nw），请大神帮忙看下，或者留个联系方式啊？
2、针对我自定义的一些词，貌似没啥效果，直接引入包，自定义会包找不到对应文件的路径。
     但是加了那些文件，貌似结果也没啥效果，能给个简单示例试试？

**Comment by wwwwushaoxiong** [comment]
哦哦。。好的。。非常感谢。只是我这边是针对很多不可意料的词，不能说针对这个词进行做特殊处理。if(searchWord='本月工资明细')DicAnalysis.parse("本月工资明细")。有没有先针对时间的词做优先分词？

**Comment by ansjsun** [comment]
目前沒有額
