### ISSUE TITLE
自定義詞典找不到的問題

### ISSUE THREAD

**Issue by yuhyuh1225** [NLPchina/ansj_seg#676]
![image](https://user-images.githubusercontent.com/42918778/44961147-6f017600-af3e-11e8-9b05-17d9ab393140.png)
library應該是放主目錄吧?
![image](https://user-images.githubusercontent.com/42918778/44961154-95271600-af3e-11e8-85e5-2f9452132d13.png)
然後ansj_library.properties放resources
![image](https://user-images.githubusercontent.com/42918778/44961169-c4d61e00-af3e-11e8-8bb9-7e30fe3c6c7d.png)
還是找不到 搞了好久
請問各位哪裡做錯

**Comment by shi-yuan** [comment]
可以调试下https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/dic/impl/File2Stream.java的31行，看看那个路径
或者
写上绝对路径

**Comment by yuhyuh1225** [comment]
![image](https://user-images.githubusercontent.com/42918778/45254461-279a4000-b3ab-11e8-9ab4-dd1e84d1f4f2.png)

絕對路徑好像也不行耶
跟android studio有關係嗎

**Comment by bizkitj** [comment]
![capture](https://user-images.githubusercontent.com/25093538/46200249-b9aabe00-c343-11e8-8e60-0449c830063b.PNG)


![capture](https://user-images.githubusercontent.com/25093538/46200343-f7a7e200-c343-11e8-8257-dfad5e0b52f5.PNG)

**Comment by bizkitj** [comment]
自定义词典着魔了：

当运行local unit test的时候，
if  library文件夹放到app下
else 放到app/src下
else 放到app/src/main下，
else 放到app/src/main/resources下
unit test显示用户自定义词典加载成功。

在以上任何一种情况下，ambiguity.dic和stop.dic和synonyms.dic都是找不到文件。

![capture_01](https://user-images.githubusercontent.com/25093538/46943398-27741b00-d0a2-11e8-80ec-407341b2be3b.PNG)


当在emulator或者具体设备上运行的时候，
if  library文件夹放到app下
else 放到app/src下
else 放到app/src/main下，
else 放到app/src/main/resources下
unit test显示用户自定义词典加载成功。

所有字典都没起作用。

怎么办呢？求助，求助大神。

**Comment by shi-yuan** [comment]
可以调试下，[File2Stream.java](https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/dic/impl/File2Stream.java)的31行，看看那个路径
或者
可以自定义加载方式，自己实现[PathToStream](https://github.com/NLPchina/ansj_seg/blob/master/src/main/java/org/ansj/dic/PathToStream.java)，然后路径写class://xxx|xxx

**Comment by bizkitj** [comment]
太麻烦了，折腾这路径。算了
最后这样了。可以用。
```
public class MyDicLoader {
    private Context context;

    public MyDicLoader(Context context) {
        this.context = context;
    }

    public void loadMyDict() {
        String[] dicArray = context.getResources().getStringArray(R.array.default_dic);
        for (String keyWord : dicArray) {
            UserDefineLibrary.insertWord(keyWord, "n", 1000);
        }
    }
}
```

**Comment by ansjsun** [comment]
就這樣了？？？
