### ISSUE TITLE
请问如果想做复杂地名的识别的话，需要做些什么改进呢？

### ISSUE THREAD

**Issue by symsimmy** [NLPchina/ansj_seg#679]
目前ansj可以识别如：上海市/ns
但如何做到识别：中国上海市杨浦区华佗路23号。这种地名呢？
希望大家提供一下思路。或者有没有类似的工具

**Comment by ansjsun** [comment]
自己写规则吧...也没好的办法..

**Comment by BigInventor** [comment]
分词+字典+正则吧

**Comment by symsimmy** [comment]
@ansjsun 感谢,果然最后还是要上规则
