### ISSUE TITLE
中文情感分析

### ISSUE THREAD

**Issue by xuelinchao** [NLPchina/ansj_seg#680]
你实例代码里的dic_sentiment词库没有啊，是什么格式的，能给一份吗1356408625@qq.com，谢谢

**Comment by ansjsun** [comment]
[sentiment.zip](https://github.com/NLPchina/ansj_seg/files/2373177/sentiment.zip)

有可能格式你得改改 .....

**Comment by xuelinchao** [comment]
能问一下你这个情感分析用什么方法实现的吗

**Comment by ansjsun** [comment]
我的辦法很low，基於數大小做的。當然你可以做的更好。
