### ISSUE TITLE
python引用jar包,找不到类

### ISSUE THREAD

**Issue by JinmingZhao** [NLPchina/ansj_seg#681]
环境: python2.7 jdk1.6.0_45
jar 包版本: tree_split-1.5.jar 和 ansj_seg-5.1.6.jar

代码:
`#!coding=utf-8
import jpype
import os
jvmPath = '/usr/lib/java/jdk1.6.0_45/jre/lib/amd64/server/libjvm.so'
print jvmPath

jars_dir = '/mnt/data/pretrained_models/word2vec_models/jars4ansj'
jars = [os.path.join(jars_dir, 'ansj_seg-5.1.6.jar'), os.path.join(jars_dir, 'tree_split-1.5.jar')]

jvm_cp = "-Djava.class.path={}".format(':'.join(jars))
jpype.startJVM(jvmPath, "-ea", jvm_cp)
print "-----------------"
JDClass = jpype.JClass('org.ansj.splitWord.analysis.NlpAnalysis')
jd = JDClass()
jd.parse("怎么这么麻烦")

jpype.shutdownJVM()`

报错信息:
/usr/lib/java/jdk1.6.0_45/jre/lib/amd64/server/libjvm.so
Traceback (most recent call last):
  File "ansj_segment.py", line 13, in <module>
    JDClass = jpype.JClass('org.ansj.splitWord.analysis.NlpAnalysis')
  File "/home/jinmming/anaconda2/lib/python2.7/site-packages/jpype/_jclass.py", line 73, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class org.ansj.splitWord.analysis.NlpAnalysis not found

之前看报错是由于jdk版本, 后来由jdk1.8换到jdk1.6还是不行, 求大神指教, 看看还有什么遗漏的细节?
jar包的导入没有问题, 就是寻找类的时候报错了.

**Comment by JinmingZhao** [comment]
@ansjsun

**Comment by yongzhuo** [comment]
这么弄，报错，求助：
import jpype
import os

jvmPath = 'D:/software/Java/Java8/jre/bin/server/jvm.dll'
print (jvmPath)
jars_dir_ansj_seg = 'D:/software/IDEA/tools/maven_soft/org/ansj/ansj_seg/5.1.6'
jars_dir_nlp_lang = 'D:/software/IDEA/tools/maven_soft/org/nlpcn/nlp-lang/1.7.7'
jars_dir_tree_split = 'D:/software/IDEA/tools/maven_soft/org/ansj/tree_split/1.5'
jars = [os.path.join(jars_dir_ansj_seg, 'ansj_seg-5.1.6.jar'), os.path.join(jars_dir_nlp_lang, 'nlp-lang-1.7.7.jar'), os.path.join(jars_dir_tree_split, 'tree_split-1.5.jar')]
jvm_cp = "-Djava.class.path={}".format(':'.join(jars))
jpype.startJVM(jvmPath, "-ea", jvm_cp)
SegModel = jpype.JClass('org.ansj.splitWord.analysis.ToAnalysis')
jd = SegModel()
print(jd.parseStr("怎么这么麻烦"))
jpype.shutdownJVM()



报错：
Connected to pydev debugger (build 172.4574.37)
D:/software/Java/Java8/jre/bin/server/jvm.dll
Traceback (most recent call last):
  File "D:\software\pycharm\PyCharm 2017.2.7\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\software\pycharm\PyCharm 2017.2.7\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\software\pycharm\PyCharm 2017.2.7\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/workspace/python/django_server/nlp_app/segment/ansj_seg_Jpype.py", line 18, in <module>
    SegModel = jpype.JClass('org.ansj.splitWord.analysis.ToAnalysis')
  File "D:\software\Anaconda3\envs\py36\lib\site-packages\jpype\_jclass.py", line 55, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class org.ansj.splitWord.analysis.ToAnalysis not found

**Comment by yongzhuo** [comment]
> 这么弄，报错，求助：
> import jpype
> import os
> 
> jvmPath = 'D:/software/Java/Java8/jre/bin/server/jvm.dll'
> print (jvmPath)
> jars_dir_ansj_seg = 'D:/software/IDEA/tools/maven_soft/org/ansj/ansj_seg/5.1.6'
> jars_dir_nlp_lang = 'D:/software/IDEA/tools/maven_soft/org/nlpcn/nlp-lang/1.7.7'
> jars_dir_tree_split = 'D:/software/IDEA/tools/maven_soft/org/ansj/tree_split/1.5'
> jars = [os.path.join(jars_dir_ansj_seg, 'ansj_seg-5.1.6.jar'), os.path.join(jars_dir_nlp_lang, 'nlp-lang-1.7.7.jar'), os.path.join(jars_dir_tree_split, 'tree_split-1.5.jar')]
> jvm_cp = "-Djava.class.path={}".format(':'.join(jars))
> jpype.startJVM(jvmPath, "-ea", jvm_cp)
> SegModel = jpype.JClass('org.ansj.splitWord.analysis.ToAnalysis')
> jd = SegModel()
> print(jd.parseStr("怎么这么麻烦"))
> jpype.shutdownJVM()
> 
> 报错：
> Connected to pydev debugger (build 172.4574.37)
> D:/software/Java/Java8/jre/bin/server/jvm.dll
> Traceback (most recent call last):
> File "D:\software\pycharm\PyCharm 2017.2.7\helpers\pydev\pydevd.py", line 1599, in 
> globals = debugger.run(setup['file'], None, None, is_module)
> File "D:\software\pycharm\PyCharm 2017.2.7\helpers\pydev\pydevd.py", line 1026, in run
> pydev_imports.execfile(file, globals, locals) # execute the script
> File "D:\software\pycharm\PyCharm 2017.2.7\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "D:/workspace/python/django_server/nlp_app/segment/ansj_seg_Jpype.py", line 18, in 
> SegModel = jpype.JClass('org.ansj.splitWord.analysis.ToAnalysis')
> File "D:\software\Anaconda3\envs\py36\lib\site-packages\jpype_jclass.py", line 55, in JClass
> raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
> jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class org.ansj.splitWord.analysis.ToAnalysis not found

已解决：
将jvm_cp = "-Djava.class.path={}".format('：'.join(jars))中的冒号转为分号就可以了jvm_cp = "-Djava.class.path={}".format(';'.join(jars))
