### ISSUE TITLE
单个字搜索不出来

### ISSUE THREAD

**Issue by 18222962201** [NLPchina/ansj_seg#683]
分词方式采用 IndexAnalysis 面向索引的分词 ,但是比如搜索  "挂面". 可以出来商品,单独搜"挂","面",都出不来,求大神解决

**Comment by ansjsun** [comment]
这种..最好用单字分词.StandardAnalyzer.也可以两个分词器结合使用

**Comment by vincentddman** [comment]
搜索介绍中的面向索引的分词http://nlpchina.github.io/ansj_seg/
召回率似乎没有实现到...输入"主副食品"
IndexAnalysis.parse("主副食品");
得到的结果就只有"主副食品"没有像说明说到的得到result:[主副食品/n, 主副食, 副食, 副食品, 食品]这样的结果，请问大神如何解决这问题？

**Comment by ansjsun** [comment]
需要挂在自定义词典.

https://github.com/NLPchina/ansj_seg/blob/master/library/default.dic

**Comment by vincentddman** [comment]
问题在于自定义词典内确实存在这几个单词https://github.com/NLPchina/ansj_seg/blob/master/library/default.dic中
62785行	主副食品	n	13
73357行	主副食	n	3
54205行	副食	n	36
45507行	副食品	n	86
28883行	食品	n	6610
但是面向索引分词还是像一般分词一样没有召回率的显示

**Comment by ansjsun** [comment]
是挂了自定义词典..没有出来这些词吗?

可能是词典没挂载成功,一般出现这种问题是词典路径问题.

再分词启动的时候回打印加载情况的日志.仔细阅读.或者发上来看看呗
