### ISSUE TITLE
bug：分词将原文本转成小写了

### ISSUE THREAD

**Issue by FergusChen** [NLPchina/ansj_seg#694]
使用版本：5.1.1，
方法：ToAnalysis.parse("他们在G302国道上")
测试发现，分词把“G”转为小写的“g”， 这个应该是一个bug，需要修复下。

**Comment by shi-yuan** [comment]
要取原文本，可以读realName

**Comment by FergusChen** [comment]
> 要取原文本，可以读realName

5.1.1版本的getRealName()获取的还是name呢。你可以试下，所有的英文都是转小写的~ 
我后来用line.substring(term.getOffe(), term.toValue()) 自己截取了，不知道有没有更好的办法。

**Comment by shi-yuan** [comment]
isRealName设置成true了吗？

**Comment by FergusChen** [comment]
> isRealName设置成true了吗？

哦，之前没有添加library.properties， 用的默认值。
现在好了，谢谢啦
