### ISSUE TITLE
核心字典（core.dic）base怎么生成的

### ISSUE THREAD

**Issue by cbycao** [NLPchina/ansj_seg#696]
index	name	base	check	status,nature
22902	奶	107377	-1	2	{n=23,v=0}
33590	茶	218899	-1	2	{n=12,ng=0}
140967	奶茶	65536	22902	3	{n=0}
index(奶茶)=base(奶)+index(茶)
check(奶茶)=index(奶)
该字典中base是什么算法生成的，我的理解base要保障依赖base生成的index不重复，且尽量保障index数值最小，保证字典数组非空元素少

**Comment by ansjsun** [comment]
nlp-lang 里面有dat的构造方式。。

**Comment by cbycao** [comment]
非常感谢

**Comment by ansjsun** [comment]
年度清理
