### ISSUE TITLE
IndexAnalysis的分词效果和其他分词似乎没有区别

### ISSUE THREAD

**Issue by DengYiPeng** [NLPchina/ansj_seg#697]
String str = "洁面仪配合洁面深层清洁毛孔 清洁鼻孔面膜碎觉使劲挤才能出一点点皱纹 脸颊毛孔修复的看不见啦 草莓鼻历史遗留问题没辙 脸和脖子差不多颜色的皮肤才是健康的 长期使用安全健康的比同龄人显小五到十岁 28岁的妹子看看你们的鱼尾纹" ;
       
        System.out.println(BaseAnalysis.parse(str));

        System.out.println(ToAnalysis.parse(str));

        System.out.println(DicAnalysis.parse(str));

        System.out.println(IndexAnalysis.parse(str));

        System.out.println(NlpAnalysis.parse(str));

![image](https://user-images.githubusercontent.com/14267220/47344709-afc67180-d6db-11e8-971d-ad791273eb0d.png)

我按照使用帮助上的测试方法对五种方法的分词结果进行了测试。
但是如上图所示，IndexAnalysis分词的效果和其他分词结果并没有区别，怎么才能够实现索引分词的效果呢？
（Ansj的版本是5.1.6）

**Comment by ansjsun** [comment]
沒有加載自定義詞典導致
