### ISSUE TITLE
停用词辞典配置

### ISSUE THREAD

**Issue by xuelinchao** [NLPchina/ansj_seg#698]
现在是不能在library.properties里面直接添加停用词辞典路径来配置停用词了吗？只能自己通过StopRecognition来添加停用词了吗

**Comment by shi-yuan** [comment]
可以添加配置啊

**Comment by xuelinchao** [comment]
> 可以添加配置啊

请问你的配置是怎么写的，我添加了都不起作用

**Comment by xuelinchao** [comment]
> 可以添加配置啊

@shi-yuan 请问你的配置是怎么写的，怎么我写的不起作用啊

**Comment by xuelinchao** [comment]
> 可以添加配置啊

@shi-yuan 请问你的配置是怎么写的，怎么我写的不起作用啊，还有你用的是哪个版本

**Comment by shi-yuan** [comment]
这么配置的：https://github.com/NLPchina/ansj_seg/blob/master/ansj_library.properties

stop=停用词典路径

**Comment by Jaschenn** [comment]
我添加了stop=XXX
但是运行过程中好像忽略了这个配置一样
这是log

 INFO - init stop_dic to env value is : src/main/resources/stopLibrary.dic
 INFO - init dic to env value is : src/main/resources/Ai.dic
DEBUG - begin init dic !
 INFO - path to stream src/main/resources/Ai.dic
 INFO - load dic use time:25 path is : src/main/resources/Ai.dic
 INFO - path to stream library/ambiguity.dic
DEBUG - begin init ambiguity
 INFO - load dic use time:0 path is : library/ambiguity.dic
DEBUG - begin init crf model!
 INFO - load crf model ok ! use time :2376
 INFO - load crf use time:2383 path is : jar://crf.model
 INFO - init core library ok use time : 613
 INFO - init ngram ok use time :829

现在是不是不支持通过配置加载停用词词典了
版本是5.1.1

**Comment by shi-yuan** [comment]
支持的吧

**Comment by Jaschenn** [comment]
当我使用StopRecognition的时候是没有任何问题的：

```
 StopRecognition filter = new StopRecognition();
        filter.insertStopNatures("r");
        String text = "半监督学习是一种智能的学习方案，不然是什么呢？";
        Result result = NlpAnalysis.parse(text).recognition(filter);
        System.out.println(result);
```
结果如下：
半监督学习/n,是/v,一种/m,智能/n,的/uj,学习/v,方案/n,，/w,不然/c,是/v,呢/y,？/w


但是在log中依然没有任何的提示停用词词典的加载过程

> 

> INFO - init stop to env value is : src/main/resources/stopLibrary.dic
>  INFO - init dic to env value is : src/main/resources/Ai.dic
> DEBUG - begin init dic !
>  INFO - path to stream src/main/resources/Ai.dic
>  INFO - load dic use time:25 path is : src/main/resources/Ai.dic
>  INFO - path to stream library/ambiguity.dic
> DEBUG - begin init ambiguity
>  INFO - load dic use time:0 path is : library/ambiguity.dic
> DEBUG - begin init crf model!
>  INFO - load crf model ok ! use time :1793
>  INFO - load crf use time:1798 path is : jar://crf.model
>  INFO - init core library ok use time : 718
>  INFO - init ngram ok use time :1135

我的配置如下：
```
#path of userLibrary
dic=src/main/resources/Ai.dic
stop=src/main/resources/stopLibrary.dic
```
版本是5.1.1，不知道这样是否有问题？
我在demo中找到的配置没有加载停用词字典的，只有dic和ambiguity，并且我按照demo成功了。

**Comment by Jaschenn** [comment]
当然，现在可以这样使用：
```
 StopRecognition filter = new StopRecognition();
        List<String> lines = FileUtils.readLines(new File("stopLibrary.dic"),"utf-8");
        filter.insertStopWords(lines);
```

**Comment by shi-yuan** [comment]
用的版本确实很旧了。。。

**Comment by ansjsun** [comment]
年度清理
