### ISSUE TITLE
人名识别问题

### ISSUE THREAD

**Issue by ihundan** [NLPchina/ansj_seg#702]
字符串"曾丹,曾琛,曾才龙,"与字符串"曾丹,曾琛,曾才龙"分词结果不一样（**字符串最后一个逗号影响分词**）。前者仅分析出曾丹是人名，后者能分析出曾丹曾才龙两个人名。这是什么原因

**Comment by ansjsun** [comment]
用的人名識別模型是crf或者hmm都會有類似問題。很難説清楚。。統計模型的缺點就是穩定性。所以只能添加詞典來解決了
