### ISSUE TITLE
wiki文档下载jar包地址不可用

### ISSUE THREAD

**Issue by huht123** [NLPchina/ansj_seg#709]
可以从 http://maven.ansj.org/org/ansj/ 或http://maven.nlpcn.org下载你需要的jar包  这两个地址目前都打不开...

**Comment by ansjsun** [comment]
你从哪看到的。我现在过去把它删了

**Comment by ansjsun** [comment]
先从maven中央仓库下载吧。




在2019年01月28日 18:58，shiyuan 写道：

这儿，找到的：
https://github.com/NLPchina/ansj_seg/wiki/%E8%8E%B7%E5%BE%97jar%E5%8C%85

**Comment by huht123** [comment]
好的
