### ISSUE TITLE
动态添加自定义词典的功能，感觉挺常用的，但是文档好像没有更新

### ISSUE THREAD

**Issue by huht123** [NLPchina/ansj_seg#710]
https://github.com/NLPchina/ansj_seg/wiki/%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%85%B8   这个地方

**Comment by ansjsun** [comment]
是沒有更新。如果您有興趣幫忙更新一下唄

不過你可以看test 裏面有寫例子
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/library/DicLibraryTest.java
https://github.com/NLPchina/ansj_seg/blob/master/src/test/java/org/ansj/dic/impl/Jar2StreamTest.java
