### ISSUE TITLE
在手机上使用如何提高加载速度

### ISSUE THREAD

**Issue by 15289663969** [NLPchina/ansj_seg#712]
我开发的app使用了分词库，但是我发现第一次使用时加载速度很慢。因为用的比较急，还没来得及全部理解源代码——估计也很困难。该怎样解决？

**Comment by ansjsun** [comment]
这个分词内存占用很大。。实际上不建议移动设备上用。
建议你参考一下其他项目的分词器。好的一点是。基本上所有的中文分词器都是这么个套路了。。返回格式也接近。对你来说改动不大的。。

**Comment by 15289663969** [comment]
好的，谢谢。事实上我使用前有度娘过，开源的分词器比较好的貌似就是jieba和ansj_seg。但是jieba安卓版的没有标注词性，而我只需要分词后的名词，而ansj_seg又没有针对移动版优化，真是一个尴尬的局面。

**Comment by ansjsun** [comment]
你可以看看 hanlp 可以不额 。。。。
