### ISSUE TITLE
可以停用默认词典么，只使用自定义词典

### ISSUE THREAD

**Issue by XuanMiaoJ** [NLPchina/ansj_seg#724]
我这边想停用默认词典，因为我这边自定义的一些词典中的词不会取到，取得还都是默认词典中的

**Comment by XuanMiaoJ** [comment]
或者加载顺序以自定义词典为准

**Comment by neilwyh** [comment]
用DicAnalysis

**Comment by hueyzng** [comment]
使用 DicAnalysis 只会优先使用用户词典。我也想知道能不能停用，在代码里找了一圈没发现有开关可以停用，假如强行 Hack 了以后不知道会不会导致其他问题。针对精确搜索的场景，默认分词有一定概率影响分词结果，所以我现在的做法是分词结果出来以后忽略所有用户词典内的词性以外的词。

但是在一些情况下出现了意外，例如：已在用户词典添加了“出血”词性为“不良反应”，当用户搜索“大出血”时的分词结果是“大出血/v”，期望能够分词出“出血”词性为“不良反应”，搜索结果变的很不可控。虽然可以添加歧义词，解决这个问题，但是也无法穷举所有的情况。

**Comment by ansjsun** [comment]
hack 进去 在 core.dic 找到这个词删了。。
