### ISSUE TITLE
你好，我用的是最新的5.1.6版本，IndexAnaylsis索引分词是不是有问题？

### ISSUE THREAD

**Issue by AlanZuora** [NLPchina/ansj_seg#737]
Result parse = IndexAnalysis.parse("主副食品")看doc文档说能有result:[主副食品/n, 主副食, 副食, 副食品, 食品]这种效果，但是为什么结果就只有一个词？

**Comment by ansjsun** [comment]
没有加载用户自定义词典




在2019年10月20日 18:57，AlanZuora 写道：

Result parse = IndexAnalysis.parse("主副食品")看doc文档说能有result:[主副食品/n, 主副食, 副食, 副食品, 食品]这种效果，但是为什么结果就只有一个词？

**Comment by AlanZuora** [comment]
谢谢回答，但我现在的运用场景是需要用到索引分词，例如：主副食品 我需要分成主副食, 副食, 副食品, 食品，这几个词，难道我需要一个个在自定义词典里面去添加？请问如何解决？没有提供细粒度分词接口直接使用的？

> 没有加载用户自定义词典 在2019年10月20日 18:57，AlanZuora 写道： Result parse = IndexAnalysis.parse("主副食品")看doc文档说能有result:[主副食品/n, 主副食, 副食, 副食品, 食品]这种效果，但是为什么结果就只有一个词？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ansjsun** [comment]
https://github.com/NLPchina/ansj_seg/tree/master/library <https://github.com/NLPchina/ansj_seg/tree/master/library>

下周 default.dic 就是 https://github.com/NLPchina/ansj_seg/blob/master/library/default.dic <https://github.com/NLPchina/ansj_seg/blob/master/library/default.dic>

这个

**Comment by charleshm** [comment]
为啥现在结果是 “主副食品,主副食,主,副食品,副食,副,食品,食,品”，产生了很多单字？

**Comment by ansjsun** [comment]
@charleshm 吧自定义词典中的单字去掉就可以
