### ISSUE TITLE
判断分词正确率的算法存在问题，导致实际结果偏高

### ISSUE THREAD

**Issue by zhangtaochn** [NLPchina/ansj_seg#745]
在这个文件中，/src/test/java/org/ansj/app/crf/model/CRFModelTest.java
分词结果的判断当中：[（88行~98行）](https://github.com/NLPchina/ansj_seg/blob/4deadeb54c27e9d5bf0f7632e8b2571e9ff83c8d/src/test/java/org/ansj/app/crf/model/CRFModelTest.java#L89)

				offe = 0;
				for (String word : paser) {
					if (had_words_array[offe] == null) {
						error++;
					} else if (had_words_array[offe].equalsIgnoreCase(word)) {
						success++;
					} else {
						success++;
					}
					offe += word.length();
				}

如果
String[] result =  {“中共“,  “中央”, “红军”, "长征"};
String[] paser = {“中“,  “共中央”, “红军长”, "征"};
计算之后依然会有50%的正确率。
应该将第95修改为 error++;

**Comment by ansjsun** [comment]
之前有个记录 比如  中国人民万岁 。分成 中国 ， 人民， 万岁 或者 中国人民 ， 万岁。都算正确。但是 召回率会变低。准确率高。最终参考f值
