### ISSUE TITLE
新词发现可以标注非词嘛

### ISSUE THREAD

**Issue by wufan1993** [NLPchina/ansj_seg#752]
新发现的词标注为非词字典库，这样下次训练的时候可以不用出现这些词

**Comment by ansjsun** [comment]
不好意思额，不可以标注。没有这个功能。也不知道该怎么做

**Comment by wufan1993** [comment]
谢谢哈，我也不太懂算法这一块，只会用，目前暂时只是自己弄了一个标记的池子，然后对训练出来的词做过滤来使用了，没有让他参与二次训练，只是感觉非词标注好后可能可以进一步提升训练效果
