### ISSUE TITLE
求一个文件加载的用户自定义词典

### ISSUE THREAD

**Issue by st18601019822** [NLPchina/ansj_seg#780]
按照案例的方式做了一下，但是没有加载成功，不知道是哪一步错了，尝试了llibrary.properties里添加dic=library\userLibrary.dic，也尝试了MyStaticValue.putLibrary(key,path)，也尝试了Library.makeForest，但是都没有成功

**Comment by ansjsun** [comment]
启动的时候有log 。显示从哪里加载词典。仔细观察。然后把词典放到那个路径就可以。

还可以如果 相对路径有问题。用绝对路径试试

**Comment by SeeWorldBaby** [comment]
这么不智能？还要启动之后看日志，那我们生产环境部署难道要自己拷贝dic文件？
