### ISSUE TITLE
使用computeArticleTfidf进行关键词搜索的时候，能够引入stopword生效么？

### ISSUE THREAD

**Issue by tonyYu1115** [NLPchina/ansj_seg#785]
你好：
     stopword用配置文件的方式，目前并不生效，通过StopRecognition进行filter过滤DicAnalysis.parse结果是可以生效的。请问使用computeArticleTfidf获取关键字时，无法使用filter了，那么有什么办法可以使stopword配置文件生效么？

**Comment by shi-yuan** [comment]
这个需要改进，支持设置Recognition
