### ISSUE TITLE
怎么跳过默认的core.dic词库

### ISSUE THREAD

**Issue by Lan0618** [NLPchina/ansj_seg#801]
默认初始化是加载core.dic后导致自定义词典部分词失效
![image](https://github.com/NLPchina/ansj_seg/assets/53222856/6c681045-ac7f-408a-9a2f-1d1de58fd137)
深河乡是我自定义词 /adr有标签 但是解析是被core.dic中的词库解析成乡镇

**Comment by ansjsun** [comment]
可以通过添加歧义词库来避免这种错分。
关键词 Ambiguity  https://github.com/NLPchina/ansj_seg/blob/50787ca2c7031d2a18c5393a97d1a54432790785/src/test/java/org/ansj/test/TestError.java#L251
