### ISSUE TITLE
可以删除default.dic中， 和 array.dic的交集码

### ISSUE THREAD

**Issue by AtomWyq** [NLPchina/ansj_seg#92]
我用的是0.8
发现default.dic和 array.dic有交集

可以删除default.dic中的交集部分吗

**Comment by yeyefengisme** [comment]
你好，请问，我修改了default .dic中某些词的词性，为什么获取不到修改后的性，而还是之前的词性。

**Comment by ansjsun** [comment]
已经在另一个回答了
